### PR TITLE
Two small bugfixes

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

I am commiting two very small bug fixes. One allows to open gzipped ICOHPLIST.lobster files. The other one closes the plt after saving a plot with a phonon dos with the PhononDosPlotter. This is done similar to "save_plot" in PhononBSPlotter.

### CODE REVIEW

**Comment by JaGeo** [comment]
I will work on a test for the ICOHPLIST.gz.

**Comment by JaGeo** [comment]
Travis CI is complaining about missing docstrings. Do I need to change this?

**Comment by JaGeo** [comment]
Should I add the docstrings? If so, let me know.

**Comment by shyuep** [comment]
Yes pls. Thanks.

**Comment by JaGeo** [comment]
I think it is ready to be merged.

**Comment by mkhorton** [comment]
Thanks!

**Pull request merged**
