### PR TITLE
Add new functionality to Lobsterin class and some fixes

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

Include a summary of major changes in bullet points:

-I have introduced a new static method to the Lobsterin class that can return a list of possible basis sets for Lobster runs. And, I also added files that help creating theses basis sets.

-To restructure the code, I have also created a lobster folder and moved tests and classes there. I have also made sure that the code is backwards compatible.

-I have fixed some tests for Lobster and also added a new one for the new functionalities.

Before a pull request can be merged, the following items must be checked:

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). 
      Run [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/) and [flake8](http://flake8.pycqa.org/en/latest/)
      on your local machine.
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) 
      to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All existing tests pass.

Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is
highly recommended that you use the pre-commit hook provided in the pymatgen 
repository. Simply `cp pre-commit .git/hooks` and a check will be run prior to
allowing commits.

### CODE REVIEW

**Comment by JaGeo** [comment]
Hi!
I don't think the failing tests are from my changes.

Best, 
JG

**Comment by mkhorton** [comment]
We've had an IonEntry bug in master for the past week, I think a PR from @knc6 just fixed it. Please try merging in from master and hopefully tests should pass, otherwise this looks great.

What's the distinction between the min/max PBE_54 bases?

**Comment by JaGeo** [comment]
I hope it is working now.

min: all occupied valence orbitals according to the POTCAR
max: all valence orbitals according to the POTCAR
Both files have an additional condition: basis functions have to be present in Lobster.

**Comment by JaGeo** [comment]
Sorry, my fault. Will fix the test - I have moved one file.

**Comment by mkhorton** [comment]
Thanks @JaGeo !

**Pull request merged**
