### PR TITLE
Modified dosplotter

### PR DESCRIPTION
**Pull request by kaueltzen**
- added arguments in Dosplotter class to plot DOS w. inverted axes (as common in chemistry) and to plot beta spin channel w. dashed line
- debugged CohpPlotter class: limit determination and display of energy axis
- added tests for automatic limit determination in DosPlotter class (especially to test if DOS and energy axis outputs are the same for inverted and non-inverted case)

### CODE REVIEW

**Comment by janosh** [comment]
Thanks @kaueltzen! 👍

**Comment by janosh** [comment]
Let me know when this is ready to merge.

**Comment by janosh** [comment]
Let me know when this is ready to merge.

**Comment by janosh** [comment]
Let me know when this is ready to merge.

**Comment by kaueltzen** [comment]
Hey @janosh , this is ready to merge(:

**Comment by janosh** [comment]
`mypy` is failing. you can try and fix the errors or (if that's too much hassle) decorate the plot function with

```py
import typing

@typing.no_type_check
```

**Comment by kaueltzen** [comment]
Thanks, I decorated the get_plot method. If required, I can look into fixing the mypy errors when I have more time.

**Comment by janosh** [comment]
GitHub actions are currently down https://www.githubstatus.com. Hopefully, tests will run later today.

**Comment by JaGeo** [comment]
Yeah! @kaueltzen 's first pymatgen contribution!

**Comment by janosh** [comment]
Congrats @kaueltzen! Very nice work even including tests in your first PR. 👏

**Pull request merged**
