### PR TITLE
Parser to read lammps style input files

### PR DESCRIPTION
**Pull request by wood-b**
## Summary 
I added a parser to read lammps style input files directly. This is useful if input files do not need to be generated.

* read a lammps style input file

## TODO

 More comprehensive unittest. Check if total number of atom, bonds, diheadrals ... etc. are added to DictLammpsInput

### CODE REVIEW

**Comment by shyuep** [comment]
Pls make the method a classmethod, rather than a static method, and also rename the method to follow the convention used in other classes. It should be from_file.

**Comment by wood-b** [comment]
I consolidated the JSON and lammps style input parsers in the from_file method and changed it from a staticmethod to classmethod.

**Comment by wood-b** [comment]
Test files moved to standard location, all related tests should pass.

**Comment by shyuep** [comment]
Thanks.

**Pull request merged**
