### PR TITLE
fix: #1985 and add test to stop computed entry being used for get_quasi_e_to_hull

### PR DESCRIPTION
**Pull request by CompRhys**
@rkingsbury 

As the proper fix in #2014 seems like it might still take a while to get merged this is the temp fix I should have done for #1985 when I first saw it. It avoids the bug that I introduced by not (at that point) being aware that `ComputedEntry` was supposed to be interoperable with `PDEntry` and adds a catch to stop another bug in `get_quasi_e_to_hull` that would be caused by the same issues with `__eq__` and `__hash__` for `ComputedEntry` that caused this bug.

### CODE REVIEW

**Comment by rkingsbury** [comment]
Thanks @CompRhys ! I appreciate you doing this and I know that #2014 has become more involved than originally expected. This fixes #1985 at least insofar as it affects my use cases and looks like a very reasonable stopgap solution. @mkhorton , do you have any concerns about merging this as a temporary fix?

**Comment by mkhorton** [comment]
@rkingsbury I plan to merge both asap, stay tuned... I think #2014 is in good shape, though it did indeed end up longer than originally intended :-)

**Comment by mkhorton** [comment]
Given that #2014 is merged, shall we close this?

**Comment by rkingsbury** [comment]
OK with me @mkhorton !

**Comment by CompRhys** [comment]
not needed due to #2014!

**Pull request closed without merging**
