### PR TITLE
🛠  fixes the issue in parsing `bandOverlaps.lobster` file

### LINKED ISSUE #2236: 🐞 Bug in parsing `bandOverlaps.lobster` file
**Describe the bug**
Generated `bandOverlaps.lobster` file by `Lobster` (tested with `v4.0.0` and `v4.1.0`), writes spin as `spin 1` and `spin 2`. In the `self._read` method here, spins are parsed as `spin 0` and `spin 1` and therefore, it misses `spin 2` and fails. 

**To Reproduce**
I have attached two following files generated by different versions of `Lobster`: 

[bandOverlaps.lobster_v4.0.0.txt](https://github.com/materialsproject/pymatgen/files/7109557/bandOverlaps.lobster_v4.0.0.txt)
[bandOverlaps.lobster_v4.1.0.txt](https://github.com/materialsproject/pymatgen/files/7109558/bandOverlaps.lobster_v4.1.0.txt)

The following snippet:
```python
from pymatgen.io.lobster.outputs import Bandoverlaps
Bandoverlaps(filename='./bandOverlaps.lobster_v4.0.0.txt')
Bandoverlaps(filename='./bandOverlaps.lobster_v4.1.0.txt')
```
would results in following exception:
```console
ValueError: could not convert string to float: 'Overlap'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/gv/d3m49bs95kl97vw2w2b6k78m0000gp/T/ipykernel_94202/4051178229.py in <module>
----> 1 Bandoverlaps(filename='./bandOverlaps.lobster_v4.0.0.txt')

~/.local/software/miniforge3/envs/aiida/lib/python3.9/site-packages/pymatgen/io/lobster/outputs.py in __init__(self, filename)
   1304             contents = f.read().split("\n")
   1305 
-> 1306         self._read(contents)
   1307 
   1308     def _read(self, contents: list):

~/.local/software/miniforge3/envs/aiida/lib/python3.9/site-packages/pymatgen/io/lobster/outputs.py in _read(self, contents)
   1341                 for el in line.split(" "):
   1342                     if el not in [""]:
-> 1343                         overlaps.append(float(el))
   1344                 self.bandoverlapsdict[spin][" ".join(kpoint_array)]["matrix"].append(overlaps)
   1345 

ValueError: could not convert string to float: 'Overlap'
```

**Expected behavior**
It should not fail and we should get `bandoverlapsdict` and `max_deviation` populated with data.
I'll open a PR shortly to address the issue. 

**Desktop (please complete the following information):**
 - OS: Mac,Linux
 - Version: 2020.0.13
 - Lobster: v4.0.0 and v4.1.0

### PR DESCRIPTION
**Pull request by pzarabadip**
## Summary

* Fix #2236 

## Additional dependencies introduced (if any)
None. 

## Checklist

Work-in-progress pull requests are encouraged, but please put [WIP]
in the pull request title.

Before a pull request can be merged, the following items must be checked:

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). The easiest way to handle this
      is to run the following in the **correct sequence** on your local machine. Start with running
      [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will automatically reformat
      your code to PEP8 conventions and removes most issues. Then run 
      [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by 
      [flake8](http://flake8.pycqa.org/en/latest/).
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All linting and tests pass.

Note that the CI system will run all the above checks. But it will be much more efficient if you already fix most 
errors prior to submitting the PR. It is highly recommended that you use the pre-commit hook provided in the pymatgen 
repository. Simply `cp pre-commit .git/hooks` and a check will be run prior to allowing commits.

### CODE REVIEW

**Comment by JaGeo** [comment]
Thank you for finding this.

**Comment by mkhorton** [comment]
Thanks @pzarabadip! Ideally there would have a minimal test added with the fix, could you add one?

**Comment by pzarabadip** [comment]
I'll do it @mkhorton. I'm having a little bit of issue running tests on M1 Mac but should be fixed soon. I'll updated the available `BandoverlapsTest` test class to reflect this PR.

**Comment by JaGeo** [comment]
Thank you. (Let me know if I can help.)

**Comment by JaGeo** [comment]
One suggestion from my side:

Adding an additional flag/parameter to the init of this class to still have compatibility with old versions of Lobster (something like old_spin_numbers=False )
There, spin 0 was used (see test files). If it's too much work for you, I am happy to do this later on. 

(Btw, if you have issues with large bandoverlaps, you might need to check your POTCAR version. There are currently issues with the lastest POTCARs in Lobster. You can find more about it in the Lobsterin class.)

**Comment by pzarabadip** [comment]
Thanks a lot @JaGeo, much appreciated. 

Indeed, I've started getting issues with large band overlaps recently. Thanks for pointing out to the solution. 

That's a great suggestion about having the code backward compatible. I could manage to run tests locally. I'll consider backward compatibility. 

Thanks also for your efforts and works for Lobster interface.

**Comment by pzarabadip** [comment]
Hi @JaGeo and @mkhorton 

Re backward compatibility: As @JaGeo suggested, I have added an argument to the class which can be used to switch between different version of `Lobster`. 

I just pushed the latest changes. I have added two new `bandOverlaps.lobster` files and consequently extended the tests in `test_lobster.py` to check the code against these files too. 

Tests were passed locally and I also formatted the code following the guidelines to pass the tests in `lint` workflow. 

Cheers,
Pezhman

**Comment by JaGeo** [comment]
From my side, this looks fine :). Let's see what @mkhorton thinks :).

**Comment by pzarabadip** [comment]
Thanks @JaGeo 

I've been thinking that maybe I should do the following changes before merge:
* Changing the `old_spin_numbers` argument to something like `lobster4` and set it to `True`
* Updating the docstring to explicitly mention something like: Set to `False` if calculations were performed using `Lobster v3.x`

**Comment by JaGeo** [comment]
Sounds good, @pzarabadip

**Comment by JaGeo** [comment]
Or, you could check for Spin 0 in the file. If it's not there, use Spin 1 and Spin 2. If it's there, use Spin 0 and Spin 1. This would avoid all problems, wouldn't it? Sorry that I haven't thought about this before.

**Comment by pzarabadip** [comment]
Brilliant @JaGeo 
This is a much better solution for this problem. I'll update and push the change at some point today.

**Comment by pzarabadip** [comment]
Hi @JaGeo @mkhorton 
The latest commit implements the above suggestion. Hope it would be ready to merge. 
Cheers, 
Pezhman

**Comment by JaGeo** [comment]
Looks good from my side :). Let's see what @mkhorton thinks.

**Comment by mkhorton** [comment]
With regards to Lobster, if you're happy I'm happy @JaGeo ! PR looks great, thank you @pzarabadip. Will merge once the CI checks have completed.

Also, for @pzarabadip, since you're a first time contributor please make sure to fill out [this form](https://forms.gle/JnisFb38QDR8QTFTA) so we can acknowledge you appropriately on our [Development Team page](https://pymatgen.org/team.html).

**Comment by pzarabadip** [comment]
Thanks @mkhorton and @JaGeo 
I also filled in the form.

**Pull request merged**
