### PR TITLE
Plotting of Multicenter COBIs

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

Lobster now also has options to compute multi-center interactions. This leads to a different format of the COBICAR.lobster (e.g., no average COBI is included) and the labels of the bonds are different. At this stage, I can already plot this different format but no tests are included so far. Bond lengths are missing in this output. I might add a computation of those based on the site index and cell number of the interacting atoms.

TODO: 

- [x] Tests for input/output modules
- [x] Tests for from_ and as_dict options of CompleteCohp
- [x] Tests for from_file of CompleteCohp
- [x] Bond length computation from cell information (cannot be done without structure. Will therefore not be done)
- [x] Code simplification (e.g., many if clauses at the moment, probably simplifications are possible)
- [x] check recomputed average cobi in detail
- [x] test spin polarization in detail
- [x] Extend from three to really any multicenter bond

### CODE REVIEW

**Comment by JaGeo** [comment]
Just as a warning that this might sit here for a longer time. I discovered an issue for the multi-center COBI computations in Lobster for the spin-polarized case during the plotting implementation. I will wait until there is a new Lobster version that can generate useful test data.

**Comment by JaGeo** [comment]
Will try to finalize a first implementation soon. I have not forgotten about this pull request.

**Comment by JaGeo** [comment]
Will work on this one here again tonight and hopefully finish it! I still have to resolve a few merge conflict or issues due to changes in the pymatgen code base.

**Comment by JaGeo** [comment]
@janosh if you have some time to review this, this would be awesome. If we don't merge it soon, this will never get merged as tons of merge conflicts show up very fast here in pymatgen and it would be sad as it was a lot of work ...

**Review by janosh — APPROVED** [review]
looks good! i [renamed `multicenter_cobis` to `multi_center_cobis`](https://github.com/materialsproject/pymatgen/pull/2926/commits/5fae0513020d6e15a839a6872b34e8a21c027973) since it was flagged by `cSpell`. let me know if this negatively affects downstream code

**Comment by JaGeo** [comment]
The renaming is fine as it is not used yet anywhere.

**Pull request merged**
