### PR TITLE
Add diffusive thermal conductivity model proposed by Agne et al.

### PR DESCRIPTION
**Pull request by naik-aakash**
Add diffusive thermal conductivity empirical model as proposed by [Agne et al.](https://pubs.rsc.org/en/content/articlelanding/2018/EE/C7EE03256K)

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @janosh , This PR can be reviewed

**Comment by naik-aakash** [comment]
@JaGeo , just tagging you here incase you have comments on this.

**Review by janosh — APPROVED** [review]
Thanks @naik-aakash, lgtm! 👍 

See here for how to add citation decorators to methods/classes implementing published work: [b9515fd](https://github.com/materialsproject/pymatgen/pull/3546/commits/b9515fda549eb881a31a299f42591a7013e62e81)

**Comment by naik-aakash** [comment]
> lgtm! 👍

Thanks! I missed adding it as decorator so did not seem to work. Good to know how to correctly use it 😃

**Pull request merged**
