### PR TITLE
Isym uniform bug fix

### PR DESCRIPTION
**Pull request by fraricci**
As discussed in issue #1453, ISYM has to be set to 1 in case of uniform mode in MPNonSCFSet.
This pull request should fix the problem.

### CODE REVIEW

**Comment by utf** [comment]
Thanks @fraricci! Can we use ISYM = 2 as this should be more efficient. See https://www.vasp.at/wiki/index.php/ISYM

**Comment by shyuep** [comment]
I am fine with this, but please implement tests.

**Comment by fraricci** [comment]
@utf , thanks for the suggestion, that's preferable indeed.
@shyuep test on isym added as well.

**Comment by mkhorton** [comment]
Thanks @fraricci !

**Pull request merged**
