### PR TITLE
[Waiting on tests] add BXSF support

### PR DESCRIPTION
**Pull request by specter119**
## Summary

vasp need to run with previous `CHGCAR`
start with nscf vis updated by
```python
user_incar_settings={
    'SYM': -1,
    'ICHARG': 11,
    'ISMEAR': 0
}
```
and a [general grid](http://www.xcrysden.org/doc/XSF.html#genper) kpoints
for example:
```python
from itertools import product
import numpy as np
from pymatgen.io.vasp.inputs import Kpoints

subdivisions = [9] * 3
kpts = [
    list(i) for i in product(*[np.linspace(0, 1, j) for j in subdivisions])
]
kpoints_xcrysden = Kpoints(
    comment='Kponits for general grids {} x {} x {}.'.format(*subdivisions),
    num_kpts=len(kpts),
    style=Kpoints.supported_modes.Reciprocal,
    kpts=kpts,
    kpts_weights=[1] * len(kpts))
```

but I have no idea how to write a test.

### CODE REVIEW

**Comment by mkhorton** [comment]
Hi @specter119, thanks for your contribution! We will definitely need a test.

An appropriate place for this test would be `pymatgen.io.tests.test_xcrysden`, you can copy the existing `XSFTest` as a template to create a `BXSFTest`. To test your `from_vasprun()` method, you can reference one of the existing vasprun.xml files in the pymatgen test_files folder.

You can test your tests locally using `nose`, or you can just commit your tests to your fork and our CI will run the tests automatically, and leave a check-mark next to your commit if they pass.

**Comment by mkhorton** [comment]
Actually, you will probably have to add an example bxsf_vasprun.xml *and* an example BXSF to the test_files folder.

**Comment by specter119** [comment]
@mkhorton thanks, I will add the test.

**Comment by mkhorton** [comment]
Hi @specter119, any updates on the test files? Would be happy to merge this once tests are present :)

**Comment by mkhorton** [comment]
His @specter119, do you have any example BXSF test files (.bxsf and the vasprun.xmls) to share so we can write a test? Then we can merge your code.

**Comment by janosh** [comment]
Closing as stale (and conflicting with current `pymatgen/io/xcrysden.py`).

**Pull request closed without merging**
