### PR TITLE
Updates to QChem IO and molecule graphs, new fragmenter and bond dissociation analysis modules

### PR DESCRIPTION
**Pull request by samblau**
## Summary

* New molecule fragmenter in analysis/fragmentation.py. Can find all possible fragments of a molecule or only fragments obtained within a specific number of bond breakages, including ring openings. Relies heavily on molecule graphs, networkx, and open babel. Essential to a new fragmentation firetask in Atomate which is used in a new fragmentation workflow to automatically calculate the energies of all fragments necessary to obtain the bond dissociation energies of a molecule. Tests present in analysis/tests/test_fragmenter.py
* Bond dissociation calculator in analysis/bond_dissociation.py. Takes entries of a molecule and its fragments and returns the bond dissociation energies of the molecule. Typically used following the new fragmentation workflow in Atomate. Tests present in analysis/tests/test_bond_dissociation.py
* Updates to analysis/graphs.py in order to facilitate fragmentation as well as additional tests in analysis/tests/test_graphs.py
* Updates to io/qchem/outputs.py including better parsing of PCM calculations, single point calculations, enthalpy and entropy values, and some new machinery around fragmentation. Tests in io/qchem/tests/test_outputs.py updated and sped up by an order of magnitude. 
* Updates to io/qchem/inputs.py and io/qchem/sets.py and their accompanying tests in order to allow the smd_solvent method to be used.

### CODE REVIEW

**Comment by shyuep** [comment]
Thanks. I will merge this for this time. But in future, pls submit PRs in bite-size morsels. Otherwise, it makes review extremely difficult.

**Comment by samblau** [comment]
Will do - sorry about that!

**Comment by shyuep** [comment]
The fragmenter tests are taking way too long. Can you fix them pls? Pls try to get tests down to less than 10s.

[None] 16.61% pymatgen.analysis.tests.test_fragmenter.TestFragmentMolecule.test_babel_PC_with_RO_depth_0_vs_depth_10: 247.0780s
[None] 2.65% pymatgen.command_line.tests.test_bader_caller.BaderAnalysisTest.test_automatic_runner: 39.4394s
[None] 2.56% pymatgen.analysis.tests.test_pourbaix_diagram.PourbaixDiagramTest.test_mpr_pipeline: 38.0186s
[None] 2.38% pymatgen.analysis.tests.test_structure_analyzer.MiscFunctionTest.test_average_coordination_number: 35.3898s
[None] 2.15% test_elastic.DiffFitTest.test_fit: 31.9953s
[None] 2.13% pymatgen.core.tests.test_surface.MillerIndexFinderTests.test_generate_all_slabs: 31.6770s
[None] 1.98% pymatgen.ext.tests.test_matproj.MPResterTest.test_get_pourbaix_entries: 29.4893s
[None] 1.80% pymatgen.analysis.defects.tests.test_generators.InterstitialGeneratorTest.test_int_gen: 26.8336s
[None] 1.60% pymatgen.command_line.tests.test_bader_caller.BaderAnalysisTest.test_from_path: 23.8605s
[None] 1.37% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_complexity_factor: 20.4286s
[None] 1.32% pymatgen.analysis.tests.test_fragmenter.TestFragmentMolecule.test_edges_given_TFSI: 19.6061s
[None] 1.30% pymatgen.analysis.tests.test_fragmenter.TestFragmentMolecule.test_babel_TFSI: 19.3955s
[None] 1.30% test_elastic.ElasticTensorExpansionTest.test_get_yield_stress: 19.3319s
[None] 1.20% pymatgen.command_line.tests.test_bader_caller.BaderAnalysisTest.test_atom_parsing: 17.8511s
[None] 1.14% pymatgen.analysis.tests.test_surface_analysis.WorkfunctionAnalyzerTest.test_attributes: 17.0007s
[None] 1.11% pymatgen.analysis.tests.test_fragmenter.TestFragmentMolecule.test_PC_depth_0_vs_depth_10: 16.5224s
[None] 1.06% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_seebeck_eff_mass: 15.7539s
[None] 1.02% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_average_eff_mass: 15.2203s
[None] 1.02% pymatgen.core.tests.test_surface.SlabTest.test_symmetrization: 15.1031s
[None] 1.01% pymatgen.io.vasp.tests.test_outputs.OutcarTest.test_stopped: 14.9695s
[None] 0.97% pymatgen.analysis.tests.test_path_finder.PathFinderTest.test_image_num: 14.4032s
[None] 0.96% pymatgen.analysis.tests.test_graphs.MoleculeGraphTest.test_build_unique_fragments: 14.3393s
[None] 0.96% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_power_factor: 14.2802s
[None] 0.91% pymatgen.io.qchem.tests.test_outputs.TestQCOutput.test_all: 13.5214s
[None] 0.90% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_seebeck: 13.3679s
[None] 0.88% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_carrier_concentration: 13.1203s
[None] 0.87% pymatgen.symmetry.tests.test_kpaths.HighSymmKpathTest.test_kpath_generation: 12.9847s
[None] 0.83% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_conductivity: 12.3571s
[None] 0.81% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_complete_dos: 12.0780s
[None] 0.80% pymatgen.electronic_structure.tests.test_boltztrap.BoltztrapAnalyzerTest.test_get_hall_carrier_concentration: 11.9374s

**Comment by samblau** [comment]
Hi Shyue - that specific test is slow because it involves many calls to OpenBabel's UFF energy minimization tool that I depend on for ring openings. It also calls molecule graph's isomorphic_to many, many times, which is quite computationally intensive. However, this specific test revealed multiple bugs during development, which is why I decided to keep it despite it being so slow. @mkhorton and I were talking about it just yesterday and trying to think of a smaller test system that would still be comprehensive, but fundamentally, it needs to be an asymmetric ring with fragments from both normal bond breaking and ring bond breaking that are isomorphic. Thus far, I've been unable to think up a molecule smaller than our 13 atom test case that would still test everything covered at present.

**Comment by samblau** [comment]
I could certainly turn off the other depth_0 vs depth_10 test which I only added as a mediocre replacement for the extremely long test when babel is not present, or at least turn it off when babel is present. I could also get rid of one or both of the TFSI tests that look to be just outside of the top 10 shown above given that they likely aren't testing anything that the very long test isn't.

**Pull request merged**
