### PR TITLE
Suggested fix for the parsing issues related with the predictor-corrector data in VASP output

### PR DESCRIPTION
**Pull request by aykol**
## Summary

This is a suggested solution for the Issue #325, mostly for code review purposes. I can work on a new pull request based on the comments on this one.

* Predictor corrector data is now correctly parsed.
* These 3 sets of 3 xN parameters are stored properly for each site as a site_property.
* inputs.Poscar is modified to now generate the the correct string for POSCAR's with predictor_corrector information.
* A generic "structure_properties" attribute is added to Structure to store any arbitrary structure information that is not site-specific.
* Using that, predictor corrector preamble (key, potim, thermostat params...) is stored as a structure_property
* Structure and IStructure were modified to accommodate "structure_properties" (e.g. addition of properties, structure generation, copying etc.)
* Changes are tested, no errors generated.

### CODE REVIEW

**Comment by shyuep** [comment]
Thanks. I think the new parsing is great. But I think there is really no reason to add a structure_property field. Structure is mutable by default. So you can simply set any new properties as Structure.thermostat = X for example. Also, I think things like thermostat etc. are not really Structure related but rather POSCAR related. So they should actually be stored in POSCAR itself rather than Structure?

**Comment by aykol** [comment]
Thanks for the comments. I will isolate the parsing and submit a new pull request. 

For the preamble storage (key, time-step and thermostat parameters), I agree that the proper place would be Poscar since they are specific to it. But the reason why I suggested storing them in Structure was, because they are tied with the predictor corrector coordinates and derivatives (e.g. those are valid for only the time-step given in the preamble) so I wasn't sure about separating them. Because in that sense, having them together in Structure ensures that when a Structure parsed from a CONTCAR is stored, it is self-sufficient to generate a new Poscar in future, without needing access to the CONTCAR it was generated from (or a stored Poscar object). I hope my point is clear. What do you think? Would you prefer the "Structure.thermostat" style or storing in the Poscar?

**Comment by shyuep** [comment]
Thanks. I agree it is strange that the predictor_corrector are stored in site properties. There is actually a good reason for that. When the properties are related to an overall structure, there is no issue with storing them in the Poscar itself. When there are properties that relates to sites, the problem is that people may sometimes manipulate the structure e.g., swapping atomic ordering etc., after parsing a Poscar and then regenerating that Poscar. Those properties have to be linked to each site so that any ordering works. 

In general, core objects like Site and Structure should be kept free from DFT code specific things. I don't see the site_properties as a major deviation because site_properties was there to begin with. Things like Poscar related parameters should site within the Poscar object itself.

**Comment by aykol** [comment]
Ok, I got it. I'll put the those parameters in Poscar. Thanks.

**Pull request closed without merging**
