### PR TITLE
DO NOT MERGE: Request for review of Eqn of State Thermal

### PR DESCRIPTION
**Pull request by ctoher**
Pull request for review of equation of state thermal properties code for Materials Project. 

FAO: Patrick Huck, Donny Winston, Joey Montoya, Kristin Persson

Code is in pymatgen/analysis/eqn_of_state_thermal 

Branch eos_thermal_pmg4 is implemented in pytmatgen 4

Fits E(V) data to equations of state and Debye-Grueneisen model to obtain thermal properties.

### CODE REVIEW

**Comment by dwinston** [comment]
at-mentioning to track discussion: @tschaume @montoyjh @kristinpersson

**Comment by shyuep** [comment]
The hegemon does not need to be involved in this discussion right?

**Comment by shyuep** [comment]
It is impossible to code review something that has 758 changed files. Pls copy your repo, refork the code, and then make only the changes that are on top of the existing pymatgen.

**Comment by dwinston** [comment]
Duplicate of #481

**Pull request closed without merging**
