### PR TITLE
Fix Lobsterenv Bug

### PR DESCRIPTION
**Pull request by naik-aakash**
# Bug

The charges read from file are not assigned

# Fix

Fix the erroneous if else condition introduced during #3624 

# Todo

- [x] Add test

### CODE REVIEW

**Comment by janosh** [comment]
Thanks! Can you add a test to catch future mistakes?

**Comment by naik-aakash** [comment]
Hi @janosh , can a new release of Pymatgen be made? As this is bug breaks our LobsterPy package https://github.com/JaGeo/LobsterPy/pull/232 

Sorry for the inconvenience.

**Review by janosh — APPROVED** [review]

**Comment by janosh** [comment]
> Hi @janosh , can a new release of Pymatgen be made please? 

we just had one today so i'd prefer to accumulate a few more changes before the next release

**Comment by JaGeo** [comment]
@janosh , this currently prevents our on-going JOSS review for LobsterPy. We could use the latest master branch from pymatgen for the release but it's not exactly best practice.

**Comment by janosh** [comment]
i see. let's also get in https://github.com/materialsproject/pymatgen/pull/3593 (awaiting OP) and then we can release

**Comment by JaGeo** [comment]
@janosh Thanks!

**Comment by janosh** [comment]
[v2024.2.23](https://github.com/materialsproject/pymatgen/releases/tag/v2024.2.23) should be on PyPI in ~1h.

**Comment by naik-aakash** [comment]
> [v2024.2.23](https://github.com/materialsproject/pymatgen/releases/tag/v2024.2.23) should be on PyPI in ~1h.

Thanks 😄

**Pull request merged**
