### PR TITLE
One attempt to fix ChemEnv error in tests

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

As discussed in https://github.com/materialsproject/pymatgen/issues/2788, one way of fixing the ChemEnv error in the tests would be converting the PeriodicNeighbor object in a PeriodicSite object. I have implemented this. It might however affect the execution speed.

If someone else, manages to fix the as_dict from PeriodicNeighbor in a cheaper way, I would prefer this, of course.

### CODE REVIEW

**Comment by JaGeo** [comment]
Linting still fails but tests are running through. 
Please let me know what you think and if you have any better/faster ideas (@shyuep , @janosh). Both species and coordinates  are influenced when using from_dict and as_dict from PeriodicNeighbors.

**Comment by janosh** [comment]
This doesn't look like much a slowdown anyway.

**Comment by janosh** [comment]
Thanks @JaGeo. Good to have green CI again. Like you said, makes contributing much easier. I'll close #2788 now.

**Comment by JaGeo** [comment]
Just adding this here: https://github.com/materialsproject/pymatgen/blob/c1a7f5d7635f85e7bc490658d52b70867ed24614/pymatgen/core/structure.py#L158 
This name is a bit unfortunate. If as_dict as inherited from PeriodicSites is then used, "coords" (typically fractional coordinates  but now cartesian ones due to the overloading) is used and this might lead to the other problems with from_dict and as_dict for PeriodicNeighbors (besides the dict issue for the species).

**Pull request merged**
