### PR TITLE
flake8 add per-file-ignores = __init__.py: F401

### LINKED ISSUE #2359: Fix yaml.safe_load() deprecation warnings
My `pytest` and `fireworks`  logs are full of `yaml.safe_load()` deprecation warnings originating in `pymatgen` and `monty`.

```py
site-packages/monty/serialization.py:85: PendingDeprecationWarning: 
  load will be removed, use
  
    yaml=YAML(typ='unsafe', pure=True)
    yaml.load(...)
  
  instead
    return yaml.load(fp, *args, **kwargs)

site-packages/pymatgen/analysis/local_env.py:51: PendingDeprecationWarning: 
  safe_load will be removed, use
  
    yaml=YAML(typ='safe', pure=True)
    yaml.load(...)
  
  instead
    default_op_params = yaml.safe_load(f)

site-packages/pymatgen/analysis/local_env.py:54: PendingDeprecationWarning: 
  safe_load will be removed, use
  
    yaml=YAML(typ='safe', pure=True)
    yaml.load(...)
  
  instead
    cn_opt_params = yaml.safe_load(f)
```

Would be nice to fix those to have readable logs again. Should be doable by turning this

https://github.com/materialsproject/pymatgen/blob/905fa8592423f51784b9e83e02c53bb0c6ea0aa3/pymatgen/core/__init__.py#L11-L17

into this

```py
try:
    from ruamel.yaml import YAML

    yaml = YAML(typ="safe", pure=True)
except ImportError:
    try:
        import ruamel_yaml as yaml  # type: ignore  # noqa
    except ImportError:
        import yaml  # type: ignore # noqa
```

and then replace all `yaml.safe_load()` with `yaml.load()`. What do you say?

### PR DESCRIPTION
**Pull request by janosh**
~Closes #2359.~ Closes nothing.

#2359 was closed in d7cfd8a4a6a00fce1860f1a4d2ed0a3830520dbc.

### CODE REVIEW

**Comment by janosh** [comment]
This has become quite the opinionated PR with more monkey patching than expected.

Since the `safe_load` method will be removed soon, something like the mess I'm creating here will become necessary unless `pymatgen` decides to be more opinionated about the YAML parser it requires users to have. I.e. by saying everyone must install `ruamel.yaml` you'd have a more dependable interface.

**Comment by shyuep** [comment]
Let me do this. ruamel is already a requirement in pymatgen anyway.

**Comment by shyuep** [comment]
I just pushed a fix. This PR should not be necessary unless you see I missed something.

**Comment by janosh** [comment]
@shyuep Cool thanks! Fix looks good. I left the

```
per-file-ignores =
  # F401: imported but unused
  __init__.py: F401
```

part of this PR cause I think that's an improvement. What do you think?

**Comment by shyuep** [comment]
Ok!

**Pull request merged**
