### PR TITLE
Type hints

### PR DESCRIPTION
**Pull request by janosh**
Add some more type hints in `electronic_structure/plotter.py`, `bandstructure.py`, `io/vasp/outputs.py`.

### CODE REVIEW

**Comment by arosen93** [comment]
@janosh -- nice update to the typehints. I have a general question based on this. For something like `kwarg = None`, which is better programming practice: `kwarg: int = None` or `kwarg: int | None = None`?

**Comment by janosh** [comment]
@arosen93 Thanks! `kwarg: int | None = None` is strictly speaking more correct but unless you set `mypy`'s [`--no-implicit-optional`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-optional) flag (which I usually don't) then the two are equivalent.

**Comment by arosen93** [comment]
Good to know, thanks! :)

**Comment by mkhorton** [comment]
Thanks!

**Pull request merged**
