### PR TITLE
 Adaption to anticipated use of x_diff_weight 

### PR DESCRIPTION
**Pull request by nisse3000**

### CODE REVIEW

**Comment by shyuep** [comment]
If you removed bugs, that means that these bugs were not tested originally. Pls include tests to show that the bugs are removed.

**Comment by nisse3000** [comment]
@shyuep, the class is from @computron. I'm currently testing in-depth and finding these bugs. Will be added to unit tests.

**Comment by shyuep** [comment]
Ok. But pls submit PR only when you are more or less ready.

**Comment by nisse3000** [comment]
Sure. But "Removed 2 bugs" and the newer "shortcomings" are two separate things. Didn't anticipate more clean up, when I issued the first PR.

**Pull request closed without merging**
