### PR TITLE
Q-Chem 6 + Misc Updates

### PR DESCRIPTION
**Pull request by samblau**
## Summary

- Major changes to Q-Chem IO (inputs.py and outputs.py) to accommodate differences and new features in version 6+
- Additional parsing capabilities for HOMO/LUMO, dipoles, NBO info (hyperbonds and 3C bonds) in outputs.py
- Utility for processing a parsed binary Hessian scratch file
- Overdue updates to default values in sets.py and new defaults associated with differences and new features in Q-Chem 6+

### CODE REVIEW

**Comment by samblau** [comment]
Alright y'all, this is a big one. @espottesmith, @rkingsbury, @mkhorton, any chance some or all of you are interested in reviewing? Thank you!

**Comment by samblau** [comment]
Need to fix test_sets.py given the change from assertEqual -> assert that has been implemented in the midst of this large PR

**Comment by mkhorton** [comment]
Thanks @samblau, this looks great!

**Comment by rkingsbury** [comment]
Thanks @samblau ! Sorry I didn't get a chance to review before now but all looks good to me.

**Comment by samblau** [comment]
@mkhorton Thanks for merging! Could you or @shyuep please release a new version of pymatgen when convenient? Thank you!

**Comment by shyuep** [comment]
@samblau 2023.1.30 was released today.

**Pull request merged**
