### PR TITLE
Sortation of FEFF input

### PR DESCRIPTION
**Pull request by Ameyanagi**
## Summary 

- This PR fixes the sortation of the FEFF IO module to create ATOMS input.
- Main change is to sort the distance by `float` instead of `string`. This will prevent the sorting issue with atom distance above 10 angstroms. 
- For example, an atom with a distance of "10 angstroms" was listed before an atom with a distance of "2 angstroms" previously, but it is fixed to be listed in numerical order.

## Checklist

Work-in-progress pull requests are encouraged, but please put [WIP]
in the pull request title.

Before a pull request can be merged, the following items must be checked:

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). The easiest way to handle this
      is to run the following in the **correct sequence*- on your local machine. Start with running
      [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will automatically reformat
      your code to PEP8 conventions and removes most issues. Then run
      [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by
      [flake8](http://flake8.pycqa.org/en/latest/).
- [x] Doc strings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly*- encouraged. Run [mypy](https://github.com/python/mypy) to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All linting and tests pass.

Note that the CI system will run all the above checks. But it will be much more efficient if you already fix most
errors prior to submitting the PR. It is highly recommended that you use the `pre-commit` hooks specified in the pymatgen
repo. Simply `pip install -U pre-commit && pre-commit install` and linters will run prior to every commit.

### CODE REVIEW

**Comment by janosh** [comment]
Thanks for the nice summary! Could you add a test to `pymatgen/io/feff/tests/test_inputs.py` that verifies the new behavior, i.e. that fails with the old code and passes with your change?

**Comment by Ameyanagi** [comment]
Thank you for the comment, I modified test_inputs.py to test the new behavior. I changed the `test_files/ATOMS` files as well because they did not contain atoms with a distance above 10 Å. This also changed the chemical formula, but the test will pass. Let me know if I need to make separate ATOMS files just for this test.

The old code will fail as following:
E       AssertionError:
E       Not equal to tolerance rtol=1e-05, atol=0
E
E       Mismatched elements: 584 / 585 (99.8%)
E       Max absolute difference: 8.08273
E       Max relative difference: 4.03232605
E        x: array([ 0.      , 10.071798, 10.071798, 10.071798, 10.09169 , 10.09169 ,
E              10.09169 , 10.09169 , 10.09169 , 10.09169 , 10.093188, 10.093188,
E              10.093188, 10.093188, 10.093188, 10.093188, 10.165263, 10.165263,...
E        y: array([ 0.     ,  2.00142,  2.00142,  2.00142,  2.00896,  3.24426,
E               3.24426,  3.24426,  3.24427,  3.24427,  3.24427,  3.24525,
E               3.29708,  3.29708,  3.29708,  3.29708,  3.29708,  3.29708,...

**Comment by janosh** [comment]
@Ameyanagi Btw if you'd like to be added to the pymatgen dev team, please submit [this form](https://docs.google.com/forms/d/e/1FAIpQLSccv6R3vXKQdl_m2aMbhyepK18DEjDBWXywbpuViGH6Xn_ZLg/viewform). You'll be listed here https://pymatgen.org/team.

**Comment by Ameyanagi** [comment]
@janosh Thank you very much!! I will submit the form.

**Pull request merged**
