### PR TITLE
Modify FHI-aims inputs to not use species string

### PR DESCRIPTION
**Pull request by tpurcell90**
FHI-aims does not read spin from the species and that causes issues with magnetic calculations

## Summary

Major changes:

- fix 1: Don't use species_string for FHI-aims

## Checklist

- [x] Google format doc strings added. Check with `ruff`.
- [x] Type annotations included. Check with `mypy`.
- [x] Tests added for new features/fixes.
- [x] If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/lattice.py#L1168-L1172))

### CODE REVIEW

**Comment by ansobolev** [comment]
@tpurcell90 This seems to work for the defect workflow, thanks; however, as aims accepts anything in the `species` line (it's just a label), I would rather use something like `site.label` for site description in `geometry.in`. This will allow more precise accounting for species defaults in heterogeneous calculations (something like adsorbate on the surface). But that's for sure open for discussion and not the blocking issue.

**Comment by tpurcell90** [comment]
ready for review

**Comment by shyuep** [comment]
Thanks.

**Comment by tpurcell90** [comment]
would it be possible to make a release with this soon? We need this fix for atomate2

**Pull request merged**
