### PR TITLE
Fix descriptions in external tools

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

Descriptions of the external tools got mixed up. Switched the LobsterPy and the QuAcc description.

### CODE REVIEW

**Comment by JaGeo** [comment]
Not exactly sure how the linter is now failing in an nmr module. In any case, I only changed the documentation.

**Comment by mkhorton** [comment]
Thanks @JaGeo! No idea how that got mixed up

**Comment by janosh** [comment]
Oops, that was my mistake. 😓 

Already mixed up in the [original commit](https://github.com/JaGeo/pymatgen/commit/078479d67967ef6af4cd22edb8362ffa635d9e23#diff-de00fc0ed9e189502523ecc5869b9ecd0497e21ea9e227098662a063dde0576fR31).

**Comment by JaGeo** [comment]
Don't worry 😅. It happens. 🙂 You fixed so many other and much more servere mistakes in the code base!

**Pull request merged**
