### PR TITLE
move convert_cart_to_latt to method get_lattice_coords of Lattice class

### PR DESCRIPTION
**Pull request by blondegeek**
See discussion on #1375.

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @blondegeek ! Haven't merged yet because I'm just mulling over that `get_lattice_coords` method name, I'm not sure if that might cause confusion for people? I'm not sure what a better name for it might be though. The inverse method might also be helpful (get lattice coords from cart coords).

**Comment by mkhorton** [comment]
Actually, for the method name, instead of renaming it maybe just adding an illustrative example to the docstring would help, something like "for example, this may be used to calculate a polarization vector..."

**Comment by shyuep** [comment]
I think the method should be renamed. Lattice coords is far too confusing.

**Comment by mkhorton** [comment]
I think that name's reasonable, I can't think of a better one in any case. As long as it avoids confusion with eg `Lattice.get_cartesian_coords` I think that's the main thing.

**Comment by blondegeek** [comment]
Pending integration and code quality checks...done!

**Comment by mkhorton** [comment]
Thanks!

**Pull request merged**
