### PR TITLE
chore: add get_string alias for Poscar

### PR DESCRIPTION
**Pull request by timurbazhirov**
## Summary

Minor changes:

- add `get_string` alias for `get_str` function in Poscar class for convenience/compatibility purposes with earlier implementation(s)

Major changes:

- none

## Checklist

```bash
(.venv) ➜  pymatgen git:(chore/add-poscar-get-string-alias) pre-commit run --all-files                                           
ruff.....................................................................Passed
ruff-format..............................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
mypy.....................................................................Passed
codespell................................................................Passed
cython-lint..............................................................Passed
double-quote Cython strings..............................................Passed
blacken-docs.............................................................Passed
markdownlint.............................................................Passed
nbstripout...............................................................Passed
```

and

```bash
(.venv) ➜  pymatgen git:(chore/add-poscar-get-string-alias) pip list                  
Package            Version
------------------ -----------
beautifulsoup4     4.12.2
certifi            2024.2.2
cfgv               3.4.0
charset-normalizer 3.3.2
contourpy          1.2.1
cycler             0.12.1
Cython             3.0.2
distlib            0.3.8
filelock           3.13.4
fonttools          4.51.0
future             1.0.0
identify           2.5.35
idna               3.7
joblib             1.3.2
kiwisolver         1.4.5
latexcodec         3.0.0
matplotlib         3.8.0
monty              2024.2.26
mpmath             1.3.0
networkx           3.1
nodeenv            1.8.0
numpy              1.26.0
packaging          24.0
palettable         3.3.3
pandas             2.1.1
pillow             10.3.0
pip                24.0
platformdirs       4.2.0
plotly             5.17.0
pre-commit         3.7.0
pybtex             0.24.0
pyparsing          3.1.2
python-dateutil    2.9.0.post0
pytz               2024.1
PyYAML             6.0.1
requests           2.31.0
ruamel.yaml        0.18.6
ruamel.yaml.clib   0.2.8
scipy              1.11.3
setuptools         69.2.0
six                1.16.0
soupsieve          2.5
spglib             2.1.0
sympy              1.12
tabulate           0.9.0
tenacity           8.2.3
tqdm               4.66.2
tzdata             2024.1
uncertainties      3.1.7
urllib3            2.2.1
virtualenv         20.25.1
wheel              0.43.0
```

## Summary by CodeRabbit

- **New Features**
	- Introduced a new method alias `get_string` for enhanced usability in accessing string representations.

### CODE REVIEW

**Comment by shyuep** [comment]
@janosh Can we please for the love of god keep backward compatibility when it is trivial to do so? There is no reason for this backward incompatibility to exist.

**Comment by janosh** [comment]
@timurbazhirov apologies for the trouble. are you using another package that depends on `pymatgen` which didn't update to `get_str`?

@shyuep you green-lighted this change last year including the deprecation period.

looks like [monty@v2024.4.16](https://github.com/materialsvirtuallab/monty/releases/tag/v2024.4.16) didn't keep backwards compatibility as deserialization is failing across the code base.

**Comment by shyuep** [comment]
@janosh I green lighted the change for sure. But I was under the impression the deprecation period is longer? The Monty issue has nothing to do with deprecation but a bug introduced that were not caught by existing tests. Those I accept.

**Comment by janosh** [comment]
> But I was under the impression the deprecation period is longer?

sorry about that, i probably could have been clearer.

**Comment by shyuep** [comment]
Incidentally, keep your comments related to the existing bug report and package. Arguing by using equivalence on other packages is petty. If you have a problem with a bug on Monty, feel free to comment over at the Monty Issues.

**Comment by janosh** [comment]
re this PR: adding back `get_string` class by class is probably not ideal. better to ask why there's no migration path for @timurbazhirov

**Comment by timurbazhirov** [comment]
Thank you. This seemed like a benign workaround to avoid having to handle the function signature(s) when using py3.8-compatible earlier version(s) like in https://github.com/Exabyte-io/made/blob/main/src/py/mat3ra/made/tools/convert.py#L121. For production workloads, it's often good to have compatibility with earlier versions for longer. 

Not sure what you mean by:

> adding back get_string class by class is probably not ideal

but either way, feel free to close this PR if you don't like it.

BTW - are test failures related to the change in this PR, or caused by something else?

**Comment by JaGeo** [comment]
> BTW - are test failures related to the change in this PR, or caused by something else?

No, they aren't. An issue with a dependency. 😅 (I also asked about this earlier today)

**Comment by shyuep** [comment]
I merged. Thanks for reporting this. My view is that this is a trivial thing to support and there is no reason why we can't keep the `get_string = get_str` line. I am a practical person. Code cleanliness exists to support functionality, not to hamper it.

**Comment by shyuep** [comment]
I don't quite understand why the test suite is installing monty 2024.4.*. The pinned dependency says monty==2024.2.26

**Comment by shyuep** [comment]
@Andrew-S-Rosen Can you investigate the serialization issue? Seems related to the latest msonable changes.

**Comment by Andrew-S-Rosen** [comment]
@shyuep: I'm unavailable until the weekend so can't look at it until then, unfortunately (I'm just posting from phone).

I can't see the test fail from GitHub Mobile but my guess is it's linked to https://github.com/materialsvirtuallab/monty/pull/654.

**Comment by Andrew-S-Rosen** [comment]
Ah, I see the fail now. @matthewcarbone: at first glance, this looks similar to https://github.com/materialsvirtuallab/monty/issues/659 (just as a heads up!).

**Comment by matthewcarbone** [comment]
@Andrew-S-Rosen this one can't be my fault right? monty from February is well before I broke MSONable 😁

Happy to help look into this if you'd like though!

**Comment by shyuep** [comment]
@matthewcarbone There are two fails here:
1. The CI is installing 2024.4.x monty, which includes your changes. This is not what the CI is supposed to do. Not sure what is happening. I have no idea what `micromamba` is. This needs to be fixed by @janosh .
2. Monty 2024.4.x  itself has a bug which broke serialization. This needs to be fixed asap.

**Comment by shyuep** [comment]
@matthewcarbone I didn't know the bug existed when 2024.4.* was released. I will roll back the changes for now.

**Comment by matthewcarbone** [comment]
@shyuep @janosh the issue with the wrong install version of monty might be in `setup.py`.

https://github.com/materialsproject/pymatgen/blob/7f96ef2c6c4e753a5dafbac4fde6f5a136c0aec0/setup.py#L32

Looks like the version there is different than that pinned in `requirements.txt`. Even if this isn't the issue the `setup.py` file should probably read from `requirements.txt` so there's only one source of truth. Thoughts?

Btw a new version of monty which rolls back my bug was just released and should fix this issue. Apologies!

**Comment by matthewcarbone** [comment]
I have no idea what uv is though 😁

**Comment by JaGeo** [comment]
> I have no idea what uv is though 😁

Just a software to make pip install faster. (https://pypi.org/project/uv/)

**Pull request merged**
