### PR TITLE
Optionnal possibility to specify that the saddle_point in the NEB sho…

### PR DESCRIPTION
**Pull request by davidwaroquiers**
## Summary

* Possibility to setup the spline in the NEB analysis so that the slope is zero for the saddle point (works only for new versions of scipy).

### CODE REVIEW

**Comment by shyuep** [comment]
I will merge but I will make some edits.

**Comment by shyuep** [comment]
I pushed my changes. Can I request that we avoid introducing too much craft and code that duplicates. When you have the exact same call to CubicSpline, that is a problem.

Also, when can we remove the old scipy spline? Pymatgen already pins the latest scipy as a requirement. Do we need that?

**Comment by shyuep** [comment]
also, pls implement a unit test for the spline_options code. Right now, I have no way of knowning whether my changes broke anything.

**Comment by davidwaroquiers** [comment]
Hi Shyue,


Ok, I'll implement a unit test tomorrow (already late tonight).

On the other hand, I will re-add the "setup_spline" method if you don't
mind, because we dont store the spline itself in the as_dict(), and we
might want to use a given spline_options in some cases and another one in
some others. In this way, reading back the NEBAnalysis using from_dict()
you can setup the spline option you want.


David

**Pull request merged**
