### PR TITLE
Orbital-resolved icohplist

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

@janosh, I have added support for orbital-resolved icohplists and included tests.

(@naik-aakash , FYI. I think it should be very useful for some of our currenct projects)

### CODE REVIEW

**Comment by janosh** [comment]
@JaGeo We're trying to move away from type hint comments:

```diff
- list_orb_icohp = [] # type: List[dict]
+ list_orb_icohp: list[dict] = []
```

**Comment by JaGeo** [comment]
Thanks! Will change this!

**Comment by JaGeo** [comment]
Locally, mypy is finally passing...

**Comment by JaGeo** [comment]
Seems like most of the tests are passing now.

**Comment by JaGeo** [comment]
MacOS tests are still queued. I will contiue on another day if something fails.

**Comment by JaGeo** [comment]
@janosh Finally, all tests are passing 😃

**Comment by janosh** [comment]
Thanks @JaGeo! 👍

**Pull request merged**
