### PR TITLE
Refactor `interface_reactions` module, add support for Plotly

### PR DESCRIPTION
**Pull request by mattmcdermott**
## Summary

* Add: support for Plotly: calling `plot()` now provides a `backend` option for choosing matplotlib or Plotly.
* Add:`GrandPotentialInterfacialReactivity` class to separate code based on the use of grand potential phase diagrams (this greatly decreases the complexity of the `__init__` args) and is a more inherited approach in general
* Add: `get_dataframe()` method for plotting possible reactions in a Pandas dataframe. Users would typically have to write/copy boilerplate code to do this each time
* Fix: Better matplotlib plotting, included annotations 
* Fix: Cleaner, more readable code

## Checklist

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). The easiest way to handle this
      is to run the following in the **correct sequence** on your local machine. Start with running
      [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will automatically reformat
      your code to PEP8 conventions and removes most issues. Then run 
      [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by 
      [flake8](http://flake8.pycqa.org/en/latest/).
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All linting and tests pass.

### CODE REVIEW

**Comment by mattmcdermott** [comment]
@mkhorton My plan is to have this PR done by Wed, September 8, based on the previous timeline goal we set

**Comment by mkhorton** [comment]
Fantastic, thank you for the update @mattmcdermott !

**Comment by mattmcdermott** [comment]
Should be pretty much done; tests work on my laptop. Not sure if things are broken on Github...

**Comment by mkhorton** [comment]
Thanks @mattmcdermott! I think that method is also available on `Composition` etc. directly (via the `Stringify` mixin), just an fyi.

**Comment by mattmcdermott** [comment]
> Thanks @mattmcdermott! I think that method is also available on `Composition` etc. directly (via the `Stringify` mixin), just an fyi.

Ah true. The only downside is for compositions like `Composition("FeO2")`, it automatically puts "1" as a subscript:
e.g.,`Fe_1O_2`

**Comment by mkhorton** [comment]
Ah, I guess it acts on the Composition directly rather than formula, fair enough.

**Comment by mkhorton** [comment]
Merged. Thanks again @mattmcdermott, this is great!

**Pull request merged**
