### PR TITLE
Fix Lobsterin()._get_potcar_symbols()

### LINKED ISSUE #2363: TypeError in _get_potcar_symbols()
`class Lobsterin()._get_potcar_symbols()` causes [CI errors in `atomate`](https://github.com/hackingmaterials/atomate/runs/4871532128?check_suite_focus=true#step:8:115)

https://github.com/materialsproject/pymatgen/blob/fd553a8e80935d77df285fed1a14d7bf63669c14/pymatgen/io/lobster/inputs.py#L612-L633

```sh
        with zopen(POTCAR_input, "r") as f:
            data = f.read()
>       if "SHA256" in data or "COPYR" in data:
E       TypeError: a bytes-like object is required, not 'str'
```

Triggered by PR: https://github.com/hackingmaterials/atomate/pull/738

### PR DESCRIPTION
**Pull request by janosh**
Closes #2363.

### CODE REVIEW

**Comment by janosh** [comment]
Can add a test for this if anyone wants one.

**Comment by shyuep** [comment]
Thanks.

**Comment by janosh** [comment]
Thanks for merging. When's the next release due? This fix blocks https://github.com/hackingmaterials/atomate/pull/738 which makes `atomate` compatible with latest `pymatgen`.

**Comment by JaGeo** [comment]
Would like to point out this pull request related to atomate as well: https://github.com/materialsproject/pymatgen/pull/2358

**Comment by janosh** [comment]
@JaGeo Cool! I'd seen the CI error but not @arosen93's PR yet. Thought I'd have to dig into that one too. :)

Yes, we'll definitely have to wait for #2358 before releasing `atomate`.

**Comment by arosen93** [comment]
@JaGeo, should be done shortly! A user reported an issue when using the `LobsterSet` (also with `StaticFw`) due to a change I merged a little while back (https://github.com/materialsproject/pymatgen/commit/9cfef441c16fd4c68290b80bb0383d52a0a8c0fe#r64164646). I'll admit, I'm not exactly sure of the cause after digging into it, but I'm just reverting my change for now.

**Pull request merged**
