### PR TITLE
Fix some Kpoints generated using wrong mesh types

### PR DESCRIPTION
**Pull request by matthewkuner**
Addresses https://github.com/materialsproject/pymatgen/issues/3220. Also adds a lot of tests to (hopefully) make sure nothing like this happens again.

### CODE REVIEW

**Comment by matthewkuner** [comment]
@janosh seems like the tests that are failing are unrelated? Hard for me to tell

**Comment by janosh** [comment]
Tests were fine on `master`. Looks like something you changed turned `magmons` from `tuple` to `list`. I pushed a fix.

```py
self._cell
>>> (((...), (...), (...)), ((...),), (1,), ([...],))
```

https://github.com/materialsproject/pymatgen/blob/c335e43b5f1454786dcbfcdf20b47fd677132665/pymatgen/symmetry/analyzer.py#L103-L118

**Comment by matthewkuner** [comment]
@janosh This could possibly be discovering some other issue with the magmoms, because I don't think a single line from my new code has anything to do with magmoms? ¯\_(ツ)_/¯

**Comment by janosh** [comment]
Not sure either why this is surfacing now. I think this is good to go except for one thing. Do we need to add 3 new POSCAR files? How about you pick some of 31 that we already have:

```py
from collections import defaultdict
from glob import glob

from pymatgen.io.vasp.inputs import Poscar
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.util.testing import TEST_FILES_DIR

# glob all POSCARs in test files dir and count their crystal types
crys_sys_counts = defaultdict(int)
test_potcars = [*glob(f"{TEST_FILES_DIR}/*POSCAR*"), *glob(f"{TEST_FILES_DIR}/**/*POSCAR*")]
print(f"{len(test_potcars)=}")

for filepath in test_potcars:
    try:
        poscar = Poscar.from_file(filepath)
        crys_sys = SpacegroupAnalyzer(poscar.structure).get_crystal_system()
        crys_sys_counts[crys_sys] += 1
    except Exception:
        pass
```

`crys_sys_counts = {'cubic': 15, 'trigonal': 3, 'hexagonal': 3, 'monoclinic': 3, 'orthorhombic': 2, 'triclinic': 2}`

**Pull request merged**
