### PR TITLE
method to estimate NBANDS + tests

### PR DESCRIPTION
**Pull request by rwoodsrobinson**
## Summary

* created method to estimate NBANDS for VASP input set
* simplified `nelect` property
* added tests

## Checklist

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). 
      Run [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/) and [flake8](http://flake8.pycqa.org/en/latest/)
      on your local machine.
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) 
      to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All existing tests pass.

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @rwoodsrobinson !

**Comment by utf** [comment]
If possible, I'd also take into account whether spin-orbit coupling is included in the calculation (`LSORBIT = True`), as that will ~double NBANDS.

**Comment by rwoodsrobinson** [comment]
Thanks for mentioning @utf, I'll add it. Know of any other cases where VASP changes the # of NBANDS, or how they are estimated as a function of # of cores?

**Comment by mkhorton** [comment]
@utf it can definitely change drastically in some cases, e.g. imagine a small cell with few bands on something like KNL (64 cores) with default parallelization (I think; I would have to check specific circumstances, but I've definitely seen it change significantly, perhaps this was with OMP threads too)

**Comment by utf** [comment]
Apologies, I meant with a specific INCAR setting rather than the number of cores.

**Comment by mkhorton** [comment]
Good point about SOC btw, VASP manual doesn't mention that but makes sense

**Pull request merged**
