### PR TITLE
Add FunctionalGroupExtractor

### PR DESCRIPTION
**Pull request by espottesmith**
## Summary

Added a new file (functional_groups.py) and class (FunctionalGroupExtractor) in pymatgen.analysis. This new class uses an algorithm developed by Ertl (2017) to identify atoms of interest (heteroatoms and certain special carbons) and then combine connected atoms of interest to form functional groups. It is highly flexible; other than phenyl and methyl groups, no groups are hard-coded. 

## Additional dependencies introduced (if any)

* None (although networkx is required for functional_groups.py)

## TODO (if any)

* Some other functional groups could be hard-coded. For instance, ethyl groups will not be caught because the carbons do not fit any of the requirements laid out by the algorithm.

### CODE REVIEW

**Comment by shyuep** [comment]
This broke code. Can you fix and submit a new PR?

**Comment by shyuep** [comment]
Go to CircleCI and look at the latest build.

**Comment by shyuep** [comment]
https://circleci.com/gh/materialsproject/pymatgen/7929

**Comment by espottesmith** [comment]
Thank you. Working on a fix now, and will send another pull request shortly.

**Pull request merged**
