### PR TITLE
Add electronic structure methods for Species

### PR DESCRIPTION
**Pull request by rkingsbury**
## Summary

Replacing #3851 , this PR implements `electronic_structure`, `full_electronic_structure`, and `valence` methods for `Species`.

Major changes:

- Electronic configurations of ions is added to `periodic_table.json`. Instead of a single string, the `["Electronic structure"]` key for each element is now a `dict` keyed by oxidation state, so the elemental electronic structures are found in `["Electronic structure"]["0"]`. Those of ions corresponding to the common oxidation states are added accordingly, e.g. under `["Electronic structure"]["2"]`. This parallels the way `ionic_radii` are stored. The data themselves are taken from the NIST ASD database listed in the docstrings of the respective methods.
- I removed the word `"(tentative")` from the electron config of `Lr (0)` because the one listed is shown in the NIST database (presumably last time the .json file was updated, `Lr` was not as well understood as it is now).
- Update `electronic_structure` in `Element` to accommodate the new data format
- Implement `electronic_structure`, `full_electronic_structure`, and `valence` methods for `Species`
- Added unit tests, including a comprehensive test covering all `Element` and `common_oxidation_states` which ensures the total number of electrons between the `Element` and `Species` (based on the `full_electronic_structure` is consistent with the oxidation state.
- Updated docstrings with references and slightly more explanatory text for all methods.

## Note

the NIST database only contains electronic structures of **cations**. I was unable to find a similar resource for **anions**, however all of the negative "common oxidation states" could be achieved by filling p orbitals of the corresponding ground state element (e.g., ground state is p2, -4 anion is p6). I took this approach for all negative oxidation states (which are relatively few in comparison to the positive ones) because I feel confident it is correct. However, I welcome suggestions if anyone knows where to find hard data to confirm this.

### CODE REVIEW

**Comment by rkingsbury** [comment]
> @shyuep can I have your thoughts on this implementation? I think all that remains to finish the PR is entering data for the rest of the common oxidation states, but before I spend time on that I want to make sure this looks workable to you. Thanks!

@shyuep friendly reminder about this - once I get your blessing on the approach I've taken, I'll populate the remaining data.

**Comment by rkingsbury** [comment]
Also just a note that the pre-commit tests are currently unhappy about some spellings in `aflow_prototypes`

```
src/pymatgen/analysis/aflow_prototypes.json:1: cristalline ==> crystalline
src/pymatgen/analysis/aflow_prototypes.json:1: Ond ==> One, And
src/pymatgen/analysis/aflow_prototypes.json:1: Bever ==> Never
src/pymatgen/analysis/aflow_prototypes.json:1: CaCl ==> calc
src/pymatgen/analysis/aflow_prototypes.json:1: Parth ==> Path
src/pymatgen/analysis/aflow_prototypes.json:1: cristalline ==> crystalline
src/pymatgen/analysis/aflow_prototypes.json:1: CaF ==> calf
src/pymatgen/analysis/aflow_prototypes.json:1: Sclar ==> Scalar
src/pymatgen/analysis/aflow_prototypes.json:1: Zink ==> Zinc
src/pymatgen/analysis/aflow_prototypes.json:1: Pease ==> Peace, Piece, Please, Lease
```

**Comment by shyuep** [comment]
Seems ok to me. Ignore the spelling issues.

**Comment by rkingsbury** [comment]
@shyuep @mkhorton this is ready for review / merge!

**Comment by shyuep** [comment]
Merged. Thanks!

**Pull request merged**
