### PR TITLE
bug and typo fix for boltztrap2

### PR DESCRIPTION
**Pull request by fraricci**

### CODE REVIEW

**Comment by shyuep** [comment]
Pls fix the pylint errors related to boltztrap2.py. The rest of the errors you can ignore for now.

**Comment by shyuep** [comment]
Thanks.

**Comment by shyuep** [comment]
@fraricci It seems that your changes caused the tests to fail. Can you fix the tests pls? Thanks.

**Comment by fraricci** [comment]
it looks like it's not me:
************* Module pymatgen/cli/feff_input_generation.py
pymatgen/cli/feff_input_generation.py:1:0: F0001: No module named pymatgen/cli/feff_input_generation.py (fatal)

Am I right?

**Pull request merged**
