### PR TITLE
Add HSE-specific vdW parameters to MPHSERelaxSet

### PR DESCRIPTION
**Pull request by hongyi-zhao**
* Add HSE-optimized vdW parameters for dftd3 and dftd3-bj
See below for the related discussion and information: 
https://www.vasp.at/forum/viewtopic.php?t=19551
https://github.com/dftd3/simple-dftd3/blob/3a50cbdf8566b3caa8760499ae21746ec9a5e535/assets/parameters.toml#L80-L82

### CODE REVIEW

**Comment by hongyi-zhao** [comment]
This may not be a good way. Another way I can think of is to modify [vdw_parameters.yaml](https://github.com/materialsproject/pymatgen/blob/master/src/pymatgen/io/vasp/vdW_parameters.yaml) as follows:

```yaml
diff --git a/src/pymatgen/io/vasp/vdW_parameters.yaml b/src/pymatgen/io/vasp/vdW_parameters.yaml
index 6708fbd1e..8adcda275 100644
--- a/src/pymatgen/io/vasp/vdW_parameters.yaml
+++ b/src/pymatgen/io/vasp/vdW_parameters.yaml
@@ -3,8 +3,15 @@ dftd2:
     IVDW: 1
 dftd3:
     IVDW: 11
+    hse:
+        VDW_SR: 1.129
+        VDW_S8: 0.109    
 dftd3-bj:
     IVDW: 12
+    hse:
+        VDW_A1: 0.383
+        VDW_S8: 2.310
+        VDW_A2: 5.685    
 dftd4:
     IVDW: 13
 ts:
```
However, I could not effectively implement the corresponding code adjustments for other parts of this method.

**Comment by hongyi-zhao** [comment]
See [here](https://www.vasp.at/forum/viewtopic.php?t=19658) for the related discussion.

**Comment by shyuep** [comment]
Pls add tests for the new parameters. @mkhorton What needs to be done about the hashes? I still maintain the hashes are creating more headache than they solve.

**Comment by shyuep** [comment]
The failing tests are due to a hash check whenever input set yaml files are modified.

**Comment by hongyi-zhao** [comment]
> The failing tests are due to a hash check whenever input set yaml files are modified.

I should always create a PR based on [materialsproject:master](https://github.com/materialsproject/pymatgen/tree/master) of pymatgen instead of my local branch which includes other unmerged PRs I have made, which triggered this issue.

**Pull request closed without merging**
