### PR TITLE
SCAN input set

### PR DESCRIPTION
**Pull request by shyamd**
This a simple SCAN input set. All potentials have been benchmarked to work with SCAN. The key here is the default to PBE_52 potcars. I'm not sure if this is the best way to go about this?

### CODE REVIEW

**Comment by shyuep** [comment]
Erm, what's the difference with the MVLSCANSet?

**Comment by shyamd** [comment]
What MVLSCANSet? I don't see it.

**Comment by shyamd** [comment]
NVM. found it. That works too!

**Comment by shyamd** [comment]
Two quick questions. I'm not a big fan of the ISYM, EDIFFG, nor NELM parameters. I'm running SCAN for MP using ISYM on, EDIFFG ~ -0.05, and NELEM at default of 100 with decent success. Can i just go ahead and change these parameters or do you want a separate MP input inherited from MPRelaxSet?

**Comment by shyuep** [comment]
You can remove ISYM. EDIFFG is necessary, and I am fine with changing it to 0.05. I have no view on NELEM. Go ahead and change those.

**Comment by shyuep** [comment]
ISYM = 0  is default anyway if you don't specify anything. @HanmeiTang

**Comment by HanmeiTang** [comment]
Will do.

**Pull request closed without merging**
