### PR TITLE
Compress test vasprun.xml files

### PR DESCRIPTION
**Pull request by DanielYang59**
Compressed (`gzip`) test vasprun.xml files.

### Summary:
Total vasprun.xml file size reduced by 78.67% (361 MB -> 77 MB), with test runtime largely unaffected (increased by 1.05% but could be random error)

### Before compression:
Total vasprun.xml file size:
```bash
> find . -type f -name 'vasprun*' -exec du -ch {} + | awk 'END {print}'
361M    total
```

Test runtime:
```bash
........................................................................... [ 25%]
........................................................................... [ 51%]
........................................................................... [ 77%]
.................................................................           [100%]
============================== slowest 30 durations ===============================
7.53s call     tests/io/vasp/test_outputs.py::TestVasprun::test_runtype
6.71s call     tests/io/vasp/test_optics.py::TestVasprun::test_optics
4.45s call     tests/io/vasp/test_outputs.py::TestOutcar::test_stopped
4.44s call     tests/io/vasp/test_outputs.py::TestOutcar::test_stopped_old
4.41s call     tests/io/vasp/test_sets.py::TestMPStaticSet::test_grid_size_from_struct
2.93s call     tests/io/vasp/test_outputs.py::TestAeccars::test_read_write_file
2.59s call     tests/io/vasp/test_outputs.py::TestVasprun::test_standard
2.38s call     tests/io/vasp/test_outputs.py::TestOutcar::test_avg_core_poten
2.35s call     tests/io/vasp/test_outputs.py::TestVasprun::test_projected_magnetisation
2.24s call     tests/io/vasp/test_outputs.py::TestVasprun::test_dfpt_ionic
2.14s call     tests/io/vasp/test_outputs.py::TestOutcar::test_read_piezo_tensor
1.75s call     tests/io/vasp/test_outputs.py::TestOutcar::test_init
1.53s call     tests/io/vasp/test_outputs.py::TestVasprun::test_kpointset_electronvelocities
1.53s call     tests/io/vasp/test_outputs.py::TestVasprun::test_update_potcar
1.35s call     tests/io/vasp/test_outputs.py::TestVasprun::test_nonlmn
1.26s call     tests/io/vasp/test_outputs.py::TestVasprun::test_eigenvalue_band_properties_separate_spins
1.25s call     tests/io/vasp/test_outputs.py::TestChgcar::test_init
0.97s call     tests/io/vasp/test_outputs.py::TestVasprun::test_smart_efermi
0.88s call     tests/io/vasp/test_outputs.py::TestOutcar::test_nplwvs
0.86s call     tests/io/vasp/test_outputs.py::TestOutcar::test_drift
0.85s call     tests/io/vasp/test_outputs.py::TestVasprun::test_energies
0.83s call     tests/io/vasp/test_outputs.py::TestChgcar::test_soc_chgcar
0.66s call     tests/io/vasp/test_sets.py::TestMPAbsorptionSet::test_rpa
0.62s call     tests/io/vasp/test_outputs.py::TestVasprun::test_as_dict
0.58s call     tests/io/vasp/test_outputs.py::TestVasprun::test_get_band_structure
0.56s call     tests/io/vasp/test_outputs.py::TestOutcar::test_read_table_pattern
0.55s call     tests/io/vasp/test_outputs.py::TestOutcar::test_electrostatic_potential
0.51s call     tests/io/vasp/test_outputs.py::TestVasprun::test_search_for_potcar
0.50s setup    tests/io/vasp/test_outputs.py::TestChgcar::test_add
0.44s call     tests/io/vasp/test_outputs.py::TestVasprun::test_float_overflow
290 passed in 77.92s (0:01:17)
```

### After compression:
Total vasprun.xml file size:
```bash
> find . -type f -name 'vasprun*' -exec du -ch {} + | awk 'END {print}'
77M     total
```

Test runtime:
```bash
........................................................................... [ 25%]
........................................................................... [ 51%]
........................................................................... [ 77%]
.................................................................           [100%]
============================== slowest 30 durations ===============================
8.01s call     tests/io/vasp/test_outputs.py::TestVasprun::test_runtype
6.54s call     tests/io/vasp/test_optics.py::TestVasprun::test_optics
4.70s call     tests/io/vasp/test_outputs.py::TestOutcar::test_stopped
4.61s call     tests/io/vasp/test_outputs.py::TestOutcar::test_stopped_old
4.24s call     tests/io/vasp/test_sets.py::TestMPStaticSet::test_grid_size_from_struct
2.73s call     tests/io/vasp/test_outputs.py::TestAeccars::test_read_write_file
2.68s call     tests/io/vasp/test_outputs.py::TestVasprun::test_standard
2.44s call     tests/io/vasp/test_outputs.py::TestVasprun::test_dfpt_ionic
2.38s call     tests/io/vasp/test_outputs.py::TestVasprun::test_projected_magnetisation
2.35s call     tests/io/vasp/test_outputs.py::TestOutcar::test_avg_core_poten
2.14s call     tests/io/vasp/test_outputs.py::TestOutcar::test_read_piezo_tensor
1.72s call     tests/io/vasp/test_outputs.py::TestOutcar::test_init
1.57s call     tests/io/vasp/test_outputs.py::TestVasprun::test_update_potcar
1.52s call     tests/io/vasp/test_outputs.py::TestVasprun::test_kpointset_electronvelocities
1.32s call     tests/io/vasp/test_outputs.py::TestVasprun::test_eigenvalue_band_properties_separate_spins
1.30s call     tests/io/vasp/test_outputs.py::TestVasprun::test_nonlmn
1.17s call     tests/io/vasp/test_outputs.py::TestChgcar::test_init
1.01s call     tests/io/vasp/test_outputs.py::TestVasprun::test_smart_efermi
0.94s call     tests/io/vasp/test_outputs.py::TestOutcar::test_nplwvs
0.88s call     tests/io/vasp/test_outputs.py::TestOutcar::test_drift
0.86s call     tests/io/vasp/test_outputs.py::TestChgcar::test_soc_chgcar
0.85s call     tests/io/vasp/test_outputs.py::TestVasprun::test_energies
0.64s call     tests/io/vasp/test_sets.py::TestMPAbsorptionSet::test_rpa
0.64s call     tests/io/vasp/test_outputs.py::TestVasprun::test_as_dict
0.55s call     tests/io/vasp/test_outputs.py::TestOutcar::test_read_table_pattern
0.54s call     tests/io/vasp/test_outputs.py::TestVasprun::test_search_for_potcar
0.52s call     tests/io/vasp/test_outputs.py::TestOutcar::test_electrostatic_potential
0.51s setup    tests/io/vasp/test_outputs.py::TestChgcar::test_add
0.47s call     tests/io/vasp/test_outputs.py::TestVasprun::test_get_band_structure
0.43s call     tests/io/vasp/test_outputs.py::TestVasprun::test_float_overflow
290 passed in 78.74s (0:01:18)
```

### Project-wise `pytest` run
<details>
  <summary>Expand </summary>
  
Apparently I have many missing dependencies...

  ```bash
  ........................................................................... [  2%]
........................................................................... [  5%]
.....................................s.............................sss..... [  7%]
..........................................sssss.....s..s..................s [ 10%]
.............................................ss.......................s.... [ 13%]
.ssssssss.................................................................. [ 15%]
........................................................................... [ 18%]
........................................................................... [ 21%]
........................................................................... [ 23%]
...........................................sssss..ss..sssssssssssssssssssss [ 26%]
ssssssssssssssssss......................................................... [ 29%]
........................................................................... [ 31%]
........................................................................... [ 34%]
................................s...................................ss..... [ 37%]
................ssss..........................................s.......s.... [ 39%]
...........................s............................................... [ 42%]
.................................................ssssssssssssssssssssssssss [ 45%]
sss........................................................................ [ 47%]
..........sssssssssssssssssss.............................................. [ 50%]
........................................................................... [ 53%]
............................ss.sssssssssssssssssssssssssssssssssssssssss.ss [ 55%]
........................................................................... [ 58%]
........................................................................... [ 61%]
........................................................................... [ 63%]
........................................................................... [ 66%]
........................................................................... [ 69%]
..................................s..................s..................... [ 71%]
........................................................................... [ 74%]
........................................................................... [ 77%]
..............................................................ssssssssss... [ 79%]
........................................................................... [ 82%]
........................................................................... [ 85%]
........................................................................... [ 87%]
........................................................................... [ 90%]
........................................................................... [ 93%]
................................................................s..sssss..s [ 95%]
sssssss...ssssss...s...........s..................ssss..................... [ 98%]
..............ss..............................                              [100%]
============================== slowest 30 durations ===============================
22.38s call     tests/electronic_structure/test_plotter.py::TestBSPlotterProjected::test_methods
15.93s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_plot
14.38s call     tests/symmetry/test_kpath_lm.py::TestKPathLatimerMunro::test_kpath_generation
13.20s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_average_gruneisen
12.85s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_acoustic_debye_temp
12.61s call     tests/analysis/test_structure_analyzer.py::TestMiscFunction::test_average_coordination_number
12.60s call     tests/io/test_phonopy.py::TestGruneisen::test_gruneisen_parameter
12.59s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_thermal_conductivity_slack
12.45s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_tdos
12.42s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_as_from_dict
12.37s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_debye_temp_phonopy
12.34s call     tests/analysis/elasticity/test_elastic.py::TestDiffFit::test_fit
12.34s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_frequencies
12.20s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_multi
11.88s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_phdos
11.83s call     tests/phonon/test_gruneisen.py::TestGruneisenParameter::test_gruneisen
9.52s call     tests/io/vasp/test_outputs.py::TestVasprun::test_runtype
8.58s call     tests/analysis/test_prototypes.py::TestAflowPrototypeMatcher::test_prototype_matching
8.16s call     tests/analysis/elasticity/test_elastic.py::TestElasticTensorExpansion::test_get_yield_stress
7.85s call     tests/io/vasp/test_optics.py::TestVasprun::test_optics
7.30s call     tests/core/test_surface.py::MillerIndexFinderTests::test_generate_all_slabs
6.84s call     tests/core/test_surface.py::TestSlab::test_symmetrization
6.03s setup    tests/io/lammps/test_data.py::TestCombinedData::test_as_lammpsdata
5.99s call     tests/core/test_surface.py::TestSlabGenerator::test_nonstoichiometric_symmetrized_slab
5.53s call     tests/symmetry/test_kpath_sc.py::TestBandStructureSC::test_kpath_generation
5.37s call     tests/core/test_trajectory.py::TestTrajectory::test_extend
5.36s call     tests/io/lobster/test_lobsterenv.py::TestLobsterNeighbors::test_get_info_cohps_to_neighbors
5.14s call     tests/test_cli.py::test_pmg_structure
5.09s call     tests/core/test_trajectory.py::TestTrajectory::test_xdatcar_write
4.97s call     tests/io/vasp/test_sets.py::TestMPStaticSet::test_grid_size_from_struct
============================= short test summary info =============================
SKIPPED [1] tests/analysis/test_functional_groups.py:15: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/io/test_babel.py:16: could not import 'openbabel.pybel': No module named 'openbabel'
SKIPPED [1] tests/io/test_packmol.py:20: packmol executable not present
SKIPPED [1] tests/analysis/magnetism/test_analyzer.py:247: enumlib not present
SKIPPED [3] tests/analysis/test_bond_dissociation.py:16: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/analysis/test_fragmenter.py:80: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/analysis/test_fragmenter.py:66: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/analysis/test_fragmenter.py:71: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/analysis/test_fragmenter.py:113: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/analysis/test_fragmenter.py:108: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/analysis/test_fragmenter.py:156: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/analysis/test_graphs.py:344: graphviz executables not present
SKIPPED [1] tests/analysis/test_graphs.py:572: could not import 'openbabel': No module named 'openbabel'
SKIPPED [2] tests/analysis/test_local_env.py:289: could not import 'openbabel': No module named 'openbabel'
SKIPPED [1] tests/analysis/test_local_env.py:1339: critic2 executable not present
SKIPPED [1] tests/analysis/test_molecule_matcher.py:258: OBAlign is missing, Skipping
SKIPPED [1] tests/analysis/test_molecule_matcher.py:152: OBAlign is missing, Skipping
SKIPPED [1] tests/analysis/test_molecule_matcher.py:156: OBAlign is missing, Skipping
SKIPPED [1] tests/analysis/test_molecule_matcher.py:162: OBAlign is missing, Skipping
SKIPPED [1] tests/analysis/test_molecule_matcher.py:240: OBAlign is missing, Skipping
SKIPPED [1] tests/analysis/test_molecule_matcher.py:246: OBAlign is missing, Skipping
SKIPPED [1] tests/analysis/test_molecule_matcher.py:252: OBAlign is missing, Skipping
SKIPPED [1] tests/analysis/test_molecule_matcher.py:173: OBAlign is missing, Skipping
SKIPPED [1] tests/command_line/test_bader_caller.py:118: bader executable not present
SKIPPED [1] tests/command_line/test_bader_caller.py:86: bader executable not present
SKIPPED [1] tests/command_line/test_bader_caller.py:67: bader executable not present
SKIPPED [1] tests/command_line/test_bader_caller.py:23: bader executable not present
SKIPPED [1] tests/command_line/test_bader_caller.py:133: bader executable not present
SKIPPED [1] tests/command_line/test_critic2_caller.py:22: critic2 executable not present
SKIPPED [1] tests/command_line/test_critic2_caller.py:58: critic2 executable not present
SKIPPED [1] tests/command_line/test_enumlib_caller.py:23: enum_lib not present.
SKIPPED [1] tests/command_line/test_enumlib_caller.py:91: enum_lib not present.
SKIPPED [1] tests/command_line/test_enumlib_caller.py:79: enum_lib not present.
SKIPPED [1] tests/command_line/test_enumlib_caller.py:121: enum_lib not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:64: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:37: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:165: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:138: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:208: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:244: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:104: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:129: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:134: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:125: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:110: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:120: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:116: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:255: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:190: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:286: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:298: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:281: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:322: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:311: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:318: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:329: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:325: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:349: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:339: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:345: gulp not present.
SKIPPED [1] tests/command_line/test_gulp_caller.py:352: gulp not present.
SKIPPED [1] tests/command_line/test_mcsqs_caller.py:64: mcsqs executable not present
SKIPPED [1] tests/command_line/test_mcsqs_caller.py:98: mcsqs executable not present
SKIPPED [1] tests/command_line/test_mcsqs_caller.py:29: mcsqs executable not present
SKIPPED [1] tests/command_line/test_mcsqs_caller.py:48: mcsqs executable not present
SKIPPED [1] tests/command_line/test_mcsqs_caller.py:56: mcsqs executable not present
SKIPPED [1] tests/command_line/test_mcsqs_caller.py:74: mcsqs executable not present
SKIPPED [1] tests/command_line/test_mcsqs_caller.py:86: mcsqs executable not present
SKIPPED [1] tests/command_line/test_vampire_caller.py:35: vampire executable not present
SKIPPED [1] tests/core/test_structure.py:91: enumlib or mcsqs executable not present
SKIPPED [1] tests/core/test_structure.py:1627: could not import 'chgnet': No module named 'chgnet'
SKIPPED [1] tests/core/test_structure.py:1693: could not import 'matgl': No module named 'matgl'
SKIPPED [1] tests/core/test_structure.py:1604: could not import 'chgnet': No module named 'chgnet'
SKIPPED [1] tests/core/test_structure.py:1704: could not import 'matgl': No module named 'matgl'
SKIPPED [1] tests/core/test_structure.py:1714: could not import 'matgl': No module named 'matgl'
SKIPPED [1] tests/core/test_structure.py:1722: could not import 'matgl': No module named 'matgl'
SKIPPED [1] tests/core/test_structure.py:2315: Pytorch and TBLite clash. https://github.com/materialsproject/pymatgen/pull/3060
SKIPPED [1] tests/core/test_structure.py:2325: Pytorch and TBLite clash. https://github.com/materialsproject/pymatgen/pull/3060
SKIPPED [1] tests/core/test_surface.py:668: This test relies on neighbor orders and is hard coded. Disable temporarily
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:262: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:249: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:184: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:212: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:240: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:102: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:128: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:216: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:141: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:118: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:86: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:220: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:153: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:170: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap.py:43: No x_trans.
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:78: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:59: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:97: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:92: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:126: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:123: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:118: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:165: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:150: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:180: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:192: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:284: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:253: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_boltztrap2.py:310: No boltztrap2, skipping tests...
SKIPPED [1] tests/electronic_structure/test_plotter.py:289: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:296: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:303: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:310: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:317: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:324: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:331: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:338: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:345: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:352: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:359: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:366: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:373: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:380: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:387: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:394: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:401: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:408: No x_trans executable found
SKIPPED [1] tests/electronic_structure/test_plotter.py:415: No x_trans executable found
SKIPPED [1] tests/ext/test_cod.py:18: No mysql.
SKIPPED [1] tests/ext/test_cod.py:23: No mysql.
SKIPPED [1] tests/ext/test_matproj.py:503: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:471: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:410: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:121: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:46: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:198: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:367: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:59: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:194: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:217: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:130: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:163: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:297: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:188: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:371: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:393: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:113: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:116: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:205: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:272: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:339: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:314: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:147: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:213: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:343: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:348: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:363: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:52: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:456: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:423: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:483: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:487: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:171: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:180: Legacy PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:521: PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:539: PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:621: PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:645: PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:649: PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:691: PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_matproj.py:872: PMG_MAPI_KEY environment variable not set or MP API is down.
SKIPPED [1] tests/ext/test_optimade.py:37: PMG_MAPI_KEY env var not set or MP is down.
SKIPPED [1] tests/ext/test_optimade.py:19: PMG_MAPI_KEY env var not set or MP is down.
SKIPPED [1] tests/io/qchem/test_outputs.py:299: OpenBabel not installed.
SKIPPED [1] tests/io/qchem/test_outputs.py:336: OpenBabel not installed.
SKIPPED [1] tests/io/test_zeopp.py:68: zeo not present.
SKIPPED [1] tests/io/test_zeopp.py:37: zeo not present.
SKIPPED [1] tests/io/test_zeopp.py:112: zeo not present.
SKIPPED [1] tests/io/test_zeopp.py:81: zeo not present.
SKIPPED [1] tests/io/test_zeopp.py:143: zeo not present.
SKIPPED [1] tests/io/test_zeopp.py:132: zeo not present.
SKIPPED [1] tests/io/test_zeopp.py:164: zeo not present.
SKIPPED [1] tests/io/test_zeopp.py:187: file free_sph.cif not present
SKIPPED [1] tests/io/test_zeopp.py:210: zeo not present.
SKIPPED [1] tests/io/test_zeopp.py:231: zeo not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:101: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:162: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:245: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:207: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:192: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:233: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:360: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:300: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:338: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:330: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:348: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:488: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:536: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:545: enum_lib not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:603: mcsqs not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:613: mcsqs not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:634: mcsqs not present.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:666: icet not installed.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:652: icet not installed.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:677: icet not installed.
SKIPPED [1] tests/transformations/test_advanced_transformations.py:784: hiphive not present. Skipping...
SKIPPED [1] tests/transformations/test_site_transformations.py:213: enum_lib not present.
SKIPPED [1] tests/transformations/test_standard_transformations.py:223: enum_lib not present.
SKIPPED [1] tests/transformations/test_standard_transformations.py:237: enum_lib not present.
SKIPPED [1] tests/transformations/test_standard_transformations.py:254: enum_lib not present.
SKIPPED [1] tests/transformations/test_standard_transformations.py:248: enum_lib not present.
SKIPPED [1] tests/util/test_graph_hashing.py:44: could not import 'emmet.core.graph_hashing': No module named 'emmet.core'
SKIPPED [1] tests/util/test_graph_hashing.py:61: could not import 'emmet.core.graph_hashing': No module named 'emmet.core'
2609 passed, 215 skipped in 690.26s (0:11:30)
  ```
</details>

### Follow-up work

I would go ahead to clean up (notice all VASP test files seem to be placed flat inside the `files` dir, they might deserve their own `vasp` dir) and compress some other VASP test files (CHGCAR*, OUTCAR*) later. Would open a separate PR for that.

### CODE REVIEW

**Comment by DanielYang59** [comment]
Meanwhile I noticed there are `vasprun.xml.lobster.spin` and `vasprun.xml.lobster.nonspin` in `pymatgen/tests/files`. I did a global search and didn't see them being used anywhere. Do you have any idea? @JaGeo Thanks!

**Comment by DanielYang59** [comment]
I would go ahead to clean up (notice all VASP test files seem to be placed flat inside the `files` dir, they might deserve their own `vasp` dir) and compress some other VASP test files (CHGCAR*, OUTCAR*) later. Would open a separate PR for that.

**Comment by JaGeo** [comment]
> Meanwhile I noticed there are `vasprun.xml.lobster.spin` and `vasprun.xml.lobster.nonspin` in `pymatgen/tests/files`. I did a global search and didn't see them being used anywhere. Do you have any idea? @JaGeo Thanks!

Remove them if they are not used anymore

**Review by janosh — APPROVED** [review]
excellent work @DanielYang59! this has been on my todo list for a very long time. 🙏 

in retrospect, i should have proceeded in smaller chunks like this PR rather trying to do everything at once in #3132.

i know this must have taken some time, so much appreciated!

**Comment by DanielYang59** [comment]
> excellent work @DanielYang59! this has been on my todo list for a very long time. 🙏
> 
> in retrospect, i should have proceeded in smaller chunks like this PR rather trying to do everything at once in #3132.

No problem at all @janosh. This cannot have been done so easily without the foundation laid in #3132.

Yes I guess chopping up tasks into small pieces make everything much easier (easier to work on, easier to review and easier to revert when something goes wrong).

I just notice that `compress-test-files` branch but that seems quite out of date. Can you please update that branch and I would push future clean-ups there. Thanks! 😃

**Comment by janosh** [comment]
>  Can you please update that branch and I would push future clean-ups there.

no need, please keep making PRs to `master`. we can just delete `compress-test-files`

**Pull request merged**
