### PR TITLE
Allow usage of `calculate_ng` with a custom ENCUT and PREC values for VASP input sets

### PR DESCRIPTION
**Pull request by matthewkuner**
Add in new kwarg to `calculate_ng` to reduce redundancy with new VASP calculation validator in Emmet.

### CODE REVIEW

**Comment by shyuep** [comment]
Uniitest pls. Thanks.

**Comment by matthewkuner** [comment]
of course @shyuep , was already on it before your comment!

**Comment by matthewkuner** [comment]
@shyuep please give me a bit more time to contemplate adding something extra before you merge this

**Comment by matthewkuner** [comment]
@shyuep ready for merging

**Review by janosh — APPROVED** [review]
Thanks @matthewkuner! 👍

**Pull request merged**
