### PR TITLE
Add `chempot_diagram` module for creation/plotting of chemical potential diagrams

### PR DESCRIPTION
**Pull request by mattmcdermott**
## Summary

* Added new module with class,`ChemicalPotentialDiagram`, for creating and plotting **chemical potential diagrams** for a list of entries with 2 or more elements. Chemical potential diagrams are like normal predominance diagrams (which are already implemented in pymatgen), but they also show the "extra" chemical potential axis -- e.g., a 3D plot for a ternary system.
* Includes ability to plot slices of domains of phases which contain other elements (see reference paper)

This code uses the scipy `HalfspaceIntersection` approach to solve for all domain vertices. For more information, please reference the paper below:

_Todd, Paul K., McDermott, M.J., et al. “Selectivity in yttrium manganese oxide
synthesis via local chemical potentials in hyperdimensional phase space.”
ArXiv:2104.05986 [Cond-Mat], Apr. 2021. arXiv.org, http://arxiv.org/abs/2104.05986._

## TODO (if any)

* Add tests
* Complete remaining docstrings

## Checklist

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/)
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All linting and tests pass.

### CODE REVIEW

**Comment by mattmcdermott** [comment]
@mkhorton Any thoughts on the content of this PR before I finish docstrings and add tests? 

One of the things that may feel weird for normal pymatgen users is that I included a `get_plot()` method within the diagram class itself (as opposed to implementing a new` CPDPlotter` or something of the sort). I am not a huge fan of `PDPlotter` in general as I largely think it is a useless class.... wasn't sure what your thoughts were on this?

**Comment by mkhorton** [comment]
I also have issues with `PDPlotter` (and have a fork somewhere, actually, where I'm working on it) but it needs a large refactor I'm not sure I have time for. I don't feel weird about the `get_plot()` method here. To comment further I'll have to test the PR on my own machine, but I think it looks good.

**Comment by mattmcdermott** [comment]
Added docstrings and tests. I believe this is ready to look over before pulling in? @mkhorton

**Comment by mkhorton** [comment]
Looks fantastic @mattmcdermott, thank you!

**Pull request merged**
