### PR TITLE
Smaller test file + different testing of bandgap

### PR DESCRIPTION
**Pull request by JaGeo**
I think the test_outputs.py is the one that is failing. Thus, I decreased the file size for my test file and also changed the test a little. I hope this helps. If not, I am out of ideas for the moment.

### CODE REVIEW

**Comment by JaGeo** [comment]
It failed again. Any other idea where this could come from? I don't think it is a memory problem.

**Comment by shyuep** [comment]
Yeah, honestly I don't know. It passed when you were running it. But failed when I merged it. I think I have an idea... Let me push a fix.

**Comment by mkhorton** [comment]
What makes you think this isn’t a memory problem?

**Comment by shyuep** [comment]
Ok, force-reinstall of phonopy works in removing the segfault. I think the old phonopy (or rather new phonopy v2+) was still in the system, and we previously encountered segfaults with that. 

However, there are still failures with the fatbands test. See https://circleci.com/gh/materialsproject/pymatgen/8485 .

**Comment by shyuep** [comment]
I would strongly advise against direct comparison of dicts. It is more useful to compare the contents.

**Comment by JaGeo** [comment]
I will correct this in one of the next days.

**Pull request merged**
