### PR TITLE
Fix for the issue #1333

### PR DESCRIPTION
**Pull request by dkorotin**
It fixes new format for phase_factors in PROCAR of VASP 5.4.4. 
The VASP version check is a bit rude, if one knows how to make it better – please, do it.

### CODE REVIEW

**Comment by shyuep** [comment]
Can you please implement a unittest? Thanks.

**Comment by dkorotin** [comment]
> Can you please implement a unittest? Thanks.
To my shame, I do not know what it is and how to implement it. Probably you can show me an example...

**Comment by mkhorton** [comment]
An appropriate place to add a test would be here: 

https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/tests/test_outputs.py#L1094

You may need to also add a version of the new PROCAR format to the test_files folder here:

https://github.com/materialsproject/pymatgen/tree/master/test_files

**Comment by mkhorton** [comment]
I'd also be happy to write a test for this if you wanted to share one of the new PROCAR files.

**Comment by dkorotin** [comment]
Dear Matthew, it would be great!

[PROCAR.gz](https://github.com/materialsproject/pymatgen/files/2632708/PROCAR.gz)

**Pull request merged**
