### PR TITLE
Updated run_type method clean version.

### PR DESCRIPTION
**Pull request by darnoceloc**
## Summary

Short few sentences, and summary of the major changes in bullet 
points

* Feature 1
* Feature 2
* Fix 1
* Fix 2

## Additional dependencies introduced (if any)

* List all new dependencies needed. While adding dependencies that bring
significantly useful functionality is perfectly fine, adding ones that 
add trivial functionality, e.g., to use one single easily implementable
function, is frowned upon. Provide a justification why that dependency is needed. 
Especially frowned upon are circular dependencies, e.g., depending on derivative
modules of pymatgen such as custodian or Fireworks.

## TODO (if any)

If this is a work-in-progress, write something about what else needs 
to be done

* Feature 1 supports a, but not b.

### CODE REVIEW

**Comment by mkhorton** [comment]
Hi @darnoceloc , thanks for persevering with this. This still needs tests to be updated before it can be merged.

Also, I have a request/comment, I saw:

```
                param["run_type"] = "GGA+U" if param["is_hubbard"] else Vasprun.run_type
```

Is this correct? e.g. `is_hubbard` could be true even if the run is not GGA, seems like run_type should always be `Vasprun.run_type` to me?

**Comment by darnoceloc** [comment]
Yes, I agree.
Submit another request and wait for the tests to be updated?

**Comment by mkhorton** [comment]
You should update the tests yourself as part of this pull request.

**Comment by darnoceloc** [comment]
I didn't completely modify that line initially since the 'GGA+U' portion had remained unmodified in for quite sometime but there are multiple flaws in that section of code including below.

 **param["is_hubbard"] = (
                incar.get("LDAU", False) and sum(param["hubbards"].values()) > 0
            ) if incar is not None else False
            param["run_type"] = None** 

I also see new untracked INCAR and KPOINTS files in my pymatgen/io/vasp directory of my head/local branch created for this pull request. 
I did not create these files myself and am not sure how they got in my local directory.

**Comment by darnoceloc** [comment]
The issue is multiple vasprun.xml files in the test_files directory contain the line below for the GGA setting.
Why would this be the case and what should be the default setting in such scenarios (I assume PBE)?
    
**<i type="string" name="GGA">--</i>**

**Comment by shyuep** [comment]
Is this done?

**Comment by mkhorton** [comment]
This PR looks good now, but need to trigger tests to re-run since @darnoceloc force-pushed new changes.

**Comment by darnoceloc** [comment]
What else is required of me with respect to this PR?

**Comment by mkhorton** [comment]
You need to add a test that’s all, otherwise it looks good.

**Comment by darnoceloc** [comment]
I was planning to modify this file to add the tests or should I create a new test file just for this PR?
**https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/tests/test_outputs.py**

**Comment by shyuep** [comment]
Sorry, but this PR modifies 800+ files. We cannot merge a PR with this many changes. Can you close this PR, and resubmit one with the specific changes that you are actually submitting? It helps if your master branch is already up to date with the official master branch.

**Comment by darnoceloc** [comment]
Pardon my error, I am a bit new to the git vcs protocol/workflow and learning as I go.
But I have closed this PR and resubmitted a new/clean one as you suggested.

**Pull request closed without merging**
