### PR TITLE
Read Eigenval for Vasp non spin polarized Calculations

### PR DESCRIPTION
**Pull request by mdforti**
## Summary

Include a summary of major changes in bullet points:

* add a ine to include the case where the eigenval corresponds to non spin polarized

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @mdforti! Do you have an example non-spin-polarized EIGENVAL file to hand too? We can include it as a test case

**Comment by arosen93** [comment]
Could you clarify what issue the EIGENVAL reader has with spin unpolarized calculations? To the best of my knowledge, it has always worked for such systems.

**Comment by mdforti** [comment]
Thank you for taking this. It has been a long time since I was working on it. The version of vasp I was working was older and the EIGENVAL  looks exactly by the EIGENVAL_old  provided by @arosen93 , where the occupations are missing. In that case, also for spin polarized there are no occupations listed, so the reading would not be correct either.

**Comment by janosh** [comment]
From @arosen93's comment, sounds like even with this merged, spin-polarized calcs (3 cols) run with pre 5.4.x Vasp would still be parsed incorrectly as spin-unpolarized by `pymatgen`? I assume the unspoken conclusion here was `pymatgen` EIGENVAL reader doesn't support parsing pre 5.4.x Vasp?

**Comment by janosh** [comment]
Closing this as abandoned.

**Pull request closed without merging**
