### PR TITLE
Fix d2k function

### PR DESCRIPTION
**Pull request by tpurcell90**
Need to use the transpose of the inverse matrix for recipmatrix

## Summary

Major changes:

- fix 1: FHI-aims k-grid sizes from a density

## Checklist

- [x] Google format doc strings added. Check with `ruff`.
- [x] Type annotations included. Check with `mypy`.
- [x] Tests added for new features/fixes.
- [x] If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/lattice.py#L1168-L1172))

Tip: Install `pre-commit` hooks to auto-check types and linting before every commit:

```sh
pip install -U pre-commit
pre-commit install
```

### CODE REVIEW

**Comment by tpurcell90** [comment]
Any updates on if this can get merged in?

**Review by janosh — CHANGES_REQUESTED** [review]
thanks @tpurcell90! 👍  could you add a test that fails without this fix?

**Comment by tpurcell90** [comment]
Test added via static-no-kgrid-si test. 

Unit test can also be added if you prefer that too

**Review by janosh — APPROVED** [review]
thanks! 👍

**Review by janosh — APPROVED** [review]

**Pull request merged**
