### PR TITLE
Bug fix for `calculate_vol`

### PR DESCRIPTION
**Pull request by HanmeiTang**
## Summary

Minor buf fix for `calculate_vol`.

This bug can be reproduced as:
```python
>>> from pymatgen.analysis.defects.utils import TopographyAnalyzer, calculate_vol
>>> from pymatgen.core import Structure

>>> s = Structure.from_file("pymatgen/test_files/chgden/LiFePO4.cif")
>>> a = TopographyAnalyzer(s, ["P", "O"], ["Fe"], check_volume=False, tol=0.1)
>>> a.remove_collisions(1.5)
>>> print([v.volume for v in a.vnodes])
...
AttributeError: 'numpy.ndarray' object has no attribute 'coords'
```

* Fixed a minor bug in `calculate_vol`
* Added unittests
* Minor formatting

### CODE REVIEW

**Comment by mkhorton** [comment]
Hi @HanmeiTang, the diff for this PR seems very large for a small bug fix, is this correct?

**Comment by HanmeiTang** [comment]
Hi @mkhorton, sorry for the confusion. What I actually changed is line#1203 in the original "utils.py". Other changes are simply formatting to meet the PEP8 80-char-per-line requirement. I can undo the formatting if you think it is too hard to see the change.

`c = list(s.coords)`
to
`c = list(coords[i] for i in s)`

**Comment by mkhorton** [comment]
PEP8 changes are fine, thank you :) just wanted to make sure there weren't any other changes hidden. In future it'd be useful to have formatting changes as a separate commit just to be clear.

**Comment by HanmeiTang** [comment]
I see. I will close this PR and pull a new soon. Thanks!

**Comment by mkhorton** [comment]
Hmm, it does seem there are some additional changes beyond the PEP8 formatting? e.g. to pick one very small example, the variable `peak_local_max` is changed to `peak_local_max_found`, it looks like `test_qmodel()` has disappeared etc... what I'm concerned about is that this might have been an old test file you were editing?

**Pull request closed without merging**
