### PR TITLE
Add get_pourbaix_plot_colorfill_by_domain_name()

### PR DESCRIPTION
**Pull request by xhqu1981**
Let the caller be able to specific the color of domain via a dict. Also including the following abilities:

1) more accurate calculation of the text label position, which results in a center closer to human filling. This is implemented by considering the surrounding lines.

2) Avoid overlap the text label with H2O stability lines.

3) Add one more cluster phase which by default uses and in between color of solid and aqueous ions.

4) let the callers able to select which domain text label to be highlight by "bold" style.

5) Misc fine tuning of the label text font and line styles.

Example plot:

no mol pic

### CODE REVIEW

**Comment by kristinpersson** [comment]
Xiaohui - don't pull this to the web master until we have submitted the
paper and gotten the reviews back, ok?

Best

Kristin

On Sun, Apr 24, 2016 at 4:01 PM, Xiaohui Qu <notifications@github.com>
wrote:

> Let the caller be able to specific the color of domain via a dict. Also
> including the following abilities:
>
> 1) more accurate calculation of the text label position, which results in
> a center closer to human filling. This is implemented by considering the
> surrounding lines.
>
> 2) Avoid overlap the text label with H2O stability lines.
>
> 3) Add one more cluster phase which by default uses and in between color
> of solid and aqueous ions.
>
> 4) let the callers able to select which domain text label to be highlight
> by "bold" style.
>
> 5) Misc fine tuning of the label text font and line styles.
>
> Example plot:
>
> [image: no mol pic]
> <https://cloud.githubusercontent.com/assets/4646623/14771113/b9ada47c-0a35-11e6-974e-1ef862de83d9.jpg>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/materialsproject/pymatgen/pull/349
> Commit Summary
>
>    - fix the sign bug of kappa, the correct order should be sigma_22 -
>    sigma_iso
>    - add get_pourbaix_plot_colorfill_by_domain_name() function
>    - make all the lines antialiased
>    - add parameter to choose line width, use alpha channel to make the
>    domain edge looks smoother
>    - let the user to control whether to plot the benchmark line (H line,
>    O line and center lines)
>    - remove alpha channel in domains
>    - add a new version of get_center() which considers the distribution
>    of vertices
>    - use Times New Roman
>    - also use Times New Roman for X and Y ticks
>    - add one significant floating point number to XY ticks lables
>    - make the ticks outside
>    - use Bold text for selected species
>    - use color scheme of MP
>    - make the default line width of boundaries to be 0.5
>    - slightly move the text if overlapping with H2O stability line
>    - default to plot H2O stability line, use smaller dashes
>    - reduce the fontsize of the axis labels
>    - add docs
>
> File Changes
>
>    - *M* pymatgen/analysis/nmr.py
>    <https://github.com/materialsproject/pymatgen/pull/349/files#diff-0>
>    (10)
>    - *M* pymatgen/analysis/pourbaix/plotter.py
>    <https://github.com/materialsproject/pymatgen/pull/349/files#diff-1>
>    (220)
>    - *M* pymatgen/analysis/tests/test_nmr.py
>    <https://github.com/materialsproject/pymatgen/pull/349/files#diff-2>
>    (22)
>    - *M* pymatgen/util/plotting_utils.py
>    <https://github.com/materialsproject/pymatgen/pull/349/files#diff-3>
>    (4)
>
> Patch Links:
>
>    - https://github.com/materialsproject/pymatgen/pull/349.patch
>    - https://github.com/materialsproject/pymatgen/pull/349.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/materialsproject/pymatgen/pull/349>
>



-- 
-- 
Kristin A Persson

Assistant Professor in Materials Science and Engineering
University of California at Berkeley

Staff Scientist
Lawrence Berkeley National Laboratory
Web: http://eetd.lbl.gov/staff/kristin-persson

**Comment by shyuep** [comment]
Erm, I already merged it two hours ago. Is there actually something sensitive in there? It seems just a prettifying of the Pourbaix diagram.

**Comment by kristinpersson** [comment]
As long as the cluster energies are not presented...I am currently writing
the paper on aqueous clusters.

Prettifying is ok :-)

On Sun, Apr 24, 2016 at 7:08 PM, Shyue Ping Ong <notifications@github.com>
wrote:

> Erm, I already merged it two hours ago. Is there actually something
> sensitive in there? It seems just a prettifying of the Pourbaix diagram.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/materialsproject/pymatgen/pull/349#issuecomment-214093464>
>



-- 
-- 
Kristin A Persson

Assistant Professor in Materials Science and Engineering
University of California at Berkeley

Staff Scientist
Lawrence Berkeley National Laboratory
Web: http://eetd.lbl.gov/staff/kristin-persson

**Comment by shyuep** [comment]
I don't know if the clusters are in there. @xhqu1981 would have to comment.

**Pull request merged**
