### PR TITLE
Update to make new builder work

### PR DESCRIPTION
**Pull request by jmmshn**
I updated some keys in the insertion_battery.py and added tests for muO2 data.

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @jmmshn will merge once tests pass

**Comment by mkhorton** [comment]
There are some test errors related to the PR, `ERROR: test_as_dict_summary (pymatgen.apps.battery.tests.test_insertion_battery.InsertionElectrodeTest)`

**Comment by jmmshn** [comment]
oops, I forgot to check that before submitting

**Comment by jmmshn** [comment]
The checks all passed this time,  I didn't account for the fact that the old test files did not have the muO2 data in the entries

**Pull request merged**
