### PR TITLE
Improvements to `PDPlotter`: unary plots, 2D ternaries, better defaults, and highlight entries

### LINKED ISSUE #2402: Highlight selected points in plotly PDPlotter
Sometimes I want to plot a phase diagram and highlight points that are not on the convex hull. It would be nice to be able to give a list of entry names that would then be highlighted in a separate list to "stable" and "above hull". 

@mattmcdermott Is this something that seems reasonable to be able to add?

### LINKED ISSUE #2465: PDplotter plotly backend ternary diagram default colors are terrible
Hi,
Black font on black markers, completely invisible!
截图_选择区域_20220319162537
 
It's nowhere near publication quality plot, please change default look or allow customisation by arguments of PDPlotter.

### PR DESCRIPTION
**Pull request by mattmcdermott**
## Summary

The `PDPlotter` class has been overdue for updates for quite some time. This PR adds missing functionality that has been living in the MP Phase Diagram app. I have also addressed some issues / requested features.

- Feature: unary (1 component) plots. Code adapted from @mkhorton.
- Feature: 2D ternary plots. Code adapted from @mkhorton. This is now the default behavior; can select from "2d" or "3d" with the `ternary_style` argument in `PDPlotter.__init__()`
- Feature: highlighting a collection of provided entries, per the suggestion by @CompRhys resolves #2402.
- Feature: color fill of facets in quaternary plots. Code adapted from @mkhorton.
- Feature: improved default layouts. Most of this is subtle. For example, I changed margins slightly, camera angles, element annotation positions, etc. I think you'll find most of these changes agreeable! (See attached images)
- Feature: new convenience wrapper for plotting entirely within the phase diagram class: `PhaseDiagram.get_plot()`.
- Fix: `PDPlotter.write_image` now works with `plotly` backend. Addresses https://github.com/materialsproject/pymatgen/issues/1966.
- Fix: With changes to defaults, the complaints addressed by @Youjin1985 are hopefully resolved #2465
- Fix: entry-ids were not displaying in `hovertext` for grand potential phase diagrams

## Checklist

- [x] Google format doc strings added. Check with `ruff`.
- [x] Type annotations included. Check with `mypy`.
- [x] Tests added for new features/fixes.
- [x] All tests and linting pass.

### Unary
Screenshot 2023-06-01 at 4 48 00 PM

### Binary
Screenshot 2023-06-01 at 4 48 12 PM

### Ternary (2D)
Screenshot 2023-06-01 at 4 48 39 PM

### Ternary (3D)
Screenshot 2023-06-01 at 4 48 30 PM

### Quaternary
Screenshot 2023-06-01 at 4 48 51 PM

### CODE REVIEW

**Comment by mattmcdermott** [comment]
@janosh I think this is good to go. 

The tests for `PDPlotter` have always been somewhat minimal (just checking if the functions can run); let me know if you think more is needed here.

**Comment by janosh** [comment]
@mattmcdermott Nice work! This looks like a huge improvement! Thanks for all the screenshots to showcase. You probably know test which parts of the code base in particular might benefit from more tests. Happy to wait but also happy to merge as is.

**Comment by mattmcdermott** [comment]
@janosh I think it should be okay to merge. In general, I don't think it's super useful to test Plotly plot generation (beyond the current tests, which make sure figures are generated).

**Review by janosh — APPROVED** [review]

**Comment by rkingsbury** [comment]
@mattmcdermott fantastic work; thanks for this! I'm thinking about how to make similar enhancements in `PourbaixPlotter`. Do you see any opportunities for refactoring where `PDPlotter` and `PourbaixPlotter` could share some of the code you've written here?

**Comment by mkhorton** [comment]
Thanks for merging in my plotting updates @mattmcdermott and the improvements/extensions! Super helpful and much appreciated :)

**Comment by mattmcdermott** [comment]
Thanks for the support guys ❤️

@rkingsbury I'll look into PourbaixPlotter to see if we can streamline anything!

**Comment by mkhorton** [comment]
Re. Pourbaix plotter, most of the plotly improvements are currently in Crystal Toolkit and quite Pourbaix-specific. I’d be very happy to see it upstreamed (removing code from Crystal Toolkit is a-ok), but I’m not sure specifically what improvements remain to be made. I think it’s pretty decent already but could likely benefit from some love too.

**Comment by rkingsbury** [comment]
> Re. Pourbaix plotter, most of the plotly improvements are currently in Crystal Toolkit and quite Pourbaix-specific. I’d be very happy to see it upstreamed (removing code from Crystal Toolkit is a-ok), but I’m not sure specifically what improvements remain to be made. I think it’s pretty decent already but could likely benefit from some love too.

Ah yes, thanks for the reminder @mkhorton . Much like the PD app before this update, I know a lot of the nice Pourbaix enhancements were living in the web app (which I suppose is powered by Crystal Toolkit), so maybe it's just a matter of moving some of that back into pymatgen. If we could get similar functionality to the web within pymatgen I think that's all we need really.

**Comment by mkhorton** [comment]
You can use it via Crystal Toolkit too (in a standalone way eg in a notebook) so it’s there if you want it, nevertheless I think pymatgen is a better home.

**Pull request merged**
