### PR TITLE
added 1e-4 tolerance to is_metal method of BandStructure to account f…

### PR DESCRIPTION
**Pull request by blondegeek**
See [https://github.com/materialsproject/pymatgen/issues/648#issuecomment-295325994](https://github.com/materialsproject/pymatgen/issues/648#issuecomment-295325994).

### CODE REVIEW

**Comment by shyuep** [comment]
Shuldn't the second threshold be -1e-4, rather than 1e-4?

**Comment by blondegeek** [comment]
No, the example on the #648 would still be categorized as metallic in that case.

**Comment by shyuep** [comment]
Let's think about the intent of that method. Basically, the code is asking if there are eigenvalues that are both above and below the efermi level in a band. If there is, then it is a metal. Otherwise, it is not. So why would allowing for a +ve numerical error in the first instance and a -ve numerical error second instance lead to a wrong classification?

More importantly, why is this code not simply ```not np.all(values[i, :] - self.efermi < 1e-4)```?

**Comment by blondegeek** [comment]
I think you are right that one tolerance should be negative, but it should be the first one:
`np.any(values[i, :] - self.efermi < -1e-4) and np.any(values[i, :] - self.efermi > 1e-4)`

This ensures that only energies outside the tolerance on the efermi are used to determine if the materials is a metal.

**Pull request merged**
