### PR TITLE
Battery analysis for anion batteries [WIP]

### PR DESCRIPTION
**Pull request by sthartman**
## Summary
#2328 
* Battery analysis now handles working ion with negative charge
* Added appropriate tests

## TODO (if any)
Pytest run from the command line finds no errors in the pymatgen/apps directory, where I made the changes, but I still need to figure out why the build as a whole is failing.

### CODE REVIEW

**Comment by arosen93** [comment]
@sthartman, I'm having the same issue with the test suite via GitHub Actions. I don't think it's due to any changes you introduced. (cc @mkhorton).

**Comment by shyuep** [comment]
Hi @sthartman , I recently made sure all the tests are properly passing. Can you merge the latest master into your PR first? That should trigger a new test.

**Comment by sthartman** [comment]
Thanks @shyuep, all the checks pass now. Let me know if the reduced coverage is an issue, I could make some more tests to get the other branches.

**Comment by shyuep** [comment]
Great. Thanks. The slgihtly reduced coverage is not a big issue.

**Pull request merged**
