### PR TITLE
KPathLM labels bug fix

### PR DESCRIPTION
**Pull request by munrojm**
## Summary

This PR fixes a small bug in the `KPathLM` class where the code would hang when assigning labels to each of the points in a k-path for some complex cases.

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @munrojm. Is there an existing KPath labels test this case could be added to?

**Comment by munrojm** [comment]
> Thanks @munrojm. Is there an existing KPath labels test this case could be added to?

Good point! I will make one and update the existing test.

**Comment by mkhorton** [comment]
Should be fixed now if you merge latest changes from master. Seems to be a _crash_ in pylint for something that seems correct to me -- will revisit in a future version of pylint assuming it's a bug, for now have excluded this specific version from our CI. Thanks for your patience with this.

**Comment by munrojm** [comment]
> Should be fixed now if you merge latest changes from master. Seems to be a _crash_ in pylint for something that seems correct to me -- will revisit in a future version of pylint assuming it's a bug, for now have excluded this specific version from our CI. Thanks for your patience with this.

Not a problem, that sounds good. Thanks @mkhorton!

**Comment by mkhorton** [comment]
Thanks @munrojm !

**Pull request merged**
