### PR TITLE
NMR symmetrize tensor update 

### PR DESCRIPTION
**Pull request by dongsenfo**
## Summary

Symmetrize the tensor before returning the principal axis system

Uses the symmetrize method from the tensor class

### CODE REVIEW

**Comment by dongsenfo** [comment]
I'm was having trouble managing my local branches, hopefully this only changes the one nmr file?

**Comment by mkhorton** [comment]
Yes, that’s correct, this only changes the one file

**Comment by mkhorton** [comment]
Hi @dongsenfo, tests need to be updated to reflect this change since they're currently failing.

**Comment by dongsenfo** [comment]
I've updated the test, hopefully things should work now!

**Comment by mkhorton** [comment]
Thanks @dongsenfo !

**Pull request merged**
