### PR TITLE
Avoid using `exec` in code

### PR DESCRIPTION
**Pull request by DanielYang59**
## Summary

- Avoid using `exec`, especially from potentially untrusted source (external filename in this case) to avoid potential security issue (alerted by the `xz` backdoor)
- Minor `sourcery` fixes

## Summary by CodeRabbit

- **Refactor**
	- Improved file handling with explicit encoding specification.
	- Enhanced dictionary update syntax for better clarity and performance.
	- Modified handling of topology charges with a more robust default value approach.
	- Updated force field assignment for clearer code comprehension.
	- Revised file parsing and clustering method for efficiency.
	- Enhanced error handling for various atom styles.
	- Optimized file sorting based on a pattern and accessing matched groups in regular expressions.

### CODE REVIEW

**Comment by DanielYang59** [comment]
Can you please review this @janosh. Thanks!

**Review by janosh — APPROVED** [review]
thanks a lot @DanielYang59! 👍

**Comment by DanielYang59** [comment]
Thanks for reviewing! This is the only occurrence of `exec` cross the whole code base AFAIK.

**Comment by DanielYang59** [comment]
I noticed several usage of `eval` across the code base. I would open an PR to address them very soon.

**Pull request merged**
