### PR TITLE
Add MonteCarloRattleTransformation and general refactoring

### PR DESCRIPTION
**Pull request by utf**
## Summary

This pull request introduces a number of miscellaneous features as part of an atomate workflow to calculate lattice thermal conductivity.

- Added MonteCarloRattleTransformation. Uses the hiPhive package to displace atomic sites according to a Monte Carlo routine which punishes small bond distances. I've added an explanation of the algorithm in the docstring of the class.
- Refactored ShengBTE Control implementation. Also added helper methods to construct a Control object from a pymatgen structure and to extract a Structure from an existing Control object. 
- Added type hinting in a few places.
- Updated tests.

## Additional dependencies introduced (if any)

* `hiphive`: Added as an optional dependency. We use this package in atomate to fit the force constants and it also provides several useful functions for generating perturbed structures. This transformation must be added in Pymatgen itself, as it is used in the `TransformerFW` which is only capable of applying Pymatgen transformations.

## Checklist

Work-in-progress pull requests are encouraged, but please put [WIP]
in the pull request title.

Before a pull request can be merged, the following items must be checked:

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). 
      Run [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/) and [flake8](http://flake8.pycqa.org/en/latest/)
      on your local machine.
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) 
      to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All existing tests pass.

### CODE REVIEW

**Comment by utf** [comment]
The remaining mypy errors don't seem particularly reasonable.

**Comment by utf** [comment]
This should be ready to merge now.

**Comment by utf** [comment]
This should also be ready to merge now.

**Comment by mkhorton** [comment]
Thanks!

**Pull request merged**
