### PR TITLE
docs: update compatibility guidance

### PR DESCRIPTION
**Pull request by ltalirz**
## Summary

Drafting an update of the Compatibility guide as requested by @mkhorton in
https://github.com/materialsproject/pymatgen/issues/2083#issuecomment-791597868

## Checklist

Work-in-progress pull requests are encouraged, but please put [WIP]
in the pull request title.

Before a pull request can be merged, the following items must be checked:

- [ ] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). The easiest way to handle this
      is to run the following in the **correct sequence** on your local machine. Start with running
      [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will automatically reformat
      your code to PEP8 conventions and removes most issues. Then run 
      [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by 
      [flake8](http://flake8.pycqa.org/en/latest/).
- [ ] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [ ] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) to type check your code.
- [ ] Tests have been added for any new functionality or bug fixes.
- [ ] All linting and tests pass.

Note that the CI system will run all the above checks. But it will be much more efficient if you already fix most 
errors prior to submitting the PR. It is highly recommended that you use the pre-commit hook provided in the pymatgen 
repository. Simply `cp pre-commit .git/hooks` and a check will be run prior to allowing commits.

### CODE REVIEW

**Comment by shyuep** [comment]
I don't think the writeup is necessarily true. I don't want to give up calendar version just because we are temporarily doing semantic versioning due to the switch over to a namespace package. In future, it will still be calendar versioned.

I think a more important statement is that if you happen to just use pymatgen for its core classes, it really doesn't matter in most instances whether you are using v2018, 2019 or 2021 or 2022. None of the core classes have undergone any backwards incompatible changes in the past few years.

Those who work on the bleeding age of pymatgen will of course have to live with the nature of a research code, i.e., it is always changing!

**Comment by ltalirz** [comment]
> I don't think the writeup is necessarily true. I don't want to give up calendar version just because we are temporarily doing semantic versioning due to the switch over to a namespace package. In future, it will still be calendar versioned.

Oh, I see.

Sorry, I had understood you were going to follow the principle of incrementing the major version number upon breaking changes not just until 2022 but also going forward.

Feel free to disregard this PR then.

> I think a more important statement is that if you happen to just use pymatgen for its core classes, it really doesn't matter in most instances whether you are using v2018, 2019 or 2021 or 2022. None of the core classes have undergone any backwards incompatible changes in the past few years.

Since you mention this, I went back through the aiida-core issue tracker looking for pymatgen-related issues from the last two years

https://github.com/aiidateam/aiida-core/issues/3244
https://github.com/aiidateam/aiida-core/issues/3297
https://github.com/aiidateam/aiida-core/issues/3263
https://github.com/aiidateam/aiida-core/issues/4339
https://github.com/aiidateam/aiida-core/issues/4614
https://github.com/aiidateam/aiida-core/issues/4687
https://github.com/aiidateam/aiida-core/issues/4793

On closer inspection, you are right that most of these are not related to breaking changes. Most were caused by issues with the `numpy` dependency (which should hopefully be fixed now with the `pyproject.toml`) and other dependencies.
Only two were breaking changes - the `species_and_occu` and the recent removal of imports from the core.

All in all, I still think that for a tool like aiida it would still be useful if pymatgen was using semantic versioning... 
but of course announcing them via warnings well in advance already helps as well.

**Comment by mkhorton** [comment]
Adding the `species_and_occu` example to the compatibility page may be a good idea though, if at least to give people a better idea of how often these changes have happened in the past.

**Comment by shyuep** [comment]
@ltalirz Thanks. I will merge this and update the doc to reflect what Matt suggested.

**Comment by shyuep** [comment]
@ltalirz I have clarified the compatibility doc based on your suggested edits. Thanks.

**Pull request merged**
