### PR TITLE
`AseAtomsAdaptor`: Retain `tags` property when interconverting `Atoms` and `Structure`/`Molecule`

### PR DESCRIPTION
**Pull request by arosen93**
Currently, the `.tags` property of the ASE `Atoms` object is lost when interconverting between ASE `Atoms` and Pymatgen `Structure`/`Molecule`. I adopted the solution by @brookwander in https://github.com/ulissigroup/catapalt/issues/2 to ensure the tags do not get lost.

### CODE REVIEW

**Comment by brookwander** [comment]
thanks @arosen93 !

**Comment by arosen93** [comment]
@janosh --- why does ruff hate me? :(

**Comment by janosh** [comment]
Looks like `ruff` just had a new release that finds new issues on `master`. So nothing to do with your changes. Does this still need testing?

**Comment by arosen93** [comment]
Ah I see. No, this should be done!

**Pull request merged**
