### PR TITLE
Pyupgrade 3.7 plus

### PR DESCRIPTION
**Pull request by janosh**
Lots of automatic updates to use newer language features by running

```sh
pyupgrade --py37-plus **/*.py
```

across the whole code base.

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks for this PR @janosh. While I don't expect any significant issues, given the size of the diff I'll need some time to review it.

**Comment by mkhorton** [comment]
(I'll note that similar automatic code tools have been run against pymatgen in the past, and 99% worked but did introduce  one or two small issues that needed to be manually fixed)

**Comment by janosh** [comment]
> I'll need some time to review it.

Sure thing. Is there something I can help check? Run or write more tests for anything particular?

**Comment by mkhorton** [comment]
Nope, not at all. Perhaps being over-cautious, but I just wanted to skim through it myself

**Comment by mkhorton** [comment]
Actually there is a merge conflict now, so that could be fixed?

**Comment by janosh** [comment]
Let me know when to resolve the merge conflicts here. Best done close to review time.

**Comment by mkhorton** [comment]
Thanks, will do. Before I get to this I need to figure out what's happening with CI and the current test failures in the main branch.

We actually had some code tools introduce incorrect type hints recently (Eg `Tuple` -> `tuple`) which does make me want to review more closely but if you can vouch for it, based on your previous PRs, I would be happy to merge without a too-detailed review.

**Comment by janosh** [comment]
I've been using `pyupgrade` for a while now and have never once known it to create problems if used correctly. E.g. it too would convert `Tuple -> tuple` if run in `--py310-plus` mode but of course that'd be user error if your project needs to support older Pythons.

**Comment by shyuep** [comment]
We can close this. I already did pyupgrade on pymatgen a few days back. Thanks for the help.

**Comment by janosh** [comment]
@shyuep I think there are still some things worth merging here like 552e0d9, ab2c75d and b587d68.

**Comment by shyuep** [comment]
Can you submit those as a separate PR? Thanks.

**Comment by janosh** [comment]
@shyuep I rebased onto `master` and force pushed to my fork. Only 34 changed files with 84 additions and 94 deletions. So much more manageable PR now. I think easiest to reopen this PR though. Can update the title/rename the branch if that was your reason for suggesting a new PR?

**Comment by shyuep** [comment]
It seems that I can't reopen the PR after you force pushed it. I suggest you reopen a new PR.

**Comment by janosh** [comment]
@shyuep See #2318.

**Pull request closed without merging**
