### PR TITLE
s-, p-, d-band properties: band filling, band center, band width, skewness, kurtosis, upper band edge

### LINKED ISSUE #2453: Feature Suggestion: DOS-related descriptors (e.g. d-band center, upper d-band edge)
Given that we already have tools to parse DOS data in Pymatgen, it would be great to add some DOS-related descriptors. Some ideas include:
- d-band center
- Plotting the Hilbert transform of the local, projected DOS
- Upper d-band edge (i.e. highest peak position of the Hilbert transform of the projected DOS)

Other suggestions are welcome. I plan to implement these.

### PR DESCRIPTION
**Pull request by arosen93**
## Summary
This PR seeks to add additional features to `pymatgen.electronic_structure.dos` for various orbital-projected DOS properties used in catalysis, including:
- The orbital-projected band center, as defined by [Hammer and Norskov, _Surf. Sci._, 1995](https://www.sciencedirect.com/science/article/pii/0039602896800070)
- The band filling, band width, skewness, and kurtosis of the orbital-projected DOS, as defined by [Xin et al., _PRB_, 2014](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.89.115114)
- The Hilbert transformation of the orbital-projected DOS, which is relevant for the Newns-Anderson model of adsorption
- The Hilbert transform-based upper band edge, as defined by [Xin et al., _PRB_, 2014](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.89.115114)

To benchmark my implementation, I have reproduced the d-band center and upper d-band edge for an example material reported in [Xin et al.](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.89.115114) (included in the test suite). I have also reproduced the band filling, band width, skewness, and kurtosis from [Li et al.](https://pubs.acs.org/doi/abs/10.1021/acscatal.9b05248) (also in the test suite).

Additional changes:
- Fixed several typehint issues with `Orbital` vs. `OrbitalType` in the `CompleteDos` class
- Added a `get_convolved_densities` function to the `Dos` class, which provides a way to smooth the DOS with a simple moving average

Closes #2453.

### CODE REVIEW

**Comment by arosen93** [comment]
@montoyjh I imagine you're not doing much catalysis anymore these days, but if you have any requests along these lines, please let me know!

**Comment by arosen93** [comment]
@mkhorton, when you get a moment, could you help out with this? Locally, all my tests pass, but they're failing here because of unrelated issues with `ChemEnv`.

**Comment by arosen93** [comment]
Okay, this is ready for your review :)

**Comment by mkhorton** [comment]
Thanks @arosen93, this looks great! Will merge shortly. I take it on faith that the values presented in the unit tests are reasonable.

One (excessively nit-picking) question, why `get_band_width` in the method name, but `bandwidth` (no space) in the docstring?

**Comment by arosen93** [comment]
@mkhorton: Thanks!

Re: unit tests, yup they're as reasonable as I can possibly assure. A few papers had codes to calculate these parameters in the SI, and I benchmarked my implementation against theirs.

Re: naming, oops yeah that's because in the literature they often called it "bandwidth", but that would make it incompatible with `get_band_center`, `get_band_kurtosis`, etc.. I'll change the docstring right now.

**Pull request merged**
