### PR TITLE
[WIP]Add F* diagram generator

### PR DESCRIPTION
**Pull request by jonathanjdenney**
## Summary

Include a summary of major changes in bullet points:

* Script to generate f* diagrams 

## TODO (if any)

If this is a work-in-progress, write something about what else needs 
to be done

* add more examples

## Checklist

Work-in-progress pull requests are encouraged, but please put [WIP]
in the pull request title.

Before a pull request can be merged, the following items must be checked:

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). 
      Run [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/) and [flake8](http://flake8.pycqa.org/en/latest/)
      on your local machine.
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) 
      to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All existing tests pass.

Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is
highly recommended that you use the pre-commit hook provided in the pymatgen 
repository. Simply `cp pre-commit .git/hooks` and a check will be run prior to
allowing commits.

### CODE REVIEW

**Comment by mkhorton** [comment]
Hi @jonathanjdenney, nice to see this PR. I noticed you were uploading these files manually. You may find [GitHub Desktop](https://desktop.github.com) useful to commit your changes locally.

**Comment by jonathanjdenney** [comment]
Hi @mkhorton I will check that out. In the meantime I'm getting the error "D100: Missing docstring in public module" from the pydocstyle check and I'm not sure how to fix it.

**Comment by mkhorton** [comment]
Every module file should have a docstring at the top to say what it does, for example see [here](https://github.com/materialsproject/pymatgen/blob/7327a260259e6a0fa32b719582b68720554a400a/pymatgen/core/structure.py#L5) at the top of structure.py.

**Comment by mkhorton** [comment]
To be more specific, I see your file has a module-level docstring, but it's *below* the import statements, so it's not at the top of the file. The error message contains this information: `pymatgen/analysis/Fstar/f_star_diagram_generator.py:1 at module level:` meaning, it found the error in `f_star_diagram_generator.py` and the :1 refers to line 1.

**Comment by mkhorton** [comment]
Ok, I can see the linters pass, which is good. This will also need a test or two before it can be merged. A good place to put this would be in analysis/fstar/tests/test_fstar.py (I think renaming the folder to `fstar` lowercase and the diagram to `fstar.py` instead of `fstar_diagram_generator.py` would be good).

Regarding the example notebook, that's definitely useful, but would be better put into the [`matgenb` notebook repository](https://matgenb.materialsvirtuallab.org) after the functionality has been merged into pymatgen.

**Comment by jonathanjdenney** [comment]
Hi @mkhorton , It's been a while since I have had time to work on this. I've added a test folder and made the name changes you suggested. What kind of testing needs done to get this merged?

**Comment by mkhorton** [comment]
If you look inside the `pymatgen/analysis/tests` directory, you'll see tests for other modules which can give you an idea. Basically, any user-facing feature or function has to have a corresponding test that verifies it generates the output you expect.

The purpose of the tests is so that if a future update, e.g. to Python, to a library, or if someone comes and modifies your code (yourself or a future collaborator), they won't inadvertently either break the module or simply unknowingly change historical behavior that someone might be depending on for their own research.

**Pull request closed without merging**
