### PR TITLE
Fixes Outcar parsing for VASP 6.2.0. Details in issue #2068.

### PR DESCRIPTION
**Pull request by MichaelWolloch**
## Summary

Include a summary of major changes in bullet points:

* Allows Outcar parsing for vasp version 6.2.0

Code changes as [discussed](https://github.com/materialsproject/pymatgen/issues/2068#issuecomment-781645771) with @mkhorton.

### CODE REVIEW

**Comment by shyuep** [comment]
Pls add a simple unit test to ensure this bug does not recur. Thanks.

**Comment by MichaelWolloch** [comment]
I hope the test I added was what you had in mind @shyuep . I have not much experience writing tests...

**Comment by mkhorton** [comment]
Thanks @MichaelWolloch! That test works fine; simply having a VASP 6.2 OUTCAR parsed as part of the test suite will be useful.

**Comment by mkhorton** [comment]
Hi @MichaelWolloch, this has now been merged. Please do fill out our [developer attribution form](https://forms.gle/JnisFb38QDR8QTFTA) so we can [acknowledge you appropriately on our website](https://pymatgen.org/team.html), improvements/bug fixes to pymatgen are always appreciated.

**Pull request merged**
