### PR TITLE
Modify Critic2Caller for more modular use

### PR DESCRIPTION
**Pull request by samblau**
Modifications per discussions with @mkhorton in Atomate PR #598. Made `Critic2Caller.__init__` only responsible for actually calling `Critic2`, and put the rest of the chgcar-specific details into a `from_chgcar` class method.

### CODE REVIEW

**Comment by samblau** [comment]
@mkhorton If this looks good to you, I'd appreciate if a new version could be released following the merge. Thanks!

**Comment by shyuep** [comment]
thanks,.

**Comment by shyuep** [comment]
Why is a release needed?

**Comment by samblau** [comment]
So that I can use this functionality in my open Atomate PR #598

**Comment by shyuep** [comment]
I will release today.

**Comment by samblau** [comment]
Thank you!

**Pull request merged**
