### PR TITLE
Fix the minor document error in `POTCAR Setup`.

### PR DESCRIPTION
**Pull request by hongyi-zhao**
See https://github.com/materialsproject/pymatgen/issues/3830 for more details.

### CODE REVIEW

**Comment by DanielYang59** [comment]
I think these paths look correct to me, perhaps I'm wrong.

The `potcar_PBE/LDA.54/` in the first two paths refers to the directory where the POTCARs are stored.

For the last path looks a bit confusing, perhaps:
```diff
- pmg config --add PMG_VASP_PSP_DIR /path/to/pseudos/pmg_potcars/pmg_potcars
+ pmg config --add PMG_VASP_PSP_DIR /path/to/pseudos/pmg_potcars/POTCARs
```

**Comment by hongyi-zhao** [comment]
> For the last path looks a bit confusing, perhaps:
> 
> ```diff
> - pmg config --add PMG_VASP_PSP_DIR /path/to/pseudos/pmg_potcars/pmg_potcars
> + pmg config --add PMG_VASP_PSP_DIR /path/to/pseudos/pmg_potcars/POTCARs
> ```

No. The `PMG_VASP_PSP_DIR` must point to the top directory of the pmg_potcars.

**Comment by DanielYang59** [comment]
Make sense to me, sorry for the silly question.

**Comment by janosh** [comment]
thanks @hongyi-zhao for reporting and fixing! 👍

**Pull request merged**
