### PR TITLE
Use f-string automatic string coercion: f"{str(x)}" ->  f"{x}"

### PR DESCRIPTION
**Pull request by janosh**
Related #2294.

### CODE REVIEW

**Comment by janosh** [comment]
@shyuep The workflow 

```sh
pytest pymatgen/electronic_structure pymatgen/symmetry pymatgen/ext pymatgen/command_line
```

timed out on Windows and macOS. There is no error, just that the operation was cancelled. Does this require fixing or is it a flaky test?

**Comment by janosh** [comment]
@shyuep Just resolved the merge conflicts here. Could you trigger a workflow run? Not sure why it didn't auto-trigger.

**Comment by shyuep** [comment]
This caused test failures. I t hink it is not in line with the master branch. Pls resubmit after you have pull the latest from master.

**Comment by janosh** [comment]
My merge and then revert? I did merge `master` just before I wrote that comment 3 days ago.

**Comment by shyuep** [comment]
Because I merged and it caused all kinds of test failures. Pls merge master and resubmit a new PR.

**Comment by janosh** [comment]
Weird that it didn't trigger CI. But definitely should have checked its result before merging. Perhaps worth adding [`workflow_dispatch`](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch) to the all CI tests to be able to trigger runs manually in cases where they fail to run automatically.

**Pull request merged**
