### PR TITLE
[WIP] enable MaterialsProject2020Compatibility by default

### PR DESCRIPTION
**Pull request by rkingsbury**
## Summary
Make `MaterialsProject2020Compatibility` the default energy correction scheme in pymatgen.

* `MPRester().get_entries()` and `MPRester().get_pourbaix_entries()` now use MP2020 to correct energies
* `MaterialsProjectAqueousCompatibility` now uses MP2020 instead of legacy MP as the `solid_compat`
* Updated Pourbaix tests to reflect energy shifts due to above change
* removed deprecation warning for legacy `MaterialsProjectCompatibility`

## TODO (if any)

- [x] Refit energy corrections after upcoming data release
- [ ] Update publication detail after resubmission
- [ ] validate output of emmet `ThermoBuilder` when using MP2020 corrections to build all phase diagrams

### CODE REVIEW

**Comment by rkingsbury** [comment]
@shyuep , can you help me understand what is happening with these 'Black would make changes' linting errors? They are affecting multiple PRs and I can't figure out how to resolve them. I run `black` on the files in question from the pymatgen root directory, but still see the error during the flake8 test. Thanks!

**Comment by shyuep** [comment]
To be honest, I don’t know. As far as I am concerned, black runs fine on my machine. If that is the only problem in your code, I will merge it.

**Comment by rkingsbury** [comment]
@mkhorton the correction values in this PR are now up to date with the new DB release, based on the set of experimental data Amanda compiled and that we've been using all along.

The text below summarizes how various energies and magnetic orderings changed compared to the values we fit to at the end of August 2020. Can you please let me know if any of these changes (mainly the magnetic orderings) concern you?

I'll be evaluating alternative refitting strategies using the new matbench dataset next.

```
Energy for entry Na2O (mp-2352) changed from -3.74035 to -3.74051 eV/atom
Energy for entry MgO (mp-1265) changed from -5.98371 to -5.98399 eV/atom
Energy for entry CaO (mp-2605) changed from -6.43897 to -6.43930 eV/atom
Energy for entry NaF (mp-682) changed from -4.32427 to -4.32451 eV/atom
Energy for entry NaBr (mp-22916) changed from -3.05725 to -3.05739 eV/atom
Energy for entry MgI2 (mp-23205) changed from -2.57969 to -2.61059 eV/atom
Energy for entry Al2S3 (mp-684638) changed from -5.03119 to -5.03139 eV/atom
Energy for entry Si (mp-149) changed from -5.42339 to -5.42531 eV/atom
Energy for entry V (mp-146) changed from -9.08236 to -9.08391 eV/atom
Energy for entry Mn (mp-35) changed from -9.16171 to -9.16202 eV/atom
Energy for entry Fe (mp-13) changed from -8.46930 to -8.47001 eV/atom
Energy for entry Fe3O4 (mp-19306) changed from -6.74319 to -6.65127 eV/atom
Magnetic type for entry Fe3O4 (mp-19306) changed from FiM to FM
Energy for entry Co3O4 (mp-18748) changed from -6.00289 to -6.06987 eV/atom
Magnetic type for entry Co3O4 (mp-18748) changed from AFM to FM
Energy for entry Ni (mp-23) changed from -5.77982 to -5.78014 eV/atom
Energy for entry MoO2 (mp-510536) changed from -7.40561 to -7.41002 eV/atom
Magnetic type for entry MoO2 (mp-510536) changed from AFM to FM
Energy for entry WO2 (mp-19372) changed from -7.62360 to -7.71713 eV/atom
Magnetic type for entry MnMoO4 (mp-19081) changed from Unknown to FM
Energy for entry CaV2O6 (mp-27624) changed from -7.40282 to -7.40419 eV/atom
Energy for entry Zn (mp-79) changed from -1.25946 to -1.25974 eV/atom
Energy for entry Ti (mp-72) changed from -7.89505 to -7.89549 eV/atom
Energy for entry CuSO4 (mp-20525) changed from -5.70722 to -5.72252 eV/atom
Magnetic type for entry CuSO4 (mp-20525) changed from NM to FM
Entry Ba3Al2O6 (mp-1196869) has disappeared from the database
Energy for entry GaSb (mp-1156) changed from -3.73512 to -3.73532 eV/atom
Energy for entry Ga2Se3 (mp-1340) changed from -3.89320 to -3.89373 eV/atom
Energy for entry Ga2Te3 (mp-38970) changed from -3.41813 to -3.41923 eV/atom
```

**Comment by rkingsbury** [comment]
Related to the above, the selection of fitting compounds we have been using in MP2020 differs in a few cases from the "likely mpids" nominated in the `matbench_expt_formation_enthalpy` dataset. In every case, the matbench value is on the hull and experimental, whereas the MP2020 value is off the hull and/or theoretical.

The particular one that I wanted to ask about is Fe3O4. The MP2020 nominated material is FM ordered and and 89 meV off the hull, whereas the matbench value is on the hull and AFM ordered. Should we specifically be choosing the FM structure here, even though it's so far off the hull?

As for the other materials, I think it makes sense to update the mpids to the matbench values.

```
mpid for K3AlF6     differs: MP2020: mp-1095079 matbench: mp-1201513
mpid for V2O3       differs: MP2020: mp-18937 matbench: mp-21579
mpid for Fe3O4      differs: MP2020: mp-19306 matbench: mp-31770
mpid for LiFeO2     differs: MP2020: mp-19419 matbench: mp-18782
mpid for FeMoO4     differs: MP2020: mp-556667 matbench: mp-505526
mpid for KFeO2      differs: MP2020: mp-759749 matbench: mp-559464
mpid for MoF5       differs: MP2020: mvc-3781 matbench: mp-504759
```

**Comment by mkhorton** [comment]
> The particular one that I wanted to ask about is Fe3O4. The MP2020 nominated material mp-19306 is FM ordered and and 89 meV off the hull, whereas the matbench value mp-31770 is on the hull and AFM ordered. Should we specifically be choosing the FM structure here, even though it's so far off the hull?

No, definitely not. Fe3O4 is a classic ferrimagnet, so should be neither FM nor AFM. I'll have to take a look at this specific case to see if the correct ground state was deprecated somehow. I'm pretty sure the correct mpid is mp-19306 however.

**Comment by rkingsbury** [comment]
> 
> 
> > The particular one that I wanted to ask about is Fe3O4. The MP2020 nominated material mp-19306 is FM ordered and and 89 meV off the hull, whereas the matbench value mp-31770 is on the hull and AFM ordered. Should we specifically be choosing the FM structure here, even though it's so far off the hull?
> 
> Fe3O4 is a classic ferrimagnet, so should be neither FM nor AFM. I'll have to take a look at this specific case to see if the correct ground state was deprecated somehow. I'm pretty sure the correct mpid is mp-19306 however. (Edited to clarify wording.)

OK. mp-19306 was previously FiM, so it sounds like we should keep that mp-id in anticipation of future DB updates that might put it back on the hull.

**Comment by rkingsbury** [comment]
> > > The particular one that I wanted to ask about is Fe3O4. The MP2020 nominated material mp-19306 is FM ordered and and 89 meV off the hull, whereas the matbench value mp-31770 is on the hull and AFM ordered. Should we specifically be choosing the FM structure here, even though it's so far off the hull?
> > 
> > 
> > Fe3O4 is a classic ferrimagnet, so should be neither FM nor AFM. I'll have to take a look at this specific case to see if the correct ground state was deprecated somehow. I'm pretty sure the correct mpid is mp-19306 however. (Edited to clarify wording.)
> 
> OK. mp-19306 was previously FiM, so it sounds like we should keep that mp-id in anticipation of future DB updates that might put it back on the hull.

OK, after further investigation I see that ALL but one of the cases in which the new dataset mpid differs from the MP2020 mpid are magnetic. It appears that due to deprecation of some of the magnetic tasks, different mpids are now stable for these six materials. In light of that, I'm going to KEEP the previously-assigned mpids for all these 6, but change it for K3AlF6 (in that case, we simply added a new polymorph to the database that is more stable than the previous one).

```
mpid for K3AlF6     differs: MP2020: mp-1095079 matbench: mp-1201513 NM
mpid for V2O3       differs: MP2020: mp-18937 matbench: mp-21579 AFM
mpid for Fe3O4      differs: MP2020: mp-19306 matbench: mp-31770 FM
mpid for LiFeO2     differs: MP2020: mp-19419 matbench: mp-18782 FM
mpid for FeMoO4     differs: MP2020: mp-556667 matbench: mp-505526 FiM
mpid for KFeO2      differs: MP2020: mp-759749 matbench: mp-559464 AFM
mpid for MoF5       differs: MP2020: mvc-3781 matbench: mp-504759 FM
```

**Comment by shyuep** [comment]
@rkingsbury @mkhorton I already cautioned about this a long time back. Things like Fe3O4 (and other mixed valence oxides especially) are extremely sensitive to **charge and magnetic** ordering. Make sure they are really correct before we do this kind of large changes.

**Comment by rkingsbury** [comment]
I've refit the corrections to the latest DB release and updated the experimental data to use higher quality data from the recently-compiled dataset described [here](https://github.com/hackingmaterials/matminer/pull/602). This entailed:

- Replacing older Kubashewski data with other data for many of the fitting compounds. In particular, this newer data caused non-trivial changes to the experimental enthalpies of halide compounds
- Removing 10 compounds from the fitting set that do not match any ICSD entries
- Updating the mpid of one fitting compound because our latest DB has a new, lower energy polymorph

In the end, both the experimental data AND the mpids of fitting compounds are fully consistent with the new dataset, with the exception of the six magnetic compounds described above, for which I retained the older mpids.

After updating the fitting data, our oxygen and halide corrections are more in line with previous work and with the legacy correction scheme.

**Comment by rkingsbury** [comment]
> 
> 
> Related to the above, the selection of fitting compounds we have been using in MP2020 differs in a few cases from the "likely mpids" nominated in the `matbench_expt_formation_enthalpy` dataset. In every case, the matbench value is on the hull and experimental, whereas the MP2020 value is off the hull and/or theoretical.
> 
> The particular one that I wanted to ask about is Fe3O4. The MP2020 nominated material `mp-19306` is FM ordered and and 89 meV off the hull, whereas the matbench value `mp-31770` is on the hull and AFM ordered. Should we specifically be choosing the FM structure here, even though it's so far off the hull?
> 
> As for the other materials, I think it makes sense to update the mpids to the matbench values.
> 
> ```
> mpid for K3AlF6     differs: MP2020: mp-1095079 matbench: mp-1201513
> mpid for V2O3       differs: MP2020: mp-18937 matbench: mp-21579
> mpid for Fe3O4      differs: MP2020: mp-19306 matbench: mp-31770
> mpid for LiFeO2     differs: MP2020: mp-19419 matbench: mp-18782
> mpid for FeMoO4     differs: MP2020: mp-556667 matbench: mp-505526
> mpid for KFeO2      differs: MP2020: mp-759749 matbench: mp-559464
> mpid for MoF5       differs: MP2020: mvc-3781 matbench: mp-504759
> ```

@mkhorton these are the 7 compounds that should be re-run per today's discussion

**Comment by computron** [comment]
Hi all - can I get clarification is happening with the magnetic compounds (e.g. Fe3O4, etc) for the new fitting scheme?

- Will the new fitting scheme be deployed in production prior to these magnetic compounds being completed / re-run?
- Are we now confident on the structure / magnetic state used for these compounds?

**Comment by computron** [comment]
Also, in case it's helpful, I think we previously tried to follow the example of Wang et al (https://doi.org/10.1103/PhysRevB.73.195107) in picking crystal structures:



image

**Comment by rkingsbury** [comment]
> Hi all - can I get clarification is happening with the magnetic compounds (e.g. Fe3O4, etc) for the new fitting scheme?
> 
>     * Will the new fitting scheme be deployed in production prior to these magnetic compounds being completed / re-run?
> 
>     * Are we now confident on the structure / magnetic state used for these compounds?

Hi @computron , I believe we are confident in the magnetic state for the compounds in our fitting set _except_ for the 7 compounds listed above (particularly Fe3O4 which is currently FM but should be FiM). At present our plan is for @mkhorton to rerun this handful of compounds before we use MP2020 in production.

I can also check what we have against the table you posted @computron. If either of you has an expanded list of correct ground state magnetic orderings please send it my way. 

Didn't we integrate this information into the build pipeline validators? If not, I think we should. 

@mkhorton - I noticed that you went ahead and merged this PR activating MP2020 by default in pymatgen. What is your plan w.r.t. releases? Will MP2020 be the default in the `v2022.xxx` releases but not backported to `v2021.xxx`?

**Comment by shyuep** [comment]
As long as the data is live, we can backport to 2021.

**Comment by shyuep** [comment]
It is trivial to do backporting.

**Comment by rkingsbury** [comment]
> 
> 
> Also, in case it's helpful, I think we previously tried to follow the example of Wang et al (https://doi.org/10.1103/PhysRevB.73.195107) in picking crystal structures:
> 
> image

@mkhorton here is a complete list of magnetic materials currently used when fitting the MP2020 corrections, with their magnetic orderings. I've also included any materials whose formulas are listed in the Wang et al. table Anubhav just posted. Any cases where the orderings don't match are marked with MISMATCH

```
Cr2FeO4    (mp-1104680) : FiM 
Mn2O3      (mp-1172875) : FM  MISMATCH (Wang et al. lists AFM)
Ca3Al2O6   (mp-12147  ) : Unknown
CuF2       (mp-1229   ) : FM  
Ca(FeO2)2  (mp-1271532) : FiM 
Fe         (mp-13     ) : FM  
CsO2       (mp-1441   ) : FM  
CuO        (mp-1692   ) : NM  MISMATCH (Wang et al. lists AFM)
KO2        (mp-1866   ) : FM  
TiNiO3     (mp-18732  ) : AFM 
Co3O4      (mp-18748  ) : FM  MISMATCH (Wang et al. lists AFM)
NiSO4      (mp-18749  ) : AFM 
Mn(FeO2)2  (mp-18750  ) : FiM 
Mn3O4      (mp-18759  ) : FiM MISMATCH (Wang et al. lists FM)
MnCO3      (mp-18814  ) : AFM 
Mn2SiO4    (mp-18928  ) : AFM 
V2O3       (mp-18937  ) : AFM 
FeCO3      (mp-18969  ) : AFM 
MnO        (mp-19006  ) : AFM 
NiO        (mp-19009  ) : AFM 
NaO2       (mp-1901   ) : FM  
Si(NiO2)2  (mp-19072  ) : FiM 
MnMoO4     (mp-19081  ) : FM  
TiMnO3     (mp-19082  ) : AFM 
CoWO4      (mp-19092  ) : AFM 
VO2        (mp-19094  ) : FM  MISMATCH (Wang et al. lists NM)
NiCO3      (mp-19147  ) : AFM 
VO         (mp-19184  ) : AFM 
FeSO4      (mp-19254  ) : FM  
Fe3O4      (mp-19306  ) : FM  MISMATCH (Wang et al. lists FiM)
Zn(FeO2)2  (mp-19313  ) : AFM 
Cr2NiO4    (mp-19344  ) : FiM 
NaFeO2     (mp-19359  ) : AFM 
Cr2(SO4)3  (mp-19361  ) : AFM 
WO2        (mp-19372  ) : FM  
CoSO4      (mp-19379  ) : AFM 
MnO2       (mp-19395  ) : FM  MISMATCH (Wang et al. lists AFM)
Cr2O3      (mp-19399  ) : AFM 
MnWO4      (mp-19407  ) : AFM 
ZnCr2O4    (mp-19410  ) : AFM 
TiFeO3     (mp-19417  ) : AFM 
LiFeO2     (mp-19419  ) : FM  
FeWO4      (mp-19421  ) : FM  
TiCoO3     (mp-19424  ) : AFM 
Fe2O3      (mp-19770  ) : AFM 
Fe2SiO4    (mp-20313  ) : FiM 
NiSeO3     (mp-20460  ) : AFM 
CuSO4      (mp-20525  ) : FM  
Cr2CoO4    (mp-20758  ) : FiM 
NiWO4      (mp-21179  ) : AFM 
CoCO3      (mp-21434  ) : AFM 
Co2SiO4    (mp-21856  ) : FiM 
Ca2Fe2O5   (mp-22113  ) : FiM 
CoO        (mp-22408  ) : AFM 
MnSO4      (mp-22554  ) : AFM 
Ni         (mp-23     ) : FM  
V2O5       (mp-25279  ) : NM  MISMATCH (Wang et al. lists DM)
Al2CuO4    (mp-27719  ) : FM  
Al2FeO4    (mp-30084  ) : AFM 
Mn         (mp-35     ) : FiM 
Cu2O       (mp-361    ) : NM  MISMATCH (Wang et al. lists DM)
Al2CoO4    (mp-36447  ) : AFM 
Cr2CuO4    (mp-504573 ) : FiM 
FeCuO2     (mp-510281 ) : AFM 
CrO3       (mp-510421 ) : NM  MISMATCH (Wang et al. lists DM)
MoO2       (mp-510536 ) : FM  
Co         (mp-54     ) : FM  
CaCr2O4    (mp-540582 ) : FiM 
TiMn2O4    (mp-540763 ) : AFM 
Fe2(SO4)3  (mp-540767 ) : AFM 
FeClO      (mp-540828 ) : AFM 
CrF2       (mp-554340 ) : AFM 
VF4        (mp-554799 ) : FM  
CoF2       (mp-555908 ) : AFM 
FeMoO4     (mp-556667 ) : FiM 
FeF2       (mp-556911 ) : AFM 
CoF3       (mp-559473 ) : FM  
NiF2       (mp-559798 ) : FM  
CrF3       (mp-560338 ) : AFM 
MnF2       (mp-560902 ) : AFM 
CoSeO3     (mp-562826 ) : FiM 
NaCrO2     (mp-578604 ) : AFM 
Al2NiO4    (mp-688785 ) : AFM 
Fe2CoO4    (mp-753222 ) : FM  
MnAl2O4    (mp-755882 ) : AFM 
KFeO2      (mp-759749 ) : AFM 
Ti(FeO2)2  (mp-780585 ) : FiM 
Cr         (mp-90     ) : AFM 
MoF5       (mvc-3781  ) : FM  
```

**Pull request merged**
