### PR TITLE
Remove `__ne__` methods

### PR DESCRIPTION
**Pull request by janosh**
Since they're auto-defined by python as `not __eq__()`.

### CODE REVIEW

**Comment by janosh** [comment]
To quote [this SO answer](https://stackoverflow.com/a/30676267): 

> should I implement `__ne__()` operator based on `__eq__`?
> 
> Short Answer: Don't implement it, but if you must, use `==`, not `__eq__`

**Comment by janosh** [comment]
Wait! Still need to fix a test. :)

**Comment by shyuep** [comment]
Don't worry about it.

**Comment by janosh** [comment]
I'm in a call atm, will do it after.

**Comment by shyuep** [comment]
I already fixed it.

**Pull request merged**
