### PR TITLE
Boltztrap2 interface

### PR DESCRIPTION
**Pull request by fraricci**
Here a first version of the interface to BoltzTraP2.
The interface provides the user with three main classes:
- BztInterpolator: it takes care of the interpolation of the bands, giving access to coefficients of the interpolation, eigenvalues on the new denser grid, and others properties. In the same class get_band_structure() and get_dos() functions have place. The first returns a BandStructureSymmLine object interpolating bands along a high symmetry path, the second return a Dos object interpolating bands. Partial doses are also possible.
- BztTransportProperties: it deals with the calculation of the Fermi integrals that give the transport properties: Seebeck, conductivity, electrical part of thermal conductivity and Hall coefficient, conductivity effective mass tensors, Power Factor w.r.t. the chemical potential and temperatures. To create it, a BztInterpolator obj is needed as input. Upon creation, it contains transport properties tensors as properties of the object (i.e. BztTransportProperties.Seebeck_mu as a numpy array). The function compute_properties_doping() calculates all the properties w.r.t. the doping levels in input. When executed, it adds the variables "property"_doping to the BztTransportProperties object (BztTransportProperties.Seebeck_doping as a dictionary {'n':array, 'p':array}).
- BztPlotter: this is in charge of plotting the transport properties w.r.t. chemical potential, the temperature and/or the doping using the dedicated function plot_props(). Other two functions are available: plot_bands() to plot directly a band structure on symmetry line; plot_dos() to plot the total Dos. To create an instance of this object, it needs as input both a BztInterpolator and a BztTransportProperties objects.

Also, a class VasprunLoader is provided. It allows to read all the information needed for the interpolation from a Vasprun object, or from a vasprun.xml file via the from_file() function. A similar class BandstructureLoader performs the same task starting from a BS obj instead (in addition a structure object is needed in this case).

A notebook is available and shows how to use this interface works.
This a first version that tries to reproduce most of the capabilities of the current BoltzTraP interface of pmg. Also, some of the new features of BoltzTraP2, like the use of the first derivatives of energy eigenvalues, are not yet implemented in this version.

### CODE REVIEW

**Comment by shyuep** [comment]
Pls fix failing tests.

**Comment by fraricci** [comment]
The main error is due to the missing package boltztrap2 that is required to make the interface work.
How can we do?

**Comment by shyamd** [comment]
@fraricci Add it to requirements-optional.txt and then the test should install it.

**Comment by shyamd** [comment]
@fraricci It looks like its failing during the pip install. I just tried pip installing boltztrap2 on a fresh environment and it failed to properly compile as well. I think there is some trick to installing it, but that needs to be put into the travis script for it to work out right. Do you remember what these tricks where?

**Comment by fraricci** [comment]
@shyamd could you try this? 
CFLAGS="-std=gnu++11" python3 setup.py install

**Comment by fraricci** [comment]
Hi @shyuep , I solved the problem with the compilation of BoltzTrap2 editing the .travis.yml.
Now it pass the test but it exceed the time limit during testing pymatgen.
Could you have a look? thanks

**Comment by fraricci** [comment]
@shyuep thanks for merging.
I also have a notebook to show how to use this interface.
Where can I add it now that the example folder is not anymore included?

**Comment by shyuep** [comment]
You can add it to matgenb.materialsvirtuallab.org . You can form the repo and contribute your notebook.

BTW, tests are failing on CircleCI because they are not able to install Boltztrap. See https://circleci.com/gh/materialsproject/pymatgen/8001

**Comment by fraricci** [comment]
ok I'll add the notebook there.
well I added the trick to install boltztrap2 only in travis.yml.
Do you want me to add it in CircleCi too?

**Comment by shyuep** [comment]
yes pls

**Pull request merged**
