### PR TITLE
Add a cache to speed up get_el_sp

### PR DESCRIPTION
**Pull request by v1kko**
Uses functools.cache to speed up the conversion of arbitrary objects into Element | Species | DummySpecies.

- One thing to keep in mind is that returned objects are not necessarily unique anymore, they could be returned again through the cache.
- Arguments to `get_el_sp` must be `Hashable`, luckily this seems to be the case

## Summary

Major updates:

- feature 1: massive speed up for get_el_sp

## Checklist

Ensure:

- [x] Google format doc strings added. Check with `ruff`.
- [x] Type annotations included. Check with `mypy`.
- [ ] Tests added for new features/fixes.
- [x] All tests and linting pass.

Tip: Install `pre-commit` hooks to auto-check before every commit:

```sh
pip install -U pre-commit
pre-commit install
```

### CODE REVIEW

**Comment by janosh** [comment]
> One thing to keep in mind is that returned objects are not necessarily unique anymore, they could be returned again through the cache.

This sounds like a foot gun we should stay away from. Could you describe your motivation for this change? Maybe there's a safer way to go about this.

**Comment by janosh** [comment]
Closing this as stale for now. Feel free to report back and we can reopen/discuss further.

**Comment by shyuep** [comment]
Element and Species are immutables. If this has a clear speed up, it should be fine.

**Comment by janosh** [comment]
Species are immutable?

```py
from pymatgen.core import Species

sp = Species("Fe2+", properties={"spin": 5})
sp.spin
>>> 5

sp.spin = 4
sp.spin
>>> 4
```

**Comment by shyuep** [comment]
They are *supposed* to be. That is the reason why this change has zero failures across pymatgen. If you really want to enforce strict immutability, then Species should be changed to a dataclass.

**Pull request merged**
