### PR TITLE
Parameters can be written to exciting input file via nested dictionary

### PR DESCRIPTION
**Pull request by vorwerkc**
## Summary

Small additional feature that allows the user to generate an exciting input file with additional parameters. The parameters are provided in the form of a nested dictionary, which allows to generate a full exciting input files with all elements and attributes.

* Additional arguments for io.exciting.ExcitingInput.write_etree, io.exciting.ExcitingInput.write_string, io.exciting.ExcitingInput.write_file to provide additional parameters that are included in the exciting input

### CODE REVIEW

**Comment by mkhorton** [comment]
Many thanks for this @vorwerkc ! Since `paramdict` is freeform (for any settings not otherwise specified), perhaps it would be better to set this at the end as `**kwargs` instead? Otherwise this looks good to merge.

**Comment by mkhorton** [comment]
Hi @vorwerkc, I made a quick commit to illustrate what I meant by the "kwargs" comment, so now the relevant line is simply:

```
        self._dicttoxml(kwargs, root)
```

and I've updated the test accordingly too. This means, for example, you can still do:

```
        paradir = {'grst': {'do': 'fromscratch', 'ngridk': '8 8 8', 
                    'xctype': 'GGA_PBE_SOL', 'gmaxvr': '14.0'}, 
                    'xs': {'xstype': 'BSE', 'ngridk': '4 4 4', 
                           'ngridq': '4 4 4', 'nempty': '30', 'gqmax': '3.0', 
                           'broad': '0.07', 'tevout': 'true', 'energywindow':
                           {'intv': '0.0 1.0', 'points': '1200'},
                           'screening': {'screentype': 'full', 'nempty': '100'}, 
                           'BSE': {'bsetype': 'singlet', 'nstlbse': '1 5 1 4'}}}

         test_input = ExcitingInput(struct)
         test_input.write_string('unchanged', **paradir)
```

but also, for example,

```
         test_input = ExcitingInput(struct)
         test_input.write_string('unchanged', grst={"xctype": "GGA_PBE_SOL"}, xs=...)  # etc.
```

if you just want to make a smaller change.

**Comment by vorwerkc** [comment]
Hi @mkhorton,
thanks for the review! You are right, your solution is more general and more elegant. I was stuck in a FORTRAN mindset...
From my side, the pull request is ready to be merged.

**Comment by mkhorton** [comment]
Thanks @vorwerkc !

**Pull request merged**
