### PR TITLE
automatic box size overwrite

### PR DESCRIPTION
**Pull request by htz1992213**
## Summary

*The box size values in the CombinedData object is now automatically updated by the min/max values of the coordinates.

### CODE REVIEW

**Comment by htz1992213** [comment]
Am I supposed to fix those docstring??? Why those are merged in the first place...

**Comment by mkhorton** [comment]
The shengbte, structure_vtk and advanced_transformations are the responsibility of other contributors. Any other errors you would have to correct, this is the result of stricter checking for docstrings on commit (if you touch a file that has bad docstrings, it will flag an error).

**Comment by htz1992213** [comment]
Thanks Matt! So it's good to merge?

**Comment by shyuep** [comment]
Thanks! It has been merged.

**Pull request merged**
