### PR TITLE
Further cleanup of Electrode objects

### PR DESCRIPTION
**Pull request by jmmshn**
## Summary
- Change `ConversionElectrode` to type `dataclass` similar to the change to `InsertionElectrode` in #2013 
- Added `x_charge` and `x_discharge` properties to report the number of working ion ver formula unit
- Standardized how the summary dictionary is created, now the base Electrode class has a `get_summary_dict` function which can be improved upon by the Insertion and Conversion objects.
- Added some more tests of the `summary_dict`

The old `as_dict_summary` methods are still around but maybe should be deprecated?

### CODE REVIEW

**Comment by mkhorton** [comment]
Yes, please add a deprecation decorator to `as_dict_summary()`, and we can remove at a later date. Thanks!

**Comment by jmmshn** [comment]
@mkhorton I made some additional (independent) changes to the plotter.

**Comment by mkhorton** [comment]
Can you make `capacity` synonymous with `capacity_grav`? e.g. just add an `or` in line 73, for backwards compatibility (the docstring can be left as-is), I'm not sure if features in the current materials project website rely on the existing behavior

**Comment by jmmshn** [comment]
OK done.  Also maybe we should consider raising the version number up from 0.1.

**Comment by mkhorton** [comment]
I'm not sure the version numbers are useful, we don't have a policy for what they mean or when they're incremented

**Comment by mkhorton** [comment]
Thanks @jmmshn!

**Pull request merged**
