### PR TITLE
Update minimal basis

### PR DESCRIPTION
**Pull request by JaGeo**
This is a very small change of the configuration files for the Lobster basis. We removed the 2p orbitals for Be as they led to problems in our computations and probably should be optional during the projection.

This should hopefully not affect any of the tests.

Best, 
JG

### CODE REVIEW

**Comment by JaGeo** [comment]
Not sure what is going on with the tests as I did not change anything on the code :).

**Comment by JaGeo** [comment]
One other thing: the coverage always seems to be reduced by -0.6% independet of what we are doing. Here, I haven't changed anything on the code.

**Comment by shyuep** [comment]
Don't worry about the coverage. I made it an optional check. This is more for our information rather than a strict check.

**Comment by JaGeo** [comment]
Thank you very much.

**Pull request merged**
