### PR TITLE
Updates to diffusion analyzer

### PR DESCRIPTION
**Pull request by cajfisher**
## Summary

Fixes and changes to diffusion_analyzer.py:

* Now handles single-species systems correctly (specifically, when no framework atoms are present, calculation of framework drift is skipped) 
* Various corrections to function descriptions (typo and grammar fixes, formatting and phrasing made consistent, etc.)

Nb. The original analysis tool assumes all species are ions, but in liquid and gaseous systems, for example, this is not necessarily the case. With a few minor modifications the functions can be made to handle more general msd calculations (i.e., neutral or charged species; obviously mscds are still only useful for charged species). This is the purpose of the proposed changes.

## No additional dependencies introduced

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @cajfisher, this looks good but there are some linter errors (see failed tests):

```
pymatgen/analysis/diffusion_analyzer.py:221:39: E261 at least two spaces before inline comment
pymatgen/analysis/diffusion_analyzer.py:222:18: E261 at least two spaces before inline comment
pymatgen/core/trajectory.py:65:121: E501 line too long (122 > 120 characters)
pymatgen/core/trajectory.py:69:121: E501 line too long (124 > 120 characters)
Error: Process completed with exit code 1.
```

**Comment by mkhorton** [comment]
Many thanks @cajfisher this is great, documentation improvements much appreciated too.

Could you add a quick test for the no framework atoms case? then it looks ready to merge.

**Comment by mkhorton** [comment]
Hi @cajfisher, I'm just checking in on the status of this PR. If a test is added and the merge conflict resolved, it looks ready to merge.

**Comment by cajfisher** [comment]
Dear Matthew,

Sorry for the delay – I fell ill for a while and have been desperately trying to catch up on work since then. I’ll sort out the remaining conflicts as soon as I have a chance.

Best regards,

Craig

**Comment by mkhorton** [comment]
No worries at all, there's no harm if the PR sits here for a while.

**Pull request closed without merging**
