### PR TITLE
Parse projected magnetisation from non-collinear calculations

### PR DESCRIPTION
**Pull request by utf**
## Summary

Added the ability to parse the projected magnetisation from VASP calculations that include spin-orbit coupling or non-collinear magnetism.

For calculations that include orbital projections (`LORBIT = 11`), the projections are written to the vasprun.xml file in the same format as in the PROCAR file (https://www.vasp.at/wiki/index.php/PROCAR). The format of the projections depends on the other calculation parameters:
- For spin-paired calculations (`ISPIN = 1`): There is only one spin channel present.
- For spin-polarised calculations (`ISPIN = 2`): There are two spin channels present.
- For non-collinear or SOC calculations: There are 4 spin channels present.

In the last case, the first spin channel is the usual projection of the wavefunctions onto the atomic orbitals. The last 3 spin channels are actually the projected magnetisation of those orbitals in the 3 cartesian directions.

Previously, the projected eigenvalues from SOC calculations incorrectly had two spin channels, while the remaining spin channels were ignored. This PR fixes the parsing so that the projected magnetisation is extracted correctly for SOC calculations.

I've added a unit test.

### CODE REVIEW

**Comment by utf** [comment]
I've run black on the files, so I don't know why linting is failing saying "Black would make changes". It doesn't...

**Comment by mkhorton** [comment]
@utf different set of black rules maybe? https://github.com/materialsproject/pymatgen/blob/1e36e835967fb8665a6ede344f4e608af50e93c2/pyproject.toml#L10

**Comment by utf** [comment]
I can run black on outputs.py using a line length of 120 but that will cause lots of unrelated changes. Are you sure you'd like me to do that?

**Comment by shyuep** [comment]
Just run black from the root level of pymatgen.

**Comment by utf** [comment]
> Just run black from the root level of pymatgen.

I did. There were no changes.

**Comment by shyuep** [comment]
I have merged this for now

**Comment by utf** [comment]
Thanks!

**Comment by shyuep** [comment]
I ran black on my system on your pulled code and it definitely reformatted the file. Pls check your black version. It might be out of date.

**Comment by utf** [comment]
I am using the latest version of black, so it can't be that.

```
› black --version                                                                                                                                                                       
black, version 20.8b1
```

**Comment by mkhorton** [comment]
Also seeing this issue myself actually.

**Pull request merged**
