### PR TITLE
Guard `TYPE_CHECKING` only imports

### PR DESCRIPTION
**Pull request by DanielYang59**
## Summary

- Guard `TYPE_CHECKING` only imports
- Format docstring to Google style in `io.aims.sets` 

### Can we automate this check (and fix)?

`flake8` provides [`TYP001` rule](https://github.com/asottile/flake8-typing-imports) to check this, but doesn't seem able to correct it automatically. Have to run `flake8 --select=TYP001` and fix manually.

`ruff` might [have this implemented](https://github.com/astral-sh/ruff/issues/2096) but I didn't find it in the [available rules](https://docs.astral.sh/ruff/rules/).

### CODE REVIEW

**Comment by DanielYang59** [comment]
@janosh. Please review this, thanks.

Wondering if we could automate this checking?

**Comment by janosh** [comment]
> Wondering if we could automate this checking?

`ruff` has an open issue about implementing this rule which you could upvote and/or leave a comment

https://github.com/astral-sh/ruff/issues/2302

**Comment by DanielYang59** [comment]
I would resolve it now :)

**Comment by DanielYang59** [comment]
Resolved.

**Comment by janosh** [comment]
is the main benefit here meant to be code clarity? that type-checking-time only imports are clearly separated? i don't think we get any speedup since we're importing the `typing` module anyway to get `TYPE_CHECKING`

**Comment by DanielYang59** [comment]
Thanks for reviewing. And sorry I'm unable to help completely guard all imports by `TYPE_CHECKING`

**Pull request merged**
