### PR TITLE
[WIP] Heisenberg

### PR DESCRIPTION
**Pull request by ncfrey**
## Summary

@mkhorton 

New functionality to take low energy magnetic orderings, map them to a Heisenberg model, compute exchange parameters, and perform Monte Carlo with the VAMPIRE package to calculate critical temperatures.

* Heisenberg model mapping of magnetic materials for calculating exchange parameters.
* Wrapper for VAMPIRE atomistic simulations of magnetic materials package.

## Additional dependencies introduced (if any)

* Vampire5 command line tool for atomistic simulations of magnetic materials.

## TODO (if any)

* Added sophistication to screening/sanitization of input low energy ordering data.
* Cleanup VAMPIRE files after execution.

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @ncfrey !

**Comment by shyuep** [comment]
I propose that you name the pymatgen wrappers around vampire "lestat". :-)

**Comment by mkhorton** [comment]
Looks pretty good, some tests need to be updated (e.g. see test_round_magmoms in CollinearMagneticStructureAnalyzerTest), a few minor PEP8 violations (mostly line length), HeisenbergScreener class definition has extraneous parentheses etc. I haven't had a look at test coverage yet. Overall seems v high quality though + almost ready to merge. Thanks for the good code comments, made reviewing it easy!

**Comment by ncfrey** [comment]
Thanks for the review Matt! Working on those fixes now.

**Comment by mkhorton** [comment]
Find it really weird that ReactionDiagramTest failed here ... there's nothing in this PR that should affect that.

**Pull request merged**
