### PR TITLE
Breaking: Default `user_potcar_settings` to `{"W": "W_sv"}` in all input sets if `user_potcar_functional == "PBE_54"`

### LINKED ISSUE #1707: W_pv not included in newer POTCAR versions
**Describe the bug**
W_pv POTCAR does not exist in the newer POTCAR versions (PBE_54). Using the MVLScanRelaxSet or the LobsterSet for compounds including W will therefore result in an error:

**To Reproduce**
`from pymatgen.ext.matproj import MPRester`
`from pymatgen.io.vasp.sets import MVLScanRelaxSet`
`a = MPRester()`
`struct = a.get_structure_by_material_id('mp-1191364')`
`set = MVLScanRelaxSet(structure=struct, potcar_functional="PBE_54")`
`set.write_input(output_dir=".")`

Does anyone have a suggestion how to fix this? Since a change would affect standard configurations, I wanted to ask for help.

Best, 
JG

### LINKED ISSUE #3016: InputSet looks for wrong W POTCAR when using PBE_54
**Describe the bug**
When creating an input set using the PBE_54 POTCAR setting, the code looks for the non-existent W_pv POTCAR. [This has been replaced by W_sv in the 5.4 version.](https://www.vasp.at/wiki/index.php/Available_PAW_potentials#Recommended_potentials_for_DFT_calculations)

**To Reproduce**
1. Establish PBE_54 POTCAR directory
2. Set `PMG_DEFAULT_FUNCTIONAL: 'PBE_54'` in `~/.pmgrc.yaml`
3. Run the following
```
from pymatgen.core.structure import Structure
from pymatgen.io.vasp.sets import MPStaticSet

struc = Structure.from_str(
"""
# generated using pymatgen
data_Sb2WO6
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   4.97452257
_cell_length_b   5.55751792
_cell_length_c   9.25434909
_cell_angle_alpha   83.52945128
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Sb2WO6
_chemical_formula_sum   'Sb4 W2 O12'
_cell_volume   254.21595972
_cell_formula_units_Z   2
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Sb  Sb0  1  0.44927320  0.38866033  0.16812494  1
  Sb  Sb1  1  0.04965522  0.88677808  0.16648034  1
  Sb  Sb2  1  0.94927320  0.61133967  0.83187506  1
  Sb  Sb3  1  0.54965522  0.11322192  0.83351966  1
  W  W4  1  0.03740281  0.24401928  0.50864705  1
  W  W5  1  0.53740281  0.75598072  0.49135295  1
  O  O6  1  0.77952180  0.53470618  0.44201347  1
  O  O7  1  0.72535535  0.03497081  0.44056689  1
  O  O8  1  0.22535535  0.96502919  0.55943311  1
  O  O9  1  0.27952180  0.46529382  0.55798653  1
  O  O10  1  0.84957778  0.23617072  0.68715870  1
  O  O11  1  0.14248836  0.26735019  0.31118039  1
  O  O12  1  0.64248836  0.73264981  0.68881961  1
  O  O13  1  0.34957778  0.76382928  0.31284130  1
  O  O14  1  0.18624167  0.61241876  0.06049465  1
  O  O15  1  0.31939681  0.11002430  0.06444027  1
  O  O16  1  0.68624167  0.38758124  0.93950535  1
  O  O17  1  0.81939681  0.88997570  0.93555973  1
  """, fmt='cif')

inputs = MPStaticSet(struc, user_potcar_functional = 'PBE_54')
inputs.write_input('W_bugtest')
```

**Expected behavior**
Look for W_sv POTCAR

**Environment (please supply relevant versions and platform info):**
- OS: Ubuntu 18
- 2023.3.23 via pip

### PR DESCRIPTION
**Pull request by janosh**
Closes #3016, closes #1707.

Breaking: `DictSet` drop deprecated kwarg `potcar_functional: str = None`, use `user_potcar_functional: str = None` instead (in ac51e26)

### CODE REVIEW

**Comment by janosh** [comment]
Pinging @JaGeo and @arosen93 for review.

**Comment by janosh** [comment]
Actually, the PR title is accurate. There are input sets that don't have any restrictions on `user_potcar_settings` which I didn't touch. So far, I only changed the input sets that ensure `user_potcar_functional in ("PBE_52", "PBE_54")`. So would make sense to move this behavior up in the class hierarchy into `DictSet` where it would always apply.

**Comment by JaGeo** [comment]
@janosh Currently, this code here, does not work:

`from pymatgen.io.vasp.sets import MPRelaxSet
from pymatgen.core.structure import Structure

structure = Structure.from_dict({'@module': 'pymatgen.core.structure', '@class': 'Structure', 'charge': 0.0,
                                 'lattice': {'matrix': [[2.6794492400614325, 0.0, -1.7723083848423267],
                                                        [7.778511770202987e-16, 4.837013999999999,
                                                         2.9618168562654676e-16], [0.0, 0.0, 5.76034817]],
                                             'pbc': (True, True, True), 'a': 3.21255743, 'b': 4.837013999999999,
                                             'c': 5.76034817, 'alpha': 90.0, 'beta': 123.48244503999997, 'gamma': 90.0,
                                             'volume': 74.65718535099107}, 'sites': [
        {'species': [{'element': 'W', 'oxidation_state': 4.0, 'occu': 1.0}], 'abc': [0.0, 0.5, 0.0],
         'xyz': [3.8892558851014935e-16, 2.4185069999999995, 1.4809084281327338e-16], 'label': 'W4+', 'properties': {}},
        {'species': [{'element': 'W', 'oxidation_state': 4.0, 'occu': 1.0}], 'abc': [0.0, 0.0, 0.5],
         'xyz': [0.0, 0.0, 2.880174085], 'label': 'W4+', 'properties': {}},
        {'species': [{'element': 'O', 'oxidation_state': -2.0, 'occu': 1.0}], 'abc': [0.292339, 0.302264, 0.7959505],
         'xyz': [0.7833075113903194, 1.4620551996959996, 4.066837145169164], 'label': 'O2-', 'properties': {}},
        {'species': [{'element': 'O', 'oxidation_state': -2.0, 'occu': 1.0}], 'abc': [0.707661, 0.802264, 0.7040495],
         'xyz': [1.896141728671114, 3.880562199695999, 2.8013767249885095], 'label': 'O2-', 'properties': {}},
        {'species': [{'element': 'O', 'oxidation_state': -2.0, 'occu': 1.0}], 'abc': [0.707661, 0.697736, 0.2040495],
         'xyz': [1.8961417286711137, 3.3749588003039994, -0.0787973600114904], 'label': 'O2-', 'properties': {}},
        {'species': [{'element': 'O', 'oxidation_state': -2.0, 'occu': 1.0}], 'abc': [0.292339, 0.197736, 0.2959505],
         'xyz': [0.7833075113903193, 0.9564518003039998, 1.1866630601691643], 'label': 'O2-', 'properties': {}}]})
mprelax = MPRelaxSet(structure=structure, user_potcar_functional="PBE_54")
mprelax.write_input("input")
`
The current change does not seem to correctly fix the issue.

**Comment by JaGeo** [comment]
Maybe `user_potcar_settings = {"W": "W_sv"}.update(user_potcar_settings) if user_potcar_settings is not None else {"W": "W_sv"}` instead?

**Comment by janosh** [comment]
Hey @JaGeo, thanks for taking a look! 🙏 

Good catch! Didn't want to write tests until initial feedback but I probably should have noticed this without tests. 😅 

```py
{"W": "W_sv"}.update(user_potcar_settings)
```

returns `None` is the problem. It should have been

```py
user_potcar_settings = {"W": "W_sv", **(user_potcar_settings or {})}
```

Fix and test incoming.

**Comment by janosh** [comment]
@JaGeo I removed `self._config_dict["POTCAR"].update({"W": "W_sv"})` from `LobsterSet` since that's now handled for all subclasses of `DictSet`. Is that ok?

**Comment by JaGeo** [comment]
> @JaGeo I removed `self._config_dict["POTCAR"].update({"W": "W_sv"})` from `LobsterSet` since that's now handled for all subclasses of `DictSet`. Is that ok?

@janosh yes, completely fine!

**Pull request merged**
