### PR TITLE
Remove more deprecated stuff

### PR DESCRIPTION
**Pull request by janosh**
Follow up to #2397 and #2401.

Deletes some more code [@shyuep said is very old](https://github.com/materialsproject/pymatgen/pull/2397#issuecomment-1025976675).

### CODE REVIEW

**Comment by shyuep** [comment]
The get_neighbors old should not be removed. It is a debugging code that is very useful. Basically it is a brute force version of the get_neighbors that is very slow but guaranteed to be correct because of the very simple logic.

**Comment by janosh** [comment]
@shyuep Yeah wasn't sure about whether that one should go. Put it back in.

**Comment by mkhorton** [comment]
Thanks for this @janosh. If removing old code (even if marked as deprecated), please also add a note to https://github.com/materialsproject/pymatgen/blob/master/docs_rst/compatibility.rst in the PR.

**Comment by janosh** [comment]
@mkhorton Ah cool, wasn't even aware of that file (even though I'd made auto-changes to it 😅). Good thing it exists! Though it appears to be a bit out of date. The file says pmg still supports py3.7. Will bring it up to date.

**Comment by janosh** [comment]
I placed the removed functions under a new heading "Unreleased". Whoever publishes the next version should fill in the right version number.

**Comment by janosh** [comment]
Screen Shot 2022-01-31 at 21 34 52

**Comment by mkhorton** [comment]
Thanks @janosh!

**Pull request merged**
