### PR TITLE
Add get_chempot_correction method in interface_reactions module

### PR DESCRIPTION
**Pull request by yihanxiao92**
## Summary

Added get_chempot_correction method in the interface_reactions module with its tests, the purpose is to enable users to obtain correction term for chemical potential of gaseous phase at given temperature and pressure. The reference state is T=298.15 K and p = 1 bar. This method can be used in the interface reaction web app. @dwinston 

* Calculate the correction for chemical potential of gaseous phase at given temperature and pressure.

### CODE REVIEW

**Comment by mkhorton** [comment]
(Note that the AppVeyor failure `ImportError: cannot import name 'get_backend' from 'matplotlib' (c:\miniconda36-x64\lib\site-packages\matplotlib\__init__.py)` is not a result of this Pull Request -- I'm still trying to figure out what's causing this error.)

**Comment by yihanxiao92** [comment]
Ok, could you let me know if I should re-open the pull request again?

**Comment by mkhorton** [comment]
Nope, you're fine, this PR looks good. That's why I left the comment, just to emphasize that the AppVeyor test failures weren't a result of your code.

**Comment by yihanxiao92** [comment]
> Nope, you're fine, this PR looks good. That's why I left the comment, just to emphasize that the AppVeyor test failures weren't a result of your code.

I see. Thanks!

**Pull request merged**
