### PR TITLE
Proposal for Magmom class

### PR DESCRIPTION
**Pull request by mkhorton**
## Summary

New proposal for `electronic_structure.core.Magmom` class to simplify working between scalar and vector-type magnetic moments for collinear and non-collinear electronic structure calculations.

Internally implements a spin quantization axis, following exactly the specification of `SAXIS` tag in VASP documentation.

Should give unsurprising results:

* if you want to use it as a scalar Magmom, e.g. `m = Magmom(5.0)`, this will work as expected with `float(m)` giving `5.0`

* if you want to use it as a list-type Magmom, e.g. `m = Magmom([1.0, 2.0, 3.0])`, this should also work as expected with `m[0]` giving `1.0`

* if you want to use a custom `SAXIS`, you can either use `m = Magmom([1, 2, 3], saxis=[1,1,1])` or you can use `m = Magmom([1,2,3])` and `m.get_moment(saxis=[1,1,1])`.

There also exist static helper methods such as:

* `Magmom.are_collinear(magmoms)` to check if a list of magmoms are collinear

* `Magmom.get_consistent_set_and_saxis(magmoms)` to return a list of magmoms with the same spin axis, and the spin axis itself to be used with VASP's `SAXIS` tag

For existing structures, can update `magmoms` with `[Magmom(m) for m in magmoms]` if any of the new functionality is required.

Would also simplify use and implementation of `MagCifParser` (#508). In particular, `MagCifParser` will always output a Structure with vector magmoms. However, for those structures which have collinear spin, a collinear approximation can be used with scalar magmoms, and `[float(m) for m in magmoms]` will give the correct values in this instance even in the case of e.g. antiferromagnetic structures. Additionally, `MagCifParser` and `MagCifWriter` need to read/write magmoms in terms of crystal axes, which is made possible by this new class.

PR is submitted for comments / code review. Feedback appreciated!

## Additional dependencies introduced (if any)

None

## TODO (if any)

* ~~Further testing.~~
* ~~Implement `get_moments_relative_to_crystal_axes` method used by `MagCifWriter`.~~
* Code review.
* (Future) If/when `Magmom` class is more mature, could change `io.vasp` to use it by default.

### CODE REVIEW

**Comment by shyuep** [comment]
Many thanks. Sorry for the lateness in merging. I was thinking if there are better ways to structure the class. For now, this looks great!

**Comment by mkhorton** [comment]
No problem at all, I'm not convinced this is the best way of doing it either, but I think it works for now. Thanks for merging!

**Comment by shyuep** [comment]
I have just pushed a bunch of changes to simplify the implementation a little. I understand the rationale for making it immutable, but for now, let's just let it flow a little.

**Comment by shyuep** [comment]
If you really want to make it immutable, you probably should subclass a namedtuple and add the relevant functions needed.

**Comment by mkhorton** [comment]
Okay, that sounds good, thanks for the clean-up! I'm completely fine with it being mutable, I don't have strong feelings either way in that regard.

(The write-only numpy arrays were probably a bit heavier than necessary anyway, I tried using them to simplify performing vector operations elsewhere, but maybe named tuples would have been better.)

**Pull request merged**
