### PR TITLE
Support Multiple Frame XYZ; Minor Changes to QChem

### PR DESCRIPTION
**Pull request by xhqu1981**
* Added class MXYZ to support multiple frame xyz (e.g. MD trajectory)
* Add support for "velocity" section to QChem module to AIMD setup.
* Add class QcNucVeloc to parse QChem AIMD velocity output.

### CODE REVIEW

**Comment by shyuep** [comment]
I think MXYZ and XYZ classes should be merged.

**Comment by xhqu1981** [comment]
I was thinking about it. But, are you sure? It will change the API. e.g. molecules (list) vs molecule. Of course, we can do ad-hoc stuff to make it file dependent, then we will force the user to test the type of molecule.

**Comment by xhqu1981** [comment]
I mean the molecule property can be either a list of molecule or just a molecule, but the user will need to test wether it is a list.

**Comment by xhqu1981** [comment]
An alternative would be to have both molecule and molecules properties. molecule returns the last frame in case multiple frame XYZ. Please let me know what is your preference.

**Comment by xhqu1981** [comment]
@shyuep Merged. Please check whether you like it.

**Pull request merged**
