### PR TITLE
pin python 3.12 in CI and `requires-python`

### PR DESCRIPTION
**Pull request by DanielYang59**
### Summary

- Pin Python 3.12 in CI for now, as it seems a lot of dependencies don't support Python 3.13 yet #4100

### CODE REVIEW

**Comment by JaGeo** [comment]
The last set of tests never started. Thus, we are stuck here. Any thoughts, @DanielYang59 ?

**Comment by DanielYang59** [comment]
> The last set of tests never started. Thus, we are stuck here. 

I don't know the exact reason, but my guess is the unstarted set is the cached set for our current config (python > 3.10 for Ubuntu). As the finished number of tests is exactly what we asked ` 42 successful, 1 skipped, and 10 expected checks `, the last 10 expected checks look like some kind of "ghost" from previous cache.

I didn't find any related reports in GitHub Community so I might open one later.

**Comment by ab5424** [comment]
@DanielYang59 @JaGeo I think that the branch protection rules require a check under the name `test (ubuntu-latest, >3.10, lowest-direct, ci,optional)` to pass (hence the "Required" tag at the end of the line) but since that doesn't exist anymore so it can't report its status. I saw the same thing in one of my projects. The only workaround I know is to temporarily remove that rule from the repo setting.

**Comment by DanielYang59** [comment]
@ab5424 Bravo! you are the savior.

> I think that the branch protection rules require a check under the name

I don't have write access to the repo, but sounds like the branch protection rules are dynamically generated based the test matrix from the master branch?

> The only workaround I know is to temporarily remove that rule from the repo setting.

Maintainers should be able to do a manual (force) merge (not using auto-merge)?

**Comment by DanielYang59** [comment]
For some reason I'm still seeing "ghost" expected checks from other PR where the config should have been updated on master branch, perhaps the branch protection rule is hard coding to expect `ubuntu-latest, >3.10`? I cannot check myself as I don't have access

**Pull request merged**
