### PR TITLE
Add OPTIMADE adapter

### PR DESCRIPTION
**Pull request by ml-evs**
## Summary

This PR adds a converter between the `pymatgen.core.Structure` object and an OPTIMADE structure resource, migrated primarily out of https://github.com/Materials-Consortia/optimade-python-tools/blob/master/optimade/adapters/structures/pymatgen.py with the aim to remove it from our library.

## Todos

- [x] Finish off tests
- [ ] See if it can be used internally in the `pymatgen.ext.optimade` client (future work)

## Checklist

- [x] Google format doc strings added. Check with `ruff`.
- [x] Type annotations included. Check with `mypy`.
- [x] Tests added for new features/fixes.
- [x] If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/lattice.py#L1168-L1172))

### CODE REVIEW

**Comment by shyuep** [comment]
I would put this in pymatgen.ext rather than pymatgen.io. The ext are external interfaces to things like web resources. E.g., matproj is in pymatgen.ext.

**Comment by mkhorton** [comment]
Given this is purely for conversion to/from the OPTIMADE schema, `io` is appropriate (but yes, any API-calling code lives in `ext`).

Thanks for the PR @ml-evs !

**Comment by ml-evs** [comment]
Apologies, I made this during the OPTIMADE workshop and your responses got lost in the notifications -- happy for this to go wherever but agree with Matt that `io` seems more appropriate to me (given that more tools are adding "offline" OPTIMADE support).

I'll get around to adding a couple more tests to this, but I think the code itself is ready for review.

**Comment by ml-evs** [comment]
Ok, slightly concerned that rebasing this PR has lead to 395 files being changed...

**Comment by janosh** [comment]
> Ok, slightly concerned that rebasing this PR has lead to 395 files being changed...

that's from the recent 9100860d7d which didn't ensure [`pymatgen` is recognized as a first-party package](https://docs.astral.sh/ruff/settings/#lint_isort_known-first-party)

**Comment by ml-evs** [comment]
Ok, rebased this more intelligently this time, have beefed up the test a little and think its ready to go.

**Pull request merged**
