### PR TITLE
Use TypeError as oxi_state is set to None, not unset

### PR DESCRIPTION
**Pull request by RoberTnf**
## Summary

Fixing #1228

* Change to TypeError, as this is the one we want to catch, `oxi_state` is set to `None`, not unset
* Remove unnecessary code

### CODE REVIEW

**Comment by RoberTnf** [comment]
The tests were failing as loading from a .mcif file would not set oxi_state to None. I'm checking for both `AtributeError` and `TypeError`.

Also I added new tests to check for this issue.

**Comment by RoberTnf** [comment]
Travis was not raising a timeout in one of the tests, so I lowered the parameter in order to try to avoid this weird bug.

**Comment by RoberTnf** [comment]
Also, the tests in `test_enumlib_caller` are skipped if this fails:

```enum_cmd = which('enum.x') or which('multienum.x')
makestr_cmd = which('makestr.x') or which('makeStr.x') or which('makeStr.py')
enumlib_present = enum_cmd and makestr_cmd
test_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..",
                        'test_files')


@unittest.skipIf(not enumlib_present, "enum_lib not present.")```

However, `enum.x` and `makestr.x` are already in: https://github.com/materialsproject/pymatgen/tree/master/cmd_line/enum

Can I just hardcodeaAlso, the tests in `test_enumlib_caller` are skipped if this fails:

```enum_cmd = which('enum.x') or which('multienum.x')
makestr_cmd = which('makestr.x') or which('makeStr.x') or which('makeStr.py')
enumlib_present = enum_cmd and makestr_cmd
test_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..",
                        'test_files')


@unittest.skipIf(not enumlib_present, "enum_lib not present.")```

however, `enum.x` and `makestr.x` are already in: https://github.com/materialsproject/pymatgen/tree/master/cmd_line/enum
Also, the tests in `test_enumlib_caller` are skipped if this fails:

```enum_cmd = which('enum.x') or which('multienum.x')
makestr_cmd = which('makestr.x') or which('makeStr.x') or which('makeStr.py')
enumlib_present = enum_cmd and makestr_cmd
test_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..",
                        'test_files')


@unittest.skipIf(not enumlib_present, "enum_lib not present.")```

however, `enum.x` and `makestr.x` are already in: https://github.com/materialsproject/pymatgen/tree/master/cmd_line/enum

Instead of running `which` and skipping if it's not found, maybe we should just hardcode the position of those files?

**Comment by mkhorton** [comment]
@RoberTnf enum.x is machine-specific (it's a compiled code), so not everyone cloning the repo would be able to run those tests, which is why `which` is called

**Pull request merged**
