### PR TITLE
Remove unused mypy ignores

### PR DESCRIPTION
**Pull request by janosh**
Might want to add

```cfg
[mypy]
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true
```

 to `setup.cfg` in future though currently emits too many type errors to deal with.

### CODE REVIEW

**Comment by janosh** [comment]
@shyuep Given how slow `mypy` is, is there a good reason for deleting the cache on every run?

https://github.com/materialsproject/pymatgen/blob/9bdf9fb8eebf4bef66f8a3541cfd27ba8ee1bccf/.github/workflows/lint.yml#L28-L32

**Comment by shyuep** [comment]
When it is cached, the results may be inaccurate. In any case, the speed is not a big limiting factor for CI.

**Comment by janosh** [comment]
CI error seems unrelated?

```py
def predict_mp(self, model_name, mp_id):
        """
        Predict using the http://megnet.crystals.ai/ API.
        """
        response = None
        url = self.url + f"/predict_mp/{model_name}/{mp_id}"
        try:
            response = self.session.get(url)
            if response.status_code in [200, 400]:
                return response.json()
            raise ValueError(f"REST query returned with error status code {response.status_code}")
        except Exception as ex:
            msg = f"{ex}. Content: {response.content}" if hasattr(response, "content") else str(ex)
>           raise ValueError(msg)
E           ValueError: REST query returned with error status code 503.  Content: ...
```

**Comment by shyuep** [comment]
The CI errors are related to the MP website being down.

**Pull request merged**
