### PR TITLE
Magnetic Space Group Symmetry

### PR DESCRIPTION
**Pull request by mt-huebsch**
Hello! 

The following suggestions should be useful when dealing with non collinear magnetism. It's my first time proposing something to another project. Please, let me know what you think!

## Summary

Implemented an ApplyMagSymmOpTransformation object, that can apply a magnetic space group operation to a structure. 

This is used in the other new object, MagneticSpaceGroupAnalyzer, which can determine the magnetic space group in two steps: 
* Find the magnetic space group operations, which leave the structure invariant. 
* Use the tool IDENTIFY MAGNETIC GROUP made available by the Bilbao Crystallographic Server on the website www.cryst.ehu.es

## Additional dependencies introduced 

mechanize: Introduced in order to navigate on the web interface of the tool IDENTIFY MAGNETIC GROUP.

I want to emphasize, that I am not affiliated with the Bilbao Crystallographic Server and that we may better get in touch with them before interfacing their tool. Though I wanted to make sure you are interested in my proposal, before asking them. Hope that's all right?

## TODO
(Or rather ideas what to work on:)

In MagneticSpaceGroupAnalyzer
* Get rid of circular dependencies btw pymatgen.transformations and pymatgen.symmetry
* Add a function get_refined_structure(self) analogous to SpacegroupAnalyzer
* Add function to return Magnetic Laue group
* Use Magnetic Laue Group + Seemann et al (2015) to determine symmetry-imposed shape of linear response tensor.

In io.cif
* Implement an magnetic CIF file writer. (First attempt failed because it needs get_refined_structure(self) )

(About me: My name is Marie-Therese. I am a PhD student in Ryotaro Aritas group at the University of Tokyo. Hard to guess, but my work focuses on non collinear magnetism. )

### CODE REVIEW

**Comment by mkhorton** [comment]
Hi @mt-huebsch -- it would be good if we were able to determine magnetic space groups, and we're all fans of Bilbao's tools here and I use them myself regularly. The problem is that we can't rely on an external service to offer this functionality. If the Bilbao server is slow or goes offline, or if a user attempts to use pymatgen on a server without an external internet connection, then any tools that depend on this pymatgen functionality will cease to work. We are exploring other avenues for determination of magnetic space group symmetry.

**Comment by mkhorton** [comment]
Actually, to clarify, if you wanted to write this and contribute to pymatgen we *would* gratefully accept it (provided this is done with Bilbao's permission, or otherwise queries their website in a polite way), however we wouldn't write this ourselves.

If you do want to contribute an interface an appropriate place to put the code would be `pymatgen.ext.bilbao` to emphasize this is calling an external service.

**Comment by mkhorton** [comment]
Finally, magnetic CIF writing should currently be supported by pymatgen -- if you're encountering bugs though please do open a bug report issue.

**Comment by mt-huebsch** [comment]
Hi @mkhorton! 

What do you mean by exploring other avenues to determine the magnetic space group (mspg)? Are you working on an implementation to get the mspg from the list of xyzt operations? 

Contacting Bilbao and implementing `pymatgen.ext.bilbao` would be a simple solution. But I agree with your argument about offline availability and robustness. Personally, I would also prefer more transparency. Maybe it's me, but I could not find the algorithm behind their tool. Finally, to open a new module suggests t write complete interfaces, which I was not planing to do.

Concerning the mcif functionality. The P 1 case works well, but when I want to use the magnetic symmetry detected,  sf.get_refined_structure() does not work. As far as I understand, spglib is applying all operations to get all positions perfectly symmetric and return the conventional structure. For a non-collinear structure we need to do that for xyzt operations, which is not implemented in spglib. To be honest, I didn't grasp how spglibs refined_structure method works, when I looked at the code, so I am not sure how it can be extended to the xyzt case.
Then instead of '_symmetry_equiv_pos_as_xyz' -> '_space_group_symop_magn_operation.xyz' and '_space_group_symop_magn_centering.xyz' should be written, I think. '_space_group_symop_magn_operation.xyz' are simply the xyzt strings, but I am not sure how to go about the latter. '_space_group_symop_magn_centering.xyz' is the non-primitiv translation that leaves the structure invariant, right? How can I find them in an efficient way...

Another question I am trying to answer is how to get '_atom_site_moment.symmform' (based on the xyzt operations?). It seems to be an xyzt like string, but in terms of mx, my, mz.

I hope you are interested in some of my thoughts. Instead of working on my own little project, I would like to share what I am doing during my PhD. In the (very) long run, I am hoping to contribute a new ansatz, that we are currently perusing. But for now, I would be happy to contribute small functionalities that come in handy for my project and may benefit others.

**Comment by shyamd** [comment]
Can we just run this for everything and build some sort of dictionary to reference to decouple from Bilbao?

**Comment by mkhorton** [comment]
Quick update, I am going to be working with Guy Moore (grad student in our group) to try and write a native pymatgen MagneticSymmetryAnalyzer, we already have 90% of what we need I think.

@mt-huebsch In terms of your other questions above, I'll get back to these! Apologies to the delay.

**Comment by mkhorton** [comment]
Closing for now, happy to re-open later if more progress is made on this.

**Pull request closed without merging**
