### PR TITLE
Non-standard setting for magnetic spacegroup & Site property deserialization

### PR DESCRIPTION
**Pull request by guymoore13**
## Summary

* Added "Jones Faithful transformation" as an optional input for the MagneticSpaceGroup constructor, allowing the user to define the space-group in non-standard coordinates
* CIF file reader uses non-standard transformation in BNS setting as input to MagneticSpaceGroup constructor
* Fixed Monty deserialization of site properties using Matt Horton's suggestion

## Additional dependencies introduced (if any)

* Added dependency to json module in core/sites.py. This dependency was added in order to decode site properties. This dependency is modeled after core/structure.py.

## TODO (if any)

* At the moment, Jones Faithful transformation applies only to the MagSymmOp output of symmetry_ops() attribute of MagneticSpaceGroup. The transformation isn't applied to the operator "data" directly.

## Checklist

- [ ] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). 
      Run [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/) and [flake8](http://flake8.pycqa.org/en/latest/)
      on your local machine.
- [ ] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [ ] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) 
      to type check your code.
- [ ] Tests have been added for any new functionality or bug fixes.
- [ ] All existing tests pass.

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @guymoore13! One thing I noticed was missing is a test for the site property serialization fix. Doing a round-trip as_dict from_dict would probably be sufficient.

**Comment by guymoore13** [comment]
Sounds good @mkhorton, thank you for the tip!

**Comment by guymoore13** [comment]
@mkhorton should I add coordinate wrapping for all symmops? In other words, for translations I tried adding np.mod(x,1.0), where x is a translation component in fractional lattice coordinates. This appeared to work well but I want to check with you first. This mod() operation appears to map the following: x -> x+1.0 if x<0.0, and x -> x-1.0 if 1.0 <= x < 2.0.

**Comment by mkhorton** [comment]
Thanks @guymoore13 ! Yes, co-ordinate wrapping sounds sensible. Thanks for adding the missing module docstrings also. The `jf_in` keyword arg can probably be renamed to `setting_transformation` or something more descriptive (verbosity is fine).

If in doubt about something like `mod` you can always check the documentation, for the NumPy modulo that's [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mod.html). Otherwise this all looks good.

**Comment by mkhorton** [comment]
Great, thanks @guymoore13 ! Will merge once continuous integration tests pass.

Also, since this is your first pymatgen code addition, please make sure to add your name to [this form](https://forms.gle/JnisFb38QDR8QTFTA) so we can credit you appropriately in the [pymatgen docs](https://pymatgen.org/team.html).

**Comment by guymoore13** [comment]
Thank you @mkhorton! I just submitted the developer information form.

**Pull request merged**
