### PR TITLE
Extension ThermalDisplacementMatrices class

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

I have extended the ThermalDisplacementMatrices class. It can now also read cif files in P1 format, produce structures including Ucif as site_property (handy for sorting structures and thermal displacement properties, for example), and print VESTA files in P1 space group including vectors indicating the directionality of two different sets of computed displacement parameters.

While doing so, I have refactored the classes parsing the cif files a tiny bit. In general, I found it very hard to reuse any of the code in there as this warning state of the class would require me to make instances of classes. While I understand the purpose of saving the warnings like this, it has this drawback. Otherwise, most of the methods in there could be static methods.

### CODE REVIEW

**Comment by JaGeo** [comment]
Currently mypy is failing but I don't see a direct connection to my pull request. I would be very happy about any hint how to potentially solve this issue.

**Comment by JaGeo** [comment]
All linting errors are fixed now.

**Comment by janosh** [comment]
Thanks!

**Comment by JaGeo** [comment]
Thanks for merging and fixing the docu and comments, @janosh !
JG

**Comment by janosh** [comment]
We should probably automate doc style checking with `pre-commit` at some point.

**Pull request merged**
