### PR TITLE
Fix pdplotter.show with matplotlib backend

### PR DESCRIPTION
**Pull request by lbluque**
## Checklist

- [X] Google format doc strings added. Check with `ruff`.
- [X] Type annotations included. Check with `mypy`.
- [X] Tests added for new features/fixes.
- [X] If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/lattice.py#L1168-L1172))

Tip: Install `pre-commit` hooks to auto-check types and linting before every commit:

```sh
pip install -U pre-commit
pre-commit install
```

### CODE REVIEW

**Review by janosh — CHANGES_REQUESTED** [review]
Thanks @lbluque! 👍 

Can we change this method to return the `ax` (`fig` for plotly)? Don't see a reason not to return. And add a test for the return type?

**Comment by lbluque** [comment]
> Thanks @lbluque! 👍 
> 
> Can we change this method to return the `ax` (`fig` for plotly)? Don't see a reason not to return. And add a test for the return type?

That looks like the `get_plot` method already does. This method is to display the plot.

**Comment by janosh** [comment]
> That looks like the `get_plot` method already does.

I know but does it hurt to return anyway? I guess it could actually. I think in Jupyter if some code calls `plt.show()` and you don't assign the returned figure to a variable the cell will render the returned figure and so it would be shown twice? If that's the case then you're right and we shouldn't return.

**Review by janosh — APPROVED** [review]
I added a bunch more tests including ones that mock `PDPlotter.show()` in CI. This is good to go. 🎉

**Comment by lbluque** [comment]
Awesome thanks for adding the tests! lgtm

**Pull request merged**
