### PR TITLE
Sign flip

### PR DESCRIPTION
**Pull request by mhsiron**
Correcting sign in BaderAnalysis' get_charge_transfer method

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks @mhsiron !

**Comment by mkhorton** [comment]
Test will likely need to be updated also. What system did you verify this against?

**Comment by mhsiron** [comment]
For ZnTe

But currently running on 50 other materials, so maybe I’ll wait!

This is the charge transfer data for Bader vs. DDEC:


For DDEC - the raw output is simply the charge transfer, while for Bader, the raw output is the total amount of charge for the atom. It would be weird for both to have a sign flip?

Also here fields 0-3 in Zn, and 4-7 is Te. I think it would make more sense for Te to be the negative transfer since its more electronegative than Zn?

Martin

**Comment by mhsiron** [comment]
Actually - upon further investigation - I'm not entirely sure this is the right conclusion.

**Pull request closed without merging**
