### PR TITLE
BUG: force contiguous calling find_points_in_spheres

### PR DESCRIPTION
**Pull request by lbluque**
## Checklist

- [X] Google format doc strings added. Check with `ruff`.
- [X] Type annotations included. Check with `mypy`.
- [X] Tests added for new features/fixes.

Tip: Install `pre-commit` hooks to auto-check types and linting before every commit:

```sh
pip install -U pre-commit
pre-commit install
```

### CODE REVIEW

**Comment by shyuep** [comment]
Quick qn: what is the purpose of this? Speed up?

**Comment by lbluque** [comment]
Having the arrays contiguous makes it faster., which I had already added in the previous PR.

However, we noticed that when called internally by a structure where the lattice matrix or frac_coords had been changed in such a way (such as applying strain) that the arrays were not contiguous then the call to the cython function would raise errors.

**Comment by janosh** [comment]
@shyuep Just for context, this came up in https://github.com/CederGroupHub/chgnet/pull/39 where tests were failing with

```py
chgnet/graph/converter.py:142: in get_neighbors
    center_index, neighbor_index, image, distance = structure.get_neighbor_list(
/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pymatgen/core/structure.py:1533: in get_neighbor_list
    center_indices, points_indices, images, distances = find_points_in_spheres(
pymatgen/optimization/neighbors.pyx:49: in pymatgen.optimization.neighbors.find_points_in_spheres
    ???
stringsource:660: in View.MemoryView.memoryview_cwrapper
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   ValueError: ndarray is not C-contiguous
```

@lbluque Thanks for the really fast fix and unit test. 👍  Makes me sleep better every time we add a new test. 😄

**Comment by shyuep** [comment]
Thanks.

**Pull request merged**
