### PR TITLE
Fix `openbabel` import to unskip `MoleculeMatcherTest`

### LINKED ISSUE #3105: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
#### Description

[pymatgen/analysis/tests/test_molecule_matcher.py](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/analysis/tests/test_molecule_matcher.py) conditionally uses OBAlign from openbabel.  openbabel is accessed by 
```
import openbabel
```
and availability of OBAlign registered with
```
ob_align_missing = openbabel is None or "OBAlign" not in dir(openbabel)
```
But the special handling for OBAlign is redundant in this sense: openbabel has moved itself into its own submodule. The source for openbabel [`__init__.py`](https://github.com/openbabel/openbabel/blob/master/scripts/python/openbabel/__init__.py.in) 
warns
```
"import openbabel" is deprecated, instead use "from openbabel import openbabel"
```
and the openbabel [documentation](https://open-babel.readthedocs.io/en/latest/UseTheLibrary/PythonDoc.html) corroborates this usage. Indeed, with openbabel 3.1.1 this works, indicating that OBAlign is located at openbabel.openbabel.OBAlign, not openbabel.OBAlign

Hence MoleculeMatcherTest gets skipped unnecessarily, due to a missing `openbabel.OBAlign` when `openbabel.openbabel.OBAlign` is available.

So https://github.com/materialsproject/pymatgen/blob/6871dae21f245db8dafdf3767182ec7dc64f094a/pymatgen/analysis/tests/test_molecule_matcher.py#L24C21-L24C21 should be updated to replace
```
    import openbabel

```
with 
```
    from openbabel import openbabel
```
A more complex variant with a double try block could be used if older versions of openbabel need to be supported. But probably best to just require a "recent" openbabel ("recent" means openbabel 3, since [March 2019](https://github.com/openbabel/openbabel/pull/1946))

#### Repro

1. Install openbabel 3
2. Go to pymatgen source
3. `pytest-3 -v -k MoleculeMatcherTest  pymatgen/analysis/tests/test_molecule_matcher.py`
4. See if tests are skipped with `OBAlign is missing, Skipping`

#### Expected behavior

MoleculeMatcherTest (OBAlign) tests should be able to run on "modern" openbabel installations (as openbabel.openbabel.OBAlign)

#### Environment

Relevant versions and platform info:

- OS: Linux (debian unstable)
- pymatgen 2023.06.23
- openbabel 3.1.1

### PR DESCRIPTION
**Pull request by janosh**
Closes #3105.

### CODE REVIEW

**Comment by janosh** [comment]
@drew-parsons I fixed the `openbabel` import but I'm leaving out the openbabel install in CI which I also needed to get this test running again. Would you like to submit a PR for that?

**Comment by drew-parsons** [comment]
I'm not sure how to patch the github CI. I'm working with the debian CI testing at https://ci.debian.net/packages/p/pymatgen/. But I've applied the import patch and it's running the OBAlign tests fine.
e.g. https://ci.debian.net/data/autopkgtest/testing/amd64/p/pymatgen/34898502/log.gz shows
```
runtests/pymatgen/analysis/tests/test_molecule_matcher.py::MoleculeMatcherTest::test_cdi_23 PASSED [ 15%]
runtests/pymatgen/analysis/tests/test_molecule_matcher.py::MoleculeMatcherTest::test_get_rmsd PASSED [ 15%]
runtests/pymatgen/analysis/tests/test_molecule_matcher.py::MoleculeMatcherTest::test_group_molecules PASSED [ 15%]
runtests/pymatgen/analysis/tests/test_molecule_matcher.py::MoleculeMatcherTest::test_strange_inchi PASSED [ 15%]
runtests/pymatgen/analysis/tests/test_molecule_matcher.py::MoleculeMatcherTest::test_thiane PASSED [ 15%]
runtests/pymatgen/analysis/tests/test_molecule_matcher.py::MoleculeMatcherTest::test_thiane_ethynyl PASSED [ 16%]
runtests/pymatgen/analysis/tests/test_molecule_matcher.py::MoleculeMatcherTest::test_to_and_from_dict PASSED [ 16%]
```

(I configured it to skip `test_fit` since it was giving an error
```
>               ob_atom.SetVector(*coords)
E               TypeError: in method 'OBAtom_SetVector', argument 2 of type 'double'

/usr/lib/python3/dist-packages/pymatgen/io/babel.py:66: TypeError
```
I'm not yet confident enough on why it's doing that to file a separate bug)

**Comment by janosh** [comment]
[Based on this](https://gohom.win/2015/10/27/openbabel-py/), it looks like `ob_atom.SetVector` expects the first argument to be a vector.

```py
OBAtom.SetVector = new_instancemethod(_openbabel.OBAtom_SetVector, None, OBAtom)
```

If you remove the unpacking operator, does the test still fail?

```diff
- ob_atom.SetVector(*coords)
+ ob_atom.SetVector(coords)
```

**Comment by drew-parsons** [comment]
No, apparently not as simple as that. `ob_atom.SetVector(coords)` gets
```
>               ob_atom.SetVector(coords)
E               TypeError: in method 'OBAtom_SetVector', argument 2 of type 'OpenBabel::vector3 const &'
```

**Comment by janosh** [comment]
Not sure but I assume so.

**Pull request merged**
