### PR TITLE
Bandstructure bug fix and review of from_dict/as_dict

### PR DESCRIPTION
**Pull request by fraricci**
This bug fix should solve the problem in issue #1941,
Example: mp-15077
Problem: for some reason some bandstructures on symmetry line in the MP
database contain the bands as dict(array). The BandStructureSymmLine.from_dict()
cannot handle this format. It creates the object but then the other methods
(e.g. is_metal()) fail because they expect an array.

Solution:
The BandStructure.from_dict() actually can handle this case. 
So I took this opportunity to review the BandStructure.from_dict()/as_dict() 
and make them work for the subclass BandStructureSymmLine as well.
So those methods were removed from the subclass.

Tests are running fine, but I'd like to do some other using data from the database.
I tried to get the json file for the problematic cases from the rester without success. 
It seems there's a check of the data server side that fails (because there the bus is 
not fixed) and it does not allow the download. I get the usual error instead.

### CODE REVIEW

**Comment by mkhorton** [comment]
Many thanks @fraricci. For some context on the MPRester issue, some particularly large band structures fail due to a timeout on Cloudflare (which we cannot change). We use Cloudflare since it provides caching to reduce load on our servers and firewalls to prevent abuse. However, we're going to establish a second endpoint that bypasses Cloudflare for the purposes of these large files, but we need to purchase a new certificate first so this may take a week or so.

**Comment by fraricci** [comment]
Hey @mkhorton, is that related with the issue I'm trying to solve with this issue?

**Comment by mkhorton** [comment]
It is not, separate issue

**Comment by mkhorton** [comment]
To add additional information, large band structures that may take more than 30 seconds to pull or process will cause a gateway timeout error. So if you're seeing that, that's why.

**Comment by fraricci** [comment]
Hi @mkhorton, it seems that this issue is not solved yet.
Fetching bands for mp-867624 still returns the same error:
sbs = rester.get_bandstructure_by_material_id('mp-867624')
MPRestError: too many indices for array: array is 0-dimensional, but 2 were indexed.....

If I well remember, to solve this, the server-side version of pymatgen has to contain the patch implemented in this pull request.
Do you have any updates?
Thanks!

**Comment by mkhorton** [comment]
Hi @fraricci, this could simply be because the MP website is still running an older pymatgen (currently, it's `2020.8.13`). We have a release pending so we can update the version of pymatgen then. Note that we're spending most of our development effort on the new API and will be looking for beta testers soon, you might prefer to use that.

**Pull request merged**
