### PR TITLE
Add a CI run that only tests non-optional deps (optimistically)

### PR DESCRIPTION
**Pull request by ml-evs**
Hopefully all tests have been written in such a way that they will be skipped if the underlying required package is not found... this would hopefully catch issues like #3645 ahead of time (although better linting would do the same too and avoid the potential need to update tests to skip if packages are missing -- only the implementation code would need to include package guard).

This should be updated after #3645 is merged to see what's left: not sure if adding a whole additional test run is "worth it" for the maintainers here but it definitely shows up the issues presented and would also be robust to any weirdness with optional deps changing the values of expected tests. There might be some kind of pytest plugin that lets you re-run only the skipped tests in the previous step when considering all deps.

### CODE REVIEW

**Comment by janosh** [comment]
wow, that's way more possibly unbound variables than expected... 😅

**Comment by ml-evs** [comment]
@coderabbitai ignore

**Comment by janosh** [comment]
my impression is coderabbitai is too verbose. if it has useful suggestions, they are buried in a lot of boilerplate language that you don't want to read

**Comment by DanielYang59** [comment]
Here I come! Giving you a hand on all those `pyright` fixes. I wish you don't mind :)

**Comment by ml-evs** [comment]
Just to be clear I was never planning on making these fixes, I just wanted to show the issue by adding it to the CI. So feel free to close/take over/supersede this PR

**Comment by DanielYang59** [comment]
Thanks for the input. I could help fix them and I could either push my fixes to your branch or maybe open a separate PR  :) ? Which do you prefer?

**Comment by ml-evs** [comment]
Probably best to close this one and start again, the CI changes I suggested here are already out of date it seems. pyright was just being used to look for symptoms of the problem, the real change that needs to be made is running the test suite with optional deps only and making sure nothing fails.

**Comment by DanielYang59** [comment]
Thanks for clarifying. I would redirect the PR directly to upstream if you don't mind (wasn't planning to pre-empt you)?

**Comment by ml-evs** [comment]
I won't be doing anything further on this so please go ahead!

**Comment by DanielYang59** [comment]
Thanks!

**Pull request closed without merging**
