### PR TITLE
[WIP - Needs Test] add include magmom toggle to `SpacegroupAnalyzer` #2201

### PR DESCRIPTION
**Pull request by CompRhys**
re #2201 

add toggle on whether to include magmoms in spglib input in order to has equivalent sites correctly map to wyckoff positions without duplicates. 

- [ ] Tests added for checking correct Wyckoff position multiplicities

### CODE REVIEW

**Comment by CompRhys** [comment]
@mkhorton If I need to include a new data file for a test of a `Structure` with magmoms that behaves "weirdly" in the way outlined in #2201 what's the current best practise to storing those files within the codebase (#2197)? or this could be merged without an extra test as no bug as such is being fixed

**Comment by mkhorton** [comment]
A test would definitely be desired. There are three options, (1) pull a test structure from the test framework and add magmoms to it, (2) add a .json to test_files, (3) construct a Structure object within the test itself (either directly or via a minimal from_dict).

**Comment by CompRhys** [comment]
@mkhorton This is actually more of an issue than I initially thought and it's not as simple as adding a toggle to get the multiplicities right due to the way the code deals with the site properties. When I use the code as is the correct magmoms are passed to the analyzer and this causes wyckoff sites to be split up by spglib (which is what I wanted to avoid) however in the called to `get_symmetrised_structure` the code just accesses the magmoms as a list as stands and then miss-assigns them to elements (see below).

```
Full Formula (Al12 Cr4 O24)
Reduced Formula: Al3CrO6
abc   :   7.165227   7.166083   8.451375
angles: 113.162862 113.161083  85.839799
Sites (40)
  #  SP           a         b         c    magmom
---  ----  --------  --------  --------  --------
  0  Al    0.973155  0.473169  0.648738     0.002
  1  Al    0.473143  0.973159  0.648728    -0.002
  2  Al    0.223212  0.223202  0.148823     0.002
  3  Al    0.723181  0.723173  0.148783    -0.002
  4  Al    0.975235  0.975237  0.650128     0.001
  5  Al    0.47525   0.47523   0.650127    -0.001
  6  Al    0.225225  0.725244  0.150164    -0.001
  7  Al    0.725226  0.225237  0.150168     0.001
  8  Al    0.52897   0.028961  0.352616    -0
  9  Al    0.028977  0.528957  0.352623     0
 10  Al    0.779009  0.779016  0.852669    -0
 11  Al    0.279008  0.279024  0.852677     0
 12  Cr    0.52741   0.527402  0.35158     -2.949
 13  Cr    0.277385  0.77739   0.851557    -2.949
 14  Cr    0.027476  0.027493  0.351636     2.949
 15  Cr    0.777495  0.27745   0.851649     2.949
 16  O     0.044653  0.704117  0.594498     0.013
 17  O     0.544639  0.204079  0.594503    -0.013
 18  O     0.294562  0.454044  0.094441     0.013
 19  O     0.794545  0.954029  0.094434    -0.013
 20  O     0.780519  0.968294  0.747281    -0.013
 21  O     0.280508  0.468296  0.747287     0.013
 22  O     0.030439  0.718202  0.247303    -0.013
 23  O     0.530433  0.218227  0.247322     0.013
 24  O     0.798074  0.950804  0.406879    -0.013
 25  O     0.298077  0.450856  0.406914     0.013
 26  O     0.047946  0.700753  0.906898     0.013
 27  O     0.547857  0.20076   0.906931    -0.013
 28  O     0.729983  0.528205  0.244689     0.008
 29  O     0.229964  0.028174  0.244634    -0.008
 30  O     0.979915  0.27833   0.74455     -0.004
 31  O     0.479916  0.778318  0.744534     0.004
 32  O     0.709869  0.548396  0.607886     0.006
 33  O     0.20987   0.048404  0.607914    -0.006
 34  O     0.959754  0.298432  0.107708    -0.007
 35  O     0.459708  0.798444  0.107638     0.007
 36  O     0.447642  0.810549  0.405891     0.007
 37  O     0.947641  0.310582  0.405913    -0.007
 38  O     0.697657  0.560783  0.906042    -0.004
 39  O     0.197676  0.060776  0.906051     0.004
```

```
Full Formula (Al12 Cr4 O24)
Reduced Formula: Al3CrO6
Spacegroup: R3 (146)
abc   :   7.165227   7.166083   8.451375
angles: 113.162862 113.161083  85.839799
Sites (40)
  #  SP           a         b         c  Wyckoff      magmom
---  ----  --------  --------  --------  ---------  --------
  0  Al    0.973155  0.473169  0.648738  4a            0.002
  1  Al    0.975235  0.975237  0.650128  4a           -0.002
  2  Al    0.52897   0.028961  0.352616  4a            0.002
  3  Cr    0.52741   0.527402  0.35158   4a           -0.002
  4  O     0.044653  0.704117  0.594498  4b            0.001
  5  O     0.780519  0.968294  0.747281  4b           -0.001
  6  O     0.798074  0.950804  0.406879  4b           -0.001
  7  O     0.729983  0.528205  0.244689  4b            0.001
  8  O     0.709869  0.548396  0.607886  4b           -0
  9  O     0.447642  0.810549  0.405891  4b            0
```

**Comment by CompRhys** [comment]
closing this PR but leaving #2201 open as this fix doesn't actually do what we need it to do for robustness in the sense I wanted.

**Pull request closed without merging**
