### PR TITLE
[WIP] Implemenation  of a robust permutation invariant molecule matcher

### PR DESCRIPTION
**Pull request by fekad**
## Summary

The main goal to implement a robust matching method between molecules. This implementation is based on [Kabsch algorithm]( https://en.m.wikipedia.org/wiki/Kabsch_algorithm) and on an excellent python package called [rmsd](https://github.com/charnley/rmsd). The code has been basically rewritten from scratch and adapted to pymatgen. Also, some small bugs in the referred solution have been fixed.

There are three new methods available:
* `KabschMatcher`: this methods works when the order of the atoms is the same in the two structures. Returns with the optimal rotation and translation which belong to the minimal distance between the molecules.
* `BruteForceOrderMatcher`: This method compares all the possible permutations and it also returns with the optimal order of atoms. Works perfectly with small molecules but not feasible larger systems due to it's factorial complexity.
* `HungarianOrderMatcher`: This method tries to identify the atom pairs by aligning the molecules based on their principle axis and sorted by the (Hungarian algorithm)[https://en.m.wikipedia.org/wiki/Hungarian_algorithm]. Please note that it is not guaranteed that this method always returns with the "best" solution. 
* (NEW) `GeneticOrderMatcher`: This method was inspired by genetic algorithms and tries to match molecules based on their already matched fragments.

Key features:
* A new method to match  `p` onto `q`  molecule
* Returns with the rotation matrix, translation vector,  proper order of atoms (in case of permutation invariant method) and root-mean-square deviation. 
* The implementation is pure python and it is completely independent of `openbabel`.
* closing: #1935 

## TODO/Checklist

Work-in-progress pull requests are encouraged, but please put [WIP]
in the pull request title.

Before a pull request can be merged, the following items must be checked:

- [x] Creating a common interface for the `match` and `fit` methods
- [x] Refactoring the code to have a more object-oriented code 
- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). 
      Run [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/) and [flake8](http://flake8.pycqa.org/en/latest/)
      on your local machine.
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) 
      to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [x] All existing tests pass.

Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is
highly recommended that you use the pre-commit hook provided in the pymatgen 
repository. Simply `cp pre-commit .git/hooks` and a check will be run prior to
allowing commits.

### CODE REVIEW

**Comment by fekad** [comment]
@mkhorton Do any of you have experience / best practice to use random numbers for testing? I was trying to use seed method and also creating a random generator object with a specific seed value but it doesn't seem to work...

Obviously, I can just use some predetermined random numbers for testing, but in theory, using random generators with seed method should give the same results and you can easily do more test if you want ...

**Comment by mkhorton** [comment]
@fekad I haven't had to do this previously, but using `seed` should work to create a deterministic random number generator, both via the in-built `random` library and `np.random`. I see you're initializing an rng object in some of your kwargs, perhaps that's responsible?

As an FYI, we don't currently use this in pymatgen but [hypothesis](https://hypothesis.readthedocs.io/en/latest/) is a nice library for creating unit tests that incorporates random data (following a specific requirement) as the test input, and asserts something about the output.

**Comment by fekad** [comment]
@mkhorton The initialization of the rng object was not an issue because every time I explicitly constructed one and passed that one to the function.

I also tried to use the - old-fashion - seed method but the result is the same...
I use multiple macs without any issue but It looks like the seed methods are not cross-platform yet.

In conclusion, I will use pre-generated structures for the tests unless somebody has a better solution.

**Comment by mkhorton** [comment]
Hi @fekad, my apologies for the delay in reviewing this, I will try to review this week. From your end, do you consider this PR ready to merge?

Looking at the test failures, I'm seeing a minor linter failure, but also some perhaps more serious test failures:

```
FAILED pymatgen/analysis/tests/test_molecule_matcher.py::KabschMatcherSiTest::test_perturbed_atom_position
129
FAILED pymatgen/analysis/tests/test_molecule_matcher.py::HungarianOrderMatcherSiTest::test_perturbed_atom_position
130
FAILED pymatgen/analysis/tests/test_molecule_matcher.py::GeneticOrderMatcherSiTest::test_all
131
FAILED pymatgen/analysis/tests/test_molecule_matcher.py::GeneticOrderMatcherSiTest::test_perturbed_atom_position
```

These are all of the form:

```
E       AssertionError: 0.2680448948923893 != 0.2628450748567651 within 8 places
77
```

It's possible these tests just need to be updated for the new method.

**Comment by fekad** [comment]
@mkhorton No worries. I didn't fix the tests yet but I will do in the next days.

**Comment by fekad** [comment]
@mkhorton From my side, this PR is ready for review. Please let me know if something is not understandable or if you have better names for the classes :)

**Comment by mkhorton** [comment]
This is a really substantial contribution and nicely tested, thank you! Class names look good to me. Please make sure to include your details in [this form](https://forms.gle/JnisFb38QDR8QTFTA) so that you can be credited appropriately in the [pymatgen documentation](https://pymatgen.org/team.html) too.

**Comment by kavanase** [comment]
Just noting here that I'm now using some of these classes in my research and they are extremely useful. Thanks @fekad !

**Pull request merged**
