### PR TITLE
[WIP] Edge Case of VoronoiNN() not finding neighbours when called by StructureGraph.with_local_env_strategy()

### PR DESCRIPTION
**Pull request by CompRhys**
## Summary
This PR is related to #1825 and aims to track down the source of the bug.

### Code
```
from pymatgen.core.structure import Structure
from pymatgen.analysis import local_env
from pymatgen.analysis.graphs import StructureGraph

with open("breaking-oqmd-4866.txt", 'r') as file:
    str_ = file.read()
    crystal = Structure.from_str(str_, fmt="json")

print(crystal)
StructureGraph.with_local_env_strategy(crystal, local_env.VoronoiNN())

```
### Input File
[breaking-oqmd-4866.txt](https://github.com/materialsproject/pymatgen/files/4474164/breaking-oqmd-4866.txt)

### CODE REVIEW

**Comment by CompRhys** [comment]
### Fails
```
StructureGraph.with_local_env_strategy(crystal, local_env.VoronoiNN(cutoff=8.0778))
print("baz - finds all polyhedra from StructureGraph")
```

### "Works"
```
StructureGraph.with_local_env_strategy(crystal, local_env.VoronoiNN(cutoff=8.0777))
print("baz - finds all polyhedra from StructureGraph")
```

with the caveat that when I try and see whether it's returned the correct graph by running 
```
foo = StructureGraph.with_local_env_strategy(crystal, local_env.VoronoiNN(cutoff=8.0777))
foo.draw_graph_to_file("test.png")
```
I get the following error:
```
Traceback (most recent call last):
  File "/home/reag2/PhD/second-year/pymatgen/break-test.py", line 19, in <module>
    foo.draw_graph_to_file("test.png")
  File "/home/reag2/PhD/second-year/pymatgen/pymatgen/analysis/graphs.py", line 913, in draw_graph_to_file
    write_dot(g, basename + ".dot")
  File "/home/reag2/anaconda3/lib/python3.7/site-packages/networkx/drawing/nx_agraph.py", line 194, in write_dot
    A.clear()
  File "/home/reag2/anaconda3/lib/python3.7/site-packages/pygraphviz/agraph.py", line 951, in clear
    self.remove_edges_from(self.edges())
  File "/home/reag2/anaconda3/lib/python3.7/site-packages/pygraphviz/agraph.py", line 573, in edges
    return list(self.edges_iter(nbunch=nbunch, keys=keys))
  File "/home/reag2/anaconda3/lib/python3.7/site-packages/pygraphviz/agraph.py", line 734, in edges_iter
    for e in self.out_edges_iter(keys=keys):
RuntimeError: generator raised StopIteration
```

The cut-off distance of 8.0777 doesn't appear to have any obvious significance for this structure. I haven't found an upper bound for the cut-off that works

**Comment by CompRhys** [comment]
The above can be traced to calls to 

```
foo = local_env.VoronoiNN(cutoff=8.0778).get_all_voronoi_polyhedra(crystal)
bar = local_env.VoronoiNN(cutoff=8.0777).get_all_voronoi_polyhedra(crystal)
```

The first returns empty neighbour dictionaries for the 14/15th entries whilst the second provides a full (not confirmed correct) output

**Comment by CompRhys** [comment]
The issue appears to stem from converting to primitive structures before calling `VoronoiNN()`. As such it is not apparent as of yet what exactly is going wrong. Despite not fixing the issue I suggest that adding this ValueError checking if no Voronoi neighbours are found for a given site is much more transparent as to what the issue is than `ValueError: max() arg is an empty sequence` which was the error previously raised.

**Comment by mkhorton** [comment]
Thanks @CompRhys for the tip about primitive cells, I'll leave the issue open. Next time we have someone using Voronoi extensively I'll ask them to help track down the underlying issue

**Comment by CompRhys** [comment]
I opened an issue on Scipy about implementing a periodic Voronoi so if that goes ahead it would be worth baring in mind for updating the `get_all_voronoi_polyhedra()` function

**Comment by mkhorton** [comment]
That'd be cool! I think they use Qhull under the hood, so it might depend on what Qhull itself supports. Perhaps they'd be willing to add a wrapper though.

**Pull request merged**
