### PR TITLE
Fix Vasprun not interpreting float overflow as nan

### PR DESCRIPTION
**Pull request by tawe141**
VASP will sometimes print "***********" when there's a float overflow. There's already a function in here to interpret these as `np.nan`, but it looks like it wasn't applied everywhere. I found one place where it wasn't used (ie just using Python's `float` function) that helped me process a large batch of `vasprun.xml`s correctly, but maybe the same function can be used elsewhere.

### CODE REVIEW

**Comment by Andrew-S-Rosen** [comment]
Good to see you around these parts, @tawe141!!!

**Review by janosh — CHANGES_REQUESTED** [review]
Thanks @tawe141! This should go along with a new test that applies `_parse_calculation` to a file containing a VASP overflow.

**Comment by tawe141** [comment]
Added test and confirmed it passes on my end!

**Review by janosh — APPROVED** [review]
Thanks a lot for fixing @tawe141! 👍

**Pull request merged**
