### PR TITLE
Allow for float ENCUTs in Wavecar class

### PR DESCRIPTION
**Pull request by arosen93**
Addresses #2361. 

As noted by @RyanNKHall, the `Wavecar` class requires that ENCUT be an `int` when strictly speaking, this is not necessary within VASP. This PR implements the change suggested by @RyanNKHall to read ENCUT as a `float`. 

If a test is requested, I can run a super cheap H2 calc, although I'm not sure it's necessary for this one. The change I made to the test is only a cosmetic change for the reader.

### CODE REVIEW

**Comment by mkhorton** [comment]
Many thanks for addressing this issue @arosen93, this looks good.

On a technical note, I don't think this can be classed as a cosmetic change -- the return type is changing, this will have downstream consequences for anyone using the pymatgen parser (eg to store results in a database). However, I can't anticipate a case where this would cause issues so happy to merge.

**Comment by arosen93** [comment]
@mkhorton, apologies! I wasn't clear in my original response. I meant the change to the test file I made is a cosmetic change. You're right about the change in return behavior.

**Comment by mkhorton** [comment]
Actually, the one test case that may be useful is a test case that reproduces @RyanNKHall's original bug report, so we can confirm it's fixed

**Comment by arosen93** [comment]
Sure, I can run a quick calculation on H2 with an encut of like 25.5. I want to keep the filesize small.

**Comment by mkhorton** [comment]
Thanks, I appreciate the concern about filesize. We do have a few wavecar in the test_files dir, so not unprecedented, but definitely good to keep to minimum.

**Comment by RyanNKHall** [comment]
Thanks @arosen93 for the mention here. I'm surprised and pleased to see someone else encountering the same issue within the same period of time. Let me know if you need/require any of my original files to replicate and/or test the bug and associated fix. I believe, however, that everything I provided in the original bug report should suffice.

**Comment by arosen93** [comment]
@RyanNKHall, I opened this PR because of your issue! :) I wanted to make sure it got fixed in future version of pymatgen. Of course, if you want to do the PR, you can by all means do so! Otherwise, I'll finish this up in the next day or two. Thanks for reporting!

**Comment by RyanNKHall** [comment]
@arosen93 I'm more than happy for you to make the PR :) Thanks for your help.

**Comment by arosen93** [comment]
I managed to make a 5 kb WAVECAR file. A teeny-tiny one! Not sure what `pip install` is complaining about though.

**Comment by arosen93** [comment]
Sorry, I was battling the pre-commit CI there for a little bit. Hopefully should be sorted out now.

**Comment by arosen93** [comment]
@mkhorton, just a reminder that this one is done.

**Comment by mkhorton** [comment]
Thanks @arosen93 :)

**Pull request merged**
