### PR TITLE
Fix `typing_extension` `ImportError` in downstream packages

### LINKED ISSUE #3751: `typing_extension` imported at run time causing ImportError
Hi! Thanks for your work on `pymatgen`! 😃 
Just to flag, this update seems to be causing some failures on our GitHub Actions tests (for [`ShakeNBreak`](https://shakenbreak.readthedocs.io/en/latest/) and [`doped`](https://doped.readthedocs.io/en/latest/)) with the latest `pymatgen` version. I'm not sure if it just needs `typing_extensions` to be added to the requirements?

```
Run pytest -vv -m "not mpl_image_compare" tests  # all non-plotting tests
============================= test session starts ==============================
platform linux -- Python 3.11.9, pytest-8.1.1, pluggy-1.4.0 -- /opt/hostedtoolcache/Python/3.11.9/x64/bin/python
cachedir: .pytest_cache
Matplotlib: 3.8.4
Freetype: 2.6.1
rootdir: /home/runner/work/ShakeNBreak/ShakeNBreak
configfile: pyproject.toml
plugins: mpl-0.1[7](https://github.com/SMTG-Bham/ShakeNBreak/actions/runs/8663869495/job/23758934155#step:6:8).0
collecting ... collected 121 items / 1 error / 29 deselected / 92 selected

==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_analysis.py ____________________
ImportError while importing test module '/home/runner/work/ShakeNBreak/ShakeNBreak/tests/test_analysis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/python.py:520: in importtestmodule
    mod = import_path(
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/_pytest/pathlib.py:5[8](https://github.com/SMTG-Bham/ShakeNBreak/actions/runs/8663869495/job/23758934155#step:6:9)4: in import_path
    importlib.import_module(module_name)
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1204: in _gcd_import
    ???
<frozen importlib._bootstrap>:1176: in _find_and_load
    ???
<frozen importlib._bootstrap>:1147: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:6[9](https://github.com/SMTG-Bham/ShakeNBreak/actions/runs/8663869495/job/23758934155#step:6:10)0: in _load_unlocked
    ???
/opt/hostedtoolcache/Python/3.[11](https://github.com/SMTG-Bham/ShakeNBreak/actions/runs/8663869495/job/23758934155#step:6:12).9/x64/lib/python3.11/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests/test_analysis.py:[14](https://github.com/SMTG-Bham/ShakeNBreak/actions/runs/8663869495/job/23758934155#step:6:15): in <module>
    from shakenbreak import analysis
shakenbreak/analysis.py:23: in <module>
    from shakenbreak import input, io
shakenbreak/input.py:30: in <module>
    from doped.generation import DefectsGenerator, name_defect_entries
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/doped/generation.py:32: in <module>
    from pymatgen.transformations.advanced_transformations import CubicSupercellTransformation
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pymatgen/transformations/advanced_transformations.py:36: in <module>
    from pymatgen.transformations.standard_transformations import (
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pymatgen/transformations/standard_transformations.py:[17](https://github.com/SMTG-Bham/ShakeNBreak/actions/runs/8663869495/job/23758934155#step:6:18): in <module>
    from pymatgen.analysis.elasticity.strain import Deformation
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pymatgen/analysis/elasticity/__init__.py:5: in <module>
    from .elastic import (
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pymatgen/analysis/elasticity/elastic.py:21: in <module>
    from pymatgen.analysis.elasticity.stress import Stress
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pymatgen/analysis/elasticity/stress.py:11: in <module>
    from typing_extensions import Self
E   ModuleNotFoundError: No module named 'typing_extensions'
```

_Originally posted by @kavanase in https://github.com/materialsproject/pymatgen/issues/3705#issuecomment-2051980163_

### PR DESCRIPTION
**Pull request by janosh**
closes #3751

## Summary by CodeRabbit

- **Refactor**
	- Improved code readability by consolidating imports in core modules.
	- Enhanced type hinting and conditional type checking across various modules.

- **Tests**
	- Updated test functions with specific error messages for better clarity.

- **Chores**
	- Updated revision of pre-commit hooks to ensure code quality.

### CODE REVIEW

**Comment by kavanase** [comment]
Hi @janosh @DanielYang59 !
Sorry to be the bearer of bad news, but this issue has cropped up again in the recent release of `pymatgen`, which again is causing failures in our CI for `doped`/`ShakeNBreak` (and I imagine other downstream packages of `pymatgen`).
(https://github.com/SMTG-Bham/ShakeNBreak/actions/runs/9323684325/job/25667402879, https://github.com/SMTG-Bham/doped/actions/runs/9323686497).

The issue is that `typing_extensions` is now imported before the `TYPE_CHECKING` block in `pymatgen.core.structure`, added in this commit: https://github.com/materialsproject/pymatgen/commit/d0ad785f9b4e9a57717ef2c56eef19ceb8e90c25
As far as I can tell, it's correctly imported in the `TYPE_CHECKING` block in all other usages, but might be worth a quick check.

**Comment by janosh** [comment]
sorry for the trouble!

we'll get a fix in asap ofc but really we need to setup CI that only installs non-optional deps so we catch these mistakes in the future.

**Comment by kavanase** [comment]
Also minor issue that doesn't really matter but might be useful to know about, `pymatgen.core.periodic_table` uses the `monty.dev` `@deprecated()` decorator with the `deadline` keyword argument, but this was only added by @DanielYang59 in v`2024.3.31` of `monty`, but this isn't a version requirement of `pymatgen`, so when I updated to the new `pymatgen` it was throwing `top_level_collect` error messages about this until I upgrade `monty`. 
So probably worth adding `monty>=2024.3.31` to the dependencies!

**Comment by janosh** [comment]
that should be easy to prevent in future since we use `uv` which offers [`--resolution=lowest`](https://astral.sh/blog/uv) to install the oldest allowed versions of all packages

**Comment by DanielYang59** [comment]
Sorry for the trouble, again. And I really want some automated import guard to guard against `TYPE_CHECKING` only imports #3827, which would prevent such issues.

> Also minor issue that doesn't really matter but might be useful to know about, `pymatgen.core.periodic_table` uses the `monty.dev` `@deprecated()` decorator with the `deadline` keyword argument, but this was only added by @DanielYang59 in v`2024.3.31` of `monty`, but this isn't a version requirement of `pymatgen`, so when I updated to the new `pymatgen` it was throwing `top_level_collect` error messages about this until I upgrade `monty`. So probably worth adding `monty>=2024.3.31` to the dependencies!

Looks like I forgot to update the minimum `monty` version in `setup.py`: https://github.com/materialsproject/pymatgen/blob/2982968a44d0ff65392057488aee4871210bc847/setup.py#L30-L32

I updated the `monty` version in `requirements.txt` alone: https://github.com/materialsproject/pymatgen/blob/2982968a44d0ff65392057488aee4871210bc847/requirements.txt#L4

Perhaps we should [reuse `requirements.txt` in `setup.py` ](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py) instead of having duplicates? Maybe there are reasons that I'm not aware of?

**Comment by janosh** [comment]
> Perhaps we should [reuse requirements.txt in setup.py ](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py)instead of having duplicates? Maybe there are reasons that I'm not aware of?

better yet, get rid of `requirements.txt` as i've been saying for years. no good reasons for keeping it imo

**Comment by JaGeo** [comment]
I would also be pro removing. Would it actually make sense to have a pymatgen[strict] similar to atomate2[strict] to have exact version numbers of all packages as well?

**Pull request merged**
