### PR TITLE
Fix KSPACING formula in MPScanRelaxSet

### PR DESCRIPTION
**Pull request by ab5424**
## Summary

Change rmin formula to match Eq. 25 from the paper.

### CODE REVIEW

**Comment by mkhorton** [comment]
FYI @rkingsbury

**Comment by mkhorton** [comment]
Thanks for the catch @ab5424

**Comment by rkingsbury** [comment]
Thanks for catching @ab5424 . @mkhorton I can confirm; I looked at the paper and the workflow again. The difference in KSPACING appears to be small, and the previous (incorrect) equation would have resulted in a tighter / more stringent KSPACING value than the one that will be computed now.

**Comment by mkhorton** [comment]
Great, will merge. Thanks both!

**Pull request merged**
