### PR TITLE
added explicit polar decomposition method to allow for more flexible …

### PR DESCRIPTION
**Pull request by montoyjh**
…scipy compatibility

### CODE REVIEW

**Comment by shyuep** [comment]
Hmm... not quite sure why we need to implement an explicity polar decompositno method?

**Comment by montoyjh** [comment]
We were having an issue with the scipy dependency, since the polar method was implemented in sciyp/0.14.0 and some folks seem to be using older versions.  Since it was the only scipy dependency in analysis.elasticity, I made it explicit to remove the scipy dependency but keep the method, but an alternative would be to just remove the method, since scipy.linalg.polar can be used with the object anyway.

**Comment by shyuep** [comment]
0.14.0 is ancient. I think the folks should upgrade. pymatgen's requirements.txt already stipulates scipy 0.16.0. So there really isn;t a reason for < 0.14.0.

**Comment by montoyjh** [comment]
Ah, I thought scipy was optional.  Probably just leave it, then.

**Pull request closed without merging**
