### PR TITLE
Add support for spin-dependent eig band props

### PR DESCRIPTION
**Pull request by arosen93**
## Summary

PR to address #2185 (please refer to this Issue for additional context). This PR allows for the band gap, CBM, VBM, and is_direct_band_gap to be computed for each individual spin channel in a spin-polarized calculation when using the VASP Eigenval or Vasprun parsers via a new `separate_spins` keyword argument. Test cases are also included.

As an example, one can run:
```python
from pymatgen.io.vasp.outputs import Eigenval
eig = Eigenval('EIGENVAL', separate_spins=True)
bg = eig.eigenvalue_band_properties[0]
print(bg)
```
which would print out a list of length two where index 0 and index 1 are the band gaps for the up- and down-spin channels, respectively. Analogous behavior would occur if the Vasprun parser were used.

## TODO (if any)

~Setting `separate_spins=True` should raise an error if the calculation is not spin-polarized (i.e. if ISPIN != 2). I have done this already for the Eigenval class (as shown [here](https://github.com/materialsproject/pymatgen/blob/42156a757ad9a52cd28d42005f4c02c6289e6286/pymatgen/io/vasp/outputs.py#L5276)) but wasn't sure the best way to introduce this for the Vasprun and BSVasprun classes.~

**Any suggestions?**

### CODE REVIEW

**Comment by mkhorton** [comment]
Thanks for this PR @arosen93, it looks like a good addition to me.

Note there's possibly a more serious logic bug in the current `eigenvalue_band_properties` in that I believe it's broken on metals, in that it will give a very small but non-zero gap.

**Comment by arosen93** [comment]
@mkhorton -- thanks for the head's up. I think I may have observed similar behavior before.

I think the PR is pretty much done. I am going to use it for a day or so more to make sure nothing unexpected pops up. I'll reach out here once I'm done with that.

Regarding the TODO I mentioned, do you know the best way for me to check if ISPIN = 2 in the Vasprun and BSVasprun classes so I can raise an error if it's not equal to 2 but `separate_spins` is called?

**Comment by arosen93** [comment]
Okay, @mkhorton -- I'm feeling good about this one whenever you wish to proceed with the PR.

**Comment by mkhorton** [comment]
Thanks for adding this! Have merged.

While reviewing, I noticed we have two copies of this implementation (one for `Vasprun`, one for `Eigenval`), I'm not sure if we should simplify this at some point to have a common implementation.

**Pull request merged**
