### PR TITLE
Accounting for FHI-aims species' defaults 

### PR DESCRIPTION
**Pull request by ansobolev**
## Summary

This PR adds new SpeciesDefaults object to account for files with the default definitions of species-related keywords (integration grids, basis sets...) in FHI-aims, named _species' defaults_. This is done to abstract away the work with species' defaults from the `AimsControlIn` object, to bring the API more in line with VASP, and to enable running heterogeneous calculations that need different precision levels for different atoms.  

Major changes:

- An `AimsSpeciesFile` class representing the defaults for one species is introduced
- A `SpeciesDefaults` class representing a list of species' defaults is introduced; the `AimsControlIn` class now uses `SpeciesDefault`
- An `AIMS_SPECIES_DIR` configuration variable is introduced which should point to the root of `FHIaims/species_defaults` directory
-  Breaking change: the possibility to use default species' defaults directory is removed. Every input sets need explicit definition of the species' defaults directory relative to `FHIaims/species_defaults` or `FHIaims/species_defaults/defaults_2020`. 

## Todos

None

## Checklist

- [x] Google format doc strings added. Check with `ruff`.
- [x] Type annotations included. Check with `mypy`.
- [x] Tests added for new features/fixes.
- [ ] If applicable, new classes/functions/modules have [`duecredit`](https://github.com/duecredit/duecredit) `@due.dcite` decorators to reference relevant papers by DOI ([example](https://github.com/materialsproject/pymatgen/blob/91dbe6ee9ed01d781a9388bf147648e20c6d58e0/pymatgen/core/lattice.py#L1168-L1172))

### CODE REVIEW

**Comment by tpurcell90** [comment]
Would it be possible to reintroduce the default `species_dir` behavior? For some people using only one set of defaults is relatively okay

**Comment by tpurcell90** [comment]
otherwise this looks good from an fhi-aims perspective. This will break atomate2 tests but we can fix that once it is merged

**Comment by ansobolev** [comment]
> Would it be possible to reintroduce the default `species_dir` behavior? For some people using only one set of defaults is relatively okay

Yeah, it could be possible (just remove one check and add `species_dir` to `paths_to_try`, I guess), but based on my discussions over here people also want to freely change the defaults, and they don't like writing out the full path every time.

**Comment by tpurcell90** [comment]
Okay that makes sense

**Comment by ansobolev** [comment]
Hi, is there anything that should be done here?

**Comment by JaGeo** [comment]
@ansobolev Thanks for contributing in any case! I alao hope one of the maintainers will soon have some time! 😃

**Comment by shyuep** [comment]
Thanks for the contribution. I have merged it!

**Pull request merged**
