### PR TITLE
QA

### PR DESCRIPTION
**Pull request by janosh**
Since `pymatgen` is now py38+, can get rid of conditional `typing.Literal` imports.

Also, brings `.pre-commit-config.yaml` up to date and adds `pyupgrade` commit hook.

### CODE REVIEW

**Comment by janosh** [comment]
@shyuep There's one error here that says to contact you about changes to an input set. In this case just a whitespace change.

```py
=================================== FAILURES ===================================
_____________________ SetChangeCheckTest.test_sets_changed _____________________

self = <vasp.tests.test_sets.SetChangeCheckTest testMethod=test_sets_changed>

    def test_sets_changed(self):
        # WARNING!
        # These tests will fail when you change an input set.
        # They are included as a sanity check: if you want to change
        # an input set, please make sure to notify the users for that set.
        # For sets starting with "MVL" this is @shyuep, for sets starting
        # with "MP" this is @shyuep and @mkhorton.
        os.chdir(MODULE_DIR / "..")
        input_sets = glob.glob("*.yaml")
        hashes = {}
        for input_set in input_sets:
            with open(input_set) as f:
                hashes[input_set] = hashlib.sha1(f.read().encode("utf-8")).hexdigest()
        known_hashes = {
            "MVLGWSet.yaml": "f4df9516cf7dd923b37281172c662a70fa32bebc",
            "MVLRelax52Set.yaml": "eb538ffb45c0cd13f13df48afc1e71c44d2e34b2",
            "MPHSERelaxSet.yaml": "2bb969e64b57ff049077c8ec10e64f94c9c97f42",
            "VASPIncarBase.yaml": "19762515f8deefb970f2968fca48a0d67f7964d4",
            "MPSCANRelaxSet.yaml": "dfa9fee19178cb38c6a121ce6096db40693478e8",
            "MPRelaxSet.yaml": "4ea97d776fbdc7e168036f73e9176012a56c0a45",
            "MITRelaxSet.yaml": "1a0970f8cad9417ec810f7ab349dc854eaa67010",
            "vdW_parameters.yaml": "66541f58b221c8966109156f4f651b2ca8aa76da",
        }
    
>       self.assertDictEqual(
            hashes,
            known_hashes,
            "These tests will fail when you change an input set. "
            "They are included as a sanity check: if you want to "
            "change an input set, please make sure to notify the "
            "users for that set. "
            'For sets starting with "MVL" this is @shyuep, '
            'for sets starting with "MP" this is @shyuep and @mkhorton.',
        )
E       AssertionError: {'MITRelaxSet.yaml': '1a0970f8cad9417ec810f7[471 chars]4d4'} != {'MVLGWSet.yaml': 'f4df9516cf7dd923b37281172[471 chars]6da'}
E         {'MITRelaxSet.yaml': '1a0970f8cad9417ec810f7ab349dc854eaa67010',
E          'MPHSERelaxSet.yaml': '2bb969e64b57ff049077c8ec10e64f94c9c97f42',
E          'MPRelaxSet.yaml': '4ea97d776fbdc7e168036f73e9176012a56c0a45',
E          'MPSCANRelaxSet.yaml': 'dfa9fee19178cb38c6a121ce6096db40693478e8',
E          'MVLGWSet.yaml': 'f4df9516cf7dd923b37281172c662a70fa32bebc',
E          'MVLRelax52Set.yaml': 'eb538ffb45c0cd13f13df48afc1e71c44d2e34b2',
E          'VASPIncarBase.yaml': '19762515f8deefb970f2968fca48a0d67f7964d4',
E       -  'vdW_parameters.yaml': '04bb09bb563d159565bcceac6a11e8bdf0152b79'}
E       +  'vdW_parameters.yaml': '66541f58b221c8966109156f4f651b2ca8aa76da'} : These tests will fail when you change an input set. They are included as a sanity check: if you want to change an input set, please make sure to notify the users for that set. For sets starting with "MVL" this is @shyuep, for sets starting with "MP" this is @shyuep and @mkhorton.

/home/runner/work/pymatgen/pymatgen/pymatgen/io/vasp/tests/test_sets.py:84: AssertionError
```

**Comment by shyuep** [comment]
Thanks. Pls update the hashes so that the tests pass. @mkhorton Pls review.

**Comment by CompRhys** [comment]
Will probably break using most recent versions on Google colab which is stuck on 3.7.12

**Comment by shyuep** [comment]
People using Google collab can use older versions.

**Comment by janosh** [comment]
@CompRhys `pip`/`conda` won't even try to install the latest `pymatgen` on Colab since @shyuep bumped `python_requires` to 3.8 in https://github.com/materialsproject/pymatgen/commit/d00945491e9b53548ea8a6755a002c2066ad0ac9 2 weeks ago. Not until Google updates their runtime.

**Comment by CompRhys** [comment]
@janosh is right the most recent version already throws errors on google colab so my point doesn't really have bearing on this PR. I thought it would still work but I just hadn't merged recent changes onto my branch that I use with my colab workflow.

**Comment by janosh** [comment]
@shyuep What was the reason for dropping py37? I'd assumed it had something to do with `numpy` but that doesn't appear to be the case.

**Comment by shyuep** [comment]
Numpy 1.22 dropped py37.

**Comment by shyuep** [comment]
Thanks.

**Pull request merged**
