### PR TITLE
Integrate `mp-api.client.MPRester` into `pymatgen.ext.matproj`

### PR DESCRIPTION
**Pull request by munrojm**
## Summary

- `mp-api` made an explicit dependency 
- `MPRester` now detects the API key type (new or legacy) and instantiates the appropriate version of `MPRester` 

## Additional dependencies introduced (if any)

`msgpack` is the only additional dependency added to enable BS and DOS data retrieval with the new API.

## TODO (if any)

Finalize clean up of `mp-api` dependencies and client code (https://github.com/materialsproject/api/pull/666) before merging.

## Checklist

Work-in-progress pull requests are encouraged, but please put [WIP]
in the pull request title.

Before a pull request can be merged, the following items must be checked:

- [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/). The easiest way to handle this
      is to run the following in the **correct sequence** on your local machine. Start with running
      [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will automatically reformat
      your code to PEP8 conventions and removes most issues. Then run
      [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/), followed by
      [flake8](http://flake8.pycqa.org/en/latest/).
- [x] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [x] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org/) to type check your code.
- [x] Tests have been added for any new functionality or bug fixes.
- [ ] All linting and tests pass.

Note that the CI system will run all the above checks. But it will be much more efficient if you already fix most
errors prior to submitting the PR. It is highly recommended that you use the pre-commit hook provided in the pymatgen
repository. Simply `cp pre-commit .git/hooks` and a check will be run prior to allowing commits.

### CODE REVIEW

**Comment by munrojm** [comment]
@mkhorton @shyuep I have realized that `msgpack` is required as an install to properly pull BS and DOS data. It only depends on cython (which is already required through scipy), and is therefore lightweight. Let me know your thoughts and if this is okay.

**Comment by mkhorton** [comment]
Interesting, I have no objections (given that it's lightweight, as you say). It could be added to the `mp-api` requirements.

**Comment by munrojm** [comment]
> Interesting, I have no objections (given that it's lightweight, as you say). It could be added to the `mp-api` requirements.

Indeed, that is where I have added it. I believe it used to get automatically installed with maggma, which was removed as a required dependency.

**Comment by shyuep** [comment]
msgpack is fine. Monty has it as an optional dependency too

**Comment by mkhorton** [comment]
Many thanks @munrojm! This looks good. Noting here that I'd like to make a test (TestPyPI) release prior to the next real release to double-check nothing unexpected happens.

**Pull request merged**
