### PR TITLE
Update some of the OPTIMADE aliases

### PR DESCRIPTION
**Pull request by ml-evs**
cf #3753, this PR fixes some of the broken OPTIMADE aliases.

## Summary by CodeRabbit

- **New Features**
	- Updated the `OptimadeRester` with new database aliases for enhanced connectivity options, including "alexandria", "odbx", "odbx.gnome", "alexandria.pbe", and "alexandria.pbesol".

### CODE REVIEW

**Comment by ml-evs** [comment]
@coderabbitai disable

**Comment by janosh** [comment]
Just to clarify, this does not fix the "mcloud.mc3d" provider, so @JaGeo's issue should remain open?

**Comment by ml-evs** [comment]
> ~Just to clarify, this does not fix the "mcloud.mc3d" provider, so @JaGeo's issue should remain open?~
> 
> didn't see the discussion in #3753 about the issue not reproducing

It does repro, I was just doing it badly late on a Friday evening ;) I'll try to cook up a fix (I think this came up once before)

**Comment by ml-evs** [comment]
How does calendar versioning work when you need to do another fix on the same day? :grin:

**Comment by janosh** [comment]
It doesn't. I guess you could add a `-1` suffix. Still one of several reasons calendar versioning is inferior to semantic.

**Pull request merged**
