### PR TITLE
circleci fixed

### PR DESCRIPTION
**Pull request by fraricci**
- circleci edited to compile boltztrap

### CODE REVIEW

**Comment by mkhorton** [comment]
Would it be possible to notify the BoltzTrap2 maintainers of this as well? A colleague was trying to install BoltzTrap2 recently via pip and was unable to do so / didn't realize additional CFLAGS had to be set.

**Comment by fraricci** [comment]
Yes, it's a better solution actually. It can be useful in general.
I'll do that so. Thanks

**Comment by shyuep** [comment]
@fraricci I think you need to fix the tests. Right now, the boltztrap2 tests take so long that they fail on CircleCI. Tests need to be reasonably quick (less than a minute preferably, but certainly no more than 10 mins).

**Comment by fraricci** [comment]
I'll check that. It sounds weird because in my computer test for btz2 run quickly.

**Comment by mkhorton** [comment]
Thanks!

**Pull request merged**
