### PR TITLE
Minor change for step_size in CubicSupercellTransformation.apply_transformation 

### PR DESCRIPTION
**Pull request by QuantumChemist**
Recently, @JaGeo and I had made some changes to the CubicSupercellTransformation.apply_transformation function in https://github.com/materialsproject/pymatgen/pull/3938.

I would like to set the step_size more coarse for the "cubic" supercells without the force_90_degree constraints as the previous step_size has led to unreasonable long run times for me.

### CODE REVIEW

**Comment by QuantumChemist** [comment]
@shyuep @mkhorton @janosh  could you have a look at this PR please? Thank you! 😄

**Comment by JaGeo** [comment]
I will merge this as this is a very minor change in a method that I recently implemented and all tests are passing (everything is backward compatible anyway)

**Comment by QuantumChemist** [comment]
> I will merge this as this is a very minor change in a method that I recently implemented and all tests are passing (everything is backward compatible anyway)

Thank you 😄

**Comment by JaGeo** [comment]
@QuantumChemist I overlooked something. I will revert this. Could you check again in more detail where to adapt the step size? Thanks!

**Comment by QuantumChemist** [comment]
If this change is breaking the backwards compatibility, I will find another solution for my problem.

**Comment by JaGeo** [comment]
@QuantumChemist I am happy to discuss this further.

**Pull request merged**
