### PR TITLE
Update `vasprun.converged_ionic` logic when `EDIFFG=0`

### PR DESCRIPTION
**Pull request by matthewkuner**
a new test for this has been added as well.

## Summary by CodeRabbit

- **New Features**
	- Enhanced the convergence detection logic in relaxation runs to include scenarios where `EDIFFG=0`.
- **Tests**
	- Added a new test to ensure accurate handling of specific convergence scenarios in VASP simulations.

### CODE REVIEW

**Comment by matthewkuner** [comment]
@janosh this is ready for merging

**Comment by esoteric-ephemera** [comment]
Just for context / documentation: the specific use case for `EDIFFG = 0` is to ensure that a relaxation runs for `NSW` steps. In this case, the user isn't really worried about convergence wrt forces or energy differences, and @matthewkuner's solution prevents custodian from trying to correct the calc because `Vasprun.converged_ionic = False`. You can think about this as the non-AIMD way to generate a relaxation trajectory with DFT

**Review by janosh — APPROVED** [review]
thanks @matthewkuner for this change and @esoteric-ephemera for the context! 👍

**Comment by janosh** [comment]
something wrong with the new test file it seems. can't be found for unknown reasons

**Comment by matthewkuner** [comment]
closed in favor of #3783

**Pull request closed without merging**
