### PR TITLE
Normalized DOS

### PR DESCRIPTION
**Pull request by jmmshn**
## Normalize Density of States

Currently the Density of states data is extensive (at lease when you use `Vasprun.complete_dos`).
This proposed change allow you to use call `Vasprun.complete_dos_normalized` to get the density of states in units of states $/ \text{eV} / \mathbb A^3$

### CODE REVIEW

**Comment by jmmshn** [comment]
@mkhorton, @munrojm, @janosh once this is updates and released can we update the x-axis of the Density of States display on the website to have the proper units?

**Comment by janosh** [comment]
> can we update the x-axis of the Density of States display on the website to have the proper units?

Sure thing. Let me know if there's something you need me to do.

**Comment by janosh** [comment]
Love your commit messages btw. 😄

**Comment by jmmshn** [comment]
> > can we update the x-axis of the Density of States display on the website to have the proper units?
> 
> Sure thing. Let me know if there's something you need me to do.

I think I just need a release once this get merged.  Then maybe update the data that gets pull by the API depending on @munrojm's opinion.

**Comment by jmmshn** [comment]
@janosh some tests failed due to a GitHub actions error.  I just made some minor changes to plotting module and tests are passing now.

**Comment by jmmshn** [comment]
Had a chat with Jason, will move forward and update the API once this is merged.

**Pull request merged**
