### PR TITLE
Converting LMPDATA to POSCAR

### PR DESCRIPTION
**Pull request by ucsdlxg**
## Summary

Add the code to transform from the format of the lammps Data to vasp POSCAR.

* Feature 1
* Feature 2
* Fix 1
* Fix 2

## Additional dependencies introduced (if any)

* List all new dependencies needed. While adding dependencies that bring
significantly useful functionality is perfectly fine, adding ones that 
add trivial functionality, e.g., to use one single easily implementable
function, is frowned upon. Provide a justification why that dependency is needed. 
Especially frowned upon are circular dependencies, e.g., depending on derivative
modules of pymatgen such as custodian or Fireworks.

## TODO (if any)

If this is a work-in-progress, write something about what else needs 
to be done

* Feature 1 supports a, but not b.

### CODE REVIEW

**Comment by shyuep** [comment]
The code should not convert LAMMPS to POSCAR. It should just allow a person to get a structure.

**Comment by shyuep** [comment]
There is never a reason to write code to convert one file format to another. If you are able to get a structure from LAMMPSDAta, you can already pass the structure to the Poscar class to get the Poscar object. The Structure object is the thing that links everything.

**Comment by ucsdlxg** [comment]
I understand. I just found that the lammps data file is closed to the POSCAR format. Thus it is easier to transform it to POSCAR first, and then use Poscar class to get the structure, which can link to everything. I have already obtained the POSCAR. Just use Poscar class to get the structure. Can I do it this way?

**Comment by shyuep** [comment]
No,you should not convert to poscar first. It is straightforward to parse the lammps input data to a structure.

**Comment by shyuep** [comment]
Thanks.

**Comment by shyuep** [comment]
@ucsdlxg See the version that I wrote. You should not be introducing a new method and reparse the Data file. There is already a LAMMPData.from_file to parse the data file. All you need is to convert the LAMMPSData to a structure. See the `@structure` property in the latest pymatgen. 

However, for some reason, I cannot retrieve even the Li2O structure. Pls debug.

**Comment by shyuep** [comment]
Nvm, I think the code works fine.

**Pull request merged**
