### PR TITLE
Added code to calculate NGX/NGY/NGZ NGXF/NGYF/NGZF

### PR DESCRIPTION
**Pull request by jmmshn**

### CODE REVIEW

**Comment by jmmshn** [comment]
@mkhorton for the tests I just grabbed a bunch of random calculations and check that the grids matched.
I actually check vs all 100K + calculations in my DB but only uploaded 300 to keep the file size small.

**Comment by mkhorton** [comment]
Thanks @jmmshn! Interesting you have to do a prime factorization with this too

**Comment by jmmshn** [comment]
This a was amusing for me as well.  It's because of how VASP interacts with FFTs.

**Comment by mkhorton** [comment]
Thanks @jmmshn !

**Pull request merged**
