### PR TITLE
Fix lobsterin dict inheritance and treat \t in lobsterins correctly

### PR DESCRIPTION
**Pull request by JaGeo**
## Summary

Closes https://github.com/materialsproject/pymatgen/issues/3437 and https://github.com/materialsproject/pymatgen/issues/3438.
Inheritance of the dict was not carried out correctly. I have started here with inheriting from UserDict. We will add more tests to avoid similar issues in the future.

### CODE REVIEW

**Comment by JaGeo** [comment]
@naik-aakash , I have started with the fix. I will test methods like update, delete as well. 

We could also directly implement a fix for reading lobsterins with \t

**Comment by naik-aakash** [comment]
Thanks! Thats great. So you will also fix the `reading lobsterins with \t` issue in this PR itself?

**Comment by JaGeo** [comment]
@naik-aakash You are invited to contribute to this PR. I am in the train and I don't really expect to be able to work much 😅

**Comment by naik-aakash** [comment]
> @naik-aakash You are invited to contribute to this PR. I am in the train today and I don't really expect to be able to work much on the remote connection 😅

Ah okay. Just got the invitation. Thank you 😄

**Comment by JaGeo** [comment]
I think I have now correctly implemented the inheritance from a UserDict. All standard functionalities work.

Things left to do:
- clarify how lobster reads cohpsteps (int, float): i.e., should we include a new category of lobster arguments?
-  treat \t in lobsterins incluing whether Lobster can process them and test every different functionality

**Comment by naik-aakash** [comment]
I think treating `\t` is solved as well, have updated the existing test file to check the implementation and it seems to work fine

**Comment by JaGeo** [comment]
Update: lobster can read floats and integers. It will automatically round to the next larger integer independent on whether it is a float or an integer (in version 4.1.0 and 5.0.0). I think it doesn't really matter that we print a float... Also, I think this behavior of Lobster is a bit unexpected.

**Comment by JaGeo** [comment]
@janosh , I think this would be ready for review in case you have time.

**Review by janosh — APPROVED** [review]

**Pull request merged**
