### PR TITLE
Fix for issue #1442

### PR DESCRIPTION
**Pull request by JRSuckert**
## Summary
This commit tries to fix issue #1442 in the pymatgen.io.vasp.outputs.Waveder class.

* Fix 1
The original issue is raised by the fact that the variables and member functions have the same name.
This has been fixed by prepending a underscore to the variable names.

* Fix 2
Additionally, the datatype of the records read into cder should be of type np.complex64.
This has been changed.

* Fix 3
Furthermore, the order of the reshape call for cder_data needs to be inverted, otherwise the mapping between bands, kpoints and spin won't be correct

* Feature 1
I also introduced a property function for the orbital derivative between states.

### CODE REVIEW

**Comment by shyuep** [comment]
Thanks. Can you add unittests to ensure those bugs don't recur in future?

**Comment by utf** [comment]
Based on the discussion in #1442, it seems like the datatype of the records can be float64 instead of complex64 if the wave function is generated using the gamma point version of VASP. 

Please can you also add an option in the init method called `gamma_only` which defaults to False and will toggle the datatype correctly.

**Comment by JRSuckert** [comment]
I've added the option proposed by @utf .

Regarding unit tests, I have never done them before, so I might need a bit to figure out what to test.

**Comment by JRSuckert** [comment]
Added a unit test. 
It would be great if somebody can look over it to see if its useful this way.

**Comment by shyuep** [comment]
Great. THanks. I will merge now.

**Pull request merged**
