### PR TITLE
Added local_env.py for near-neighbor finding

### PR DESCRIPTION
**Pull request by nisse3000**
In the future, the OrderParameter class from structure_analyzer.py will be moved to this module under the proposed name LocalStructOrderParas to avoid confusion with order parameters in a more global materials science-related sense. Is that desirable, @shyuep?

### CODE REVIEW

**Comment by shyuep** [comment]
Great. Can you put deprecation messages on the relevant classes in structure_analyzer? Say they will be removed with pymatgen > 2018.

**Comment by nisse3000** [comment]
Will do.

**Comment by nisse3000** [comment]
Maybe pymatgen > 2017 (so, in 2018)?

**Comment by shyuep** [comment]
Ok... forgive my lack of precision. pmg >= 2018.

**Comment by nisse3000** [comment]
OK. :-)

**Pull request merged**
